# Generated by Django 5.2.10 on 2026-02-04 09:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MscAcknowledgeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msc_sr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('read_by', models.CharField(blank=True, max_length=255, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'msc_acknowledge_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipUsersLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Created_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Updated_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Created_At', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Updated_At', models.DateTimeField(blank=True, null=True)),
                ('Temp_Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Ship_UsersLogin',
                'managed': False,
            },
        ),
    ]
