# Generated by Django 5.2.11 on 2026-02-09 05:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circular_ship', '0002_delete_shipuserslogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipUsersLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Created_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Updated_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Created_At', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Updated_At', models.DateTimeField(blank=True, null=True)),
                ('Temp_Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Ship_UsersLogin',
                'managed': False,
            },
        ),
    ]
