"""
Tests for FEAT-NOTIF-001: In-App Notifications.

PRD Reference: Docs/PRD.md Section 2.7 (FEAT-NOTIF-001)
API/RBAC Reference: Docs/BACKEND_STRUCTURE.md Sections 10.11, 11.1

Generated by: Test Backfill Agent
Date: 2026-02-07
"""

import uuid
from datetime import date, timedelta
from types import SimpleNamespace
from unittest.mock import patch

from django.test import TestCase
from rest_framework import status
from rest_framework.test import APIRequestFactory, force_authenticate

from apps.accounts.models import RoleCodes
from apps.notifications.management.commands.check_overdue_actions import Command as OverdueActionCommand
from apps.notifications.models import Notification, NotificationType, RecipientType
from apps.notifications.signals import (
    notify_car_created,
    notify_car_submitted,
    notify_car_submitted_to_dpa,
    notify_car_pic_accepted,
    notify_car_rework_requested,
    notify_car_dpa_closed,
    notify_psc_follow_up_recorded,
    notify_conflict_detected,
    notify_conflict_resolved,
    notify_physical_verification_created,
)
from apps.notifications.views import NotificationListView, MarkReadView, MarkAllReadView


def make_user(
    *,
    role: str,
    user_type: str,
    user_id: str,
    vessel_id: str | None = None,
    crew_id: str | None = None,
    employee_id: str | None = None,
):
    """Create a lightweight authenticated user stub for DRF view tests."""
    return SimpleNamespace(
        id=user_id,
        role=role,
        user_type=user_type,
        vessel_id=vessel_id,
        crew_id=crew_id,
        employee_id=employee_id,
        username=employee_id or user_id,
        display_name=user_id,
        is_authenticated=True,
    )


class BaseNotificationAPITestCase(TestCase):
    """Shared fixtures and helpers for notification API tests."""

    def setUp(self):
        self.factory = APIRequestFactory()
        self.vessel_id = str(uuid.uuid4())
        self.other_vessel_id = str(uuid.uuid4())

        self.vessel_master = make_user(
            role=RoleCodes.VESSEL_MASTER,
            user_type="VESSEL",
            user_id="vm-1",
            vessel_id=self.vessel_id,
            crew_id="KSM0001",
        )
        self.vessel_crew = make_user(
            role=RoleCodes.VESSEL_CREW,
            user_type="VESSEL",
            user_id="vc-1",
            vessel_id=self.vessel_id,
            crew_id="KSM0002",
        )
        self.office_pic = make_user(
            role=RoleCodes.OFFICE_PIC,
            user_type="OFFICE",
            user_id="office-1",
            employee_id="EMP001",
        )

        self.list_view = NotificationListView.as_view()
        self.mark_read_view = MarkReadView.as_view()
        self.mark_all_read_view = MarkAllReadView.as_view()


class TestFEAT_NOTIF_001_APIEndpoints(BaseNotificationAPITestCase):
    """
    FEAT-NOTIF-001 API coverage.

    PRD Reference: Docs/PRD.md FEAT-NOTIF-001
    API Reference: Docs/BACKEND_STRUCTURE.md Section 10.11
    """

    def test_feat_notif_001_happy_path_vessel_user_lists_only_own_notifications(self):
        """PRD FEAT-NOTIF-001: vessel user sees only notifications addressed to own crew_id."""
        own_direct = Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id=self.vessel_master.crew_id,
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_CREATED,
            title="Direct",
            message="Direct vessel-master notification",
        )
        Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id="KSM9999",
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_SUBMITTED,
            title="Broadcast",
            message="Should not be visible to unrelated vessel user",
        )
        Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id="KSM8888",
            vessel_id=self.other_vessel_id,
            notification_type=NotificationType.CAR_DPA_CLOSED,
            title="Other vessel",
            message="Should not be visible",
        )
        Notification.objects.create(
            recipient_type=RecipientType.OFFICE,
            recipient_id="EMP001",
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_SUBMITTED,
            title="Office",
            message="Should not be visible to vessel user",
        )

        request = self.factory.get("/api/psc/notifications/")
        force_authenticate(request, user=self.vessel_master)
        response = self.list_view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        visible_ids = {row["id"] for row in response.data["data"]}
        self.assertEqual(visible_ids, {str(own_direct.id)})

    def test_feat_notif_001_happy_path_office_user_lists_only_own_notifications(self):
        """PRD FEAT-NOTIF-001: office user sees only notifications addressed to own employee_id."""
        own = Notification.objects.create(
            recipient_type=RecipientType.OFFICE,
            recipient_id=self.office_pic.employee_id,
            notification_type=NotificationType.CAR_SUBMITTED,
            title="Office own",
            message="Visible to office user",
        )
        Notification.objects.create(
            recipient_type=RecipientType.OFFICE,
            recipient_id="EMP999",
            notification_type=NotificationType.CAR_SUBMITTED,
            title="Office other",
            message="Not visible to office user",
        )

        request = self.factory.get("/api/psc/notifications/")
        force_authenticate(request, user=self.office_pic)
        response = self.list_view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual([row["id"] for row in response.data["data"]], [str(own.id)])

    def test_feat_notif_001_validation_is_read_filter_and_pagination_work(self):
        """BACKEND_STRUCTURE 10.11: list supports is_read filter and paginated response."""
        for index in range(3):
            Notification.objects.create(
                recipient_type=RecipientType.OFFICE,
                recipient_id=self.office_pic.employee_id,
                notification_type=NotificationType.CAR_SUBMITTED,
                title=f"Item {index}",
                message="Pagination coverage",
                is_read=index == 0,
            )

        request = self.factory.get("/api/psc/notifications/?is_read=false&page=1&page_size=1")
        force_authenticate(request, user=self.office_pic)
        response = self.list_view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data["data"]), 1)
        self.assertEqual(response.data["pagination"]["page_size"], 1)
        self.assertEqual(response.data["pagination"]["total_count"], 2)

    def test_feat_notif_001_rbac_invalid_user_type_is_rejected(self):
        """API contract FEAT-NOTIF-001: unknown user_type is rejected with 403."""
        unknown_user = make_user(
            role=RoleCodes.VESSEL_MASTER,
            user_type="UNKNOWN",
            user_id="unknown-1",
        )

        request = self.factory.get("/api/psc/notifications/")
        force_authenticate(request, user=unknown_user)
        response = self.list_view(request)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(response.data["error"], "INVALID_USER_TYPE")

    def test_feat_notif_001_happy_path_mark_read_updates_only_owned_notifications(self):
        """BACKEND_STRUCTURE 10.11: mark-read updates only notifications in caller visibility scope."""
        own_unread = Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id=self.vessel_crew.crew_id,
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_CREATED,
            title="Own unread",
            message="Should be marked read",
            is_read=False,
        )
        other_unread = Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id="KSM9999",
            vessel_id=self.other_vessel_id,
            notification_type=NotificationType.CAR_CREATED,
            title="Other unread",
            message="Should remain unread",
            is_read=False,
        )
        same_vessel_other_crew = Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id="KSM7777",
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_CREATED,
            title="Same vessel other crew unread",
            message="Should remain unread",
            is_read=False,
        )

        request = self.factory.post(
            "/api/psc/notifications/mark-read/",
            {"notification_ids": [str(own_unread.id), str(other_unread.id), str(same_vessel_other_crew.id)]},
            format="json",
        )
        force_authenticate(request, user=self.vessel_crew)
        response = self.mark_read_view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["marked_count"], 1)
        own_unread.refresh_from_db()
        other_unread.refresh_from_db()
        same_vessel_other_crew.refresh_from_db()
        self.assertTrue(own_unread.is_read)
        self.assertFalse(other_unread.is_read)
        self.assertFalse(same_vessel_other_crew.is_read)

    def test_feat_notif_001_happy_path_mark_all_read_marks_only_caller_notifications(self):
        """BACKEND_STRUCTURE 10.11: mark-all-read marks all unread notifications for current user only."""
        own = Notification.objects.create(
            recipient_type=RecipientType.OFFICE,
            recipient_id=self.office_pic.employee_id,
            notification_type=NotificationType.CAR_SUBMITTED,
            title="Own unread",
            message="Marked by mark-all",
            is_read=False,
        )
        other = Notification.objects.create(
            recipient_type=RecipientType.OFFICE,
            recipient_id="EMP999",
            notification_type=NotificationType.CAR_SUBMITTED,
            title="Other unread",
            message="Should remain unread",
            is_read=False,
        )

        request = self.factory.post("/api/psc/notifications/mark-all-read/", {}, format="json")
        force_authenticate(request, user=self.office_pic)
        response = self.mark_all_read_view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["marked_count"], 1)
        own.refresh_from_db()
        other.refresh_from_db()
        self.assertTrue(own.is_read)
        self.assertFalse(other.is_read)

    def test_feat_notif_001_mark_all_read_for_vessel_does_not_mark_other_crew_same_vessel(self):
        """mark-all-read for vessel user must not mark another crew member's notifications."""
        own = Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id=self.vessel_crew.crew_id,
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_CREATED,
            title="Own unread",
            message="Should be marked read",
            is_read=False,
        )
        other_same_vessel = Notification.objects.create(
            recipient_type=RecipientType.CREW,
            recipient_id="KSM0099",
            vessel_id=self.vessel_id,
            notification_type=NotificationType.CAR_CREATED,
            title="Other crew unread",
            message="Should remain unread",
            is_read=False,
        )

        request = self.factory.post("/api/psc/notifications/mark-all-read/", {}, format="json")
        force_authenticate(request, user=self.vessel_crew)
        response = self.mark_all_read_view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["marked_count"], 1)
        own.refresh_from_db()
        other_same_vessel.refresh_from_db()
        self.assertTrue(own.is_read)
        self.assertFalse(other_same_vessel.is_read)

    def test_feat_notif_001_error_mark_read_requires_non_empty_notification_ids(self):
        """BACKEND_STRUCTURE 10.11: mark-read validates request payload shape."""
        request = self.factory.post(
            "/api/psc/notifications/mark-read/",
            {"notification_ids": []},
            format="json",
        )
        force_authenticate(request, user=self.office_pic)
        response = self.mark_read_view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("notification_ids", response.data)


class TestFEAT_NOTIF_001_TriggerFunctions(TestCase):
    """
    FEAT-NOTIF-001 trigger-function coverage.

    PRD Reference: Docs/PRD.md FEAT-NOTIF-001
    """

    def setUp(self):
        self.vessel_id = str(uuid.uuid4())
        self.car = SimpleNamespace(
            id=uuid.uuid4(),
            car_number="PSC-2026-001",
            deficiency=SimpleNamespace(def_code="10101"),
        )
        self.follow_up_inspection = SimpleNamespace(
            id=uuid.uuid4(),
            port_place="Singapore",
        )
        self.pv = SimpleNamespace(id=uuid.uuid4())

    @patch("apps.accounts.models.MasterRoleByVessel.objects.extra")
    @patch("apps.accounts.models.MasterRoleByVessel.objects.filter", side_effect=Exception("uuid conversion failed"))
    def test_feat_notif_001_office_lookup_falls_back_to_try_cast_query(
        self,
        _mock_filter,
        mock_extra,
    ):
        """Office recipient lookup should use SQL Server-safe fallback when direct UUID filtering fails."""
        from apps.notifications.signals import _get_office_users_for_vessel

        extra_qs = mock_extra.return_value
        extra_qs.values_list.return_value = ["EMP001", " EMP001 ", "EMP002", None]

        office_ids = _get_office_users_for_vessel(self.vessel_id)

        self.assertEqual(office_ids, ["EMP001", "EMP002"])

    @patch("apps.accounts.models.HRM501.objects.extra")
    @patch("apps.accounts.models.HRM501.objects.filter", side_effect=Exception("uuid conversion failed"))
    def test_feat_notif_001_vessel_master_lookup_falls_back_to_try_cast_query(
        self,
        _mock_filter,
        mock_extra,
    ):
        """Master lookup should use SQL Server-safe fallback when direct UUID filtering fails."""
        from apps.notifications.signals import _get_vessel_master_crew_ids

        extra_qs = mock_extra.return_value
        extra_qs.values_list.return_value = [
            ("KSM0001", "Master"),
            ("KSM0002", "Able Seaman"),
        ]

        master_ids = _get_vessel_master_crew_ids(self.vessel_id)

        self.assertEqual(master_ids, ["KSM0001"])

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001", "KSM0002"])
    def test_feat_notif_001_happy_path_car_created_notifies_vessel_master(self, _mock_master_ids, mock_create):
        """PRD FEAT-NOTIF-001: CAR_CREATED notifies vessel master recipients."""
        notify_car_created(self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        for call in mock_create.call_args_list:
            self.assertEqual(call.kwargs["notification_type"], NotificationType.CAR_CREATED)
            self.assertEqual(call.kwargs["recipient_type"], RecipientType.CREW)

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_office_users_for_vessel", return_value=["EMP001", "EMP002"])
    def test_feat_notif_001_happy_path_car_submitted_notifies_pic_ssqe_pool(self, _mock_office_ids, mock_create):
        """PRD FEAT-NOTIF-001: CAR_SUBMITTED notifies assigned office recipients."""
        notify_car_submitted(self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        for call in mock_create.call_args_list:
            self.assertEqual(call.kwargs["notification_type"], NotificationType.CAR_SUBMITTED)
            self.assertEqual(call.kwargs["recipient_type"], RecipientType.OFFICE)

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_office_users_for_vessel", return_value=["EMPDPA01"])
    def test_feat_notif_001_happy_path_car_submitted_to_dpa_notifies_dpa_pool(self, _mock_dpa_ids, mock_create):
        """Workflow SUBMIT_TO_DPA should notify assigned DPA office recipients."""
        notify_car_submitted_to_dpa(self.car, self.vessel_id)

        mock_create.assert_called_once()
        kwargs = mock_create.call_args.kwargs
        self.assertEqual(kwargs["notification_type"], NotificationType.CAR_SUBMITTED)
        self.assertEqual(kwargs["recipient_type"], RecipientType.OFFICE)
        self.assertEqual(kwargs["recipient_id"], "EMPDPA01")
        self.assertIn("submitted to DPA", kwargs["title"])

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001"])
    def test_feat_notif_001_happy_path_pic_accepted_and_dpa_closed_notify_vessel(self, _mock_master_ids, mock_create):
        """PRD FEAT-NOTIF-001: PIC_ACCEPTED and DPA_CLOSED each notify vessel master."""
        notify_car_pic_accepted(self.car, self.vessel_id)
        notify_car_dpa_closed(self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        types = [call.kwargs["notification_type"] for call in mock_create.call_args_list]
        self.assertEqual(types, [NotificationType.CAR_PIC_ACCEPTED, NotificationType.CAR_DPA_CLOSED])

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001"])
    @patch("apps.accounts.models.HRM501.objects.filter")
    @patch("apps.car.models.CorrectiveAction.objects.filter")
    def test_feat_notif_001_happy_path_rework_requested_notifies_vessel_and_action_owners(
        self,
        mock_action_filter,
        mock_hrm_filter,
        _mock_master_ids,
        mock_create,
    ):
        """PRD FEAT-NOTIF-001: rework request notifies vessel master and assigned action owners."""
        owner_id = uuid.uuid4()
        action_qs = mock_action_filter.return_value
        action_qs.values_list.return_value.distinct.return_value = [owner_id]
        mock_hrm_filter.return_value.first.return_value = SimpleNamespace(CrewID="KSM0002")

        notify_car_rework_requested(self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        recipients = {call.kwargs["recipient_id"] for call in mock_create.call_args_list}
        self.assertEqual(recipients, {"KSM0001", "KSM0002"})
        self.assertTrue(
            all(
                call.kwargs["notification_type"] == NotificationType.CAR_REWORK_REQUESTED
                for call in mock_create.call_args_list
            )
        )

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001"])
    @patch("apps.notifications.signals._get_active_crew_member")
    @patch("apps.car.models.CorrectiveAction.objects.filter")
    def test_feat_notif_001_rework_requested_notifies_assigned_crew_even_without_action_owners(
        self,
        mock_action_filter,
        mock_get_active_crew,
        _mock_master_ids,
        mock_create,
    ):
        """Rework should notify assigned deficiency crew even when no corrective-action owners exist."""
        assigned_crew_uuid = uuid.uuid4()
        self.car.deficiency.assigned_crew_id = assigned_crew_uuid

        action_qs = mock_action_filter.return_value
        action_qs.values_list.return_value.distinct.return_value = []
        mock_get_active_crew.return_value = SimpleNamespace(CrewID="KSM0009")

        notify_car_rework_requested(self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        recipients = {call.kwargs["recipient_id"] for call in mock_create.call_args_list}
        self.assertEqual(recipients, {"KSM0001", "KSM0009"})
        self.assertTrue(
            all(
                call.kwargs["notification_type"] == NotificationType.CAR_REWORK_REQUESTED
                for call in mock_create.call_args_list
            )
        )

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001"])
    @patch("apps.notifications.signals._get_office_users_for_vessel", return_value=["EMP001"])
    def test_feat_notif_001_happy_path_follow_up_notifies_office_and_vessel(
        self,
        _mock_office_ids,
        _mock_master_ids,
        mock_create,
    ):
        """PRD FEAT-NOTIF-001: follow-up notification goes to both office and vessel users."""
        notify_psc_follow_up_recorded(self.follow_up_inspection, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        recipient_types = {call.kwargs["recipient_type"] for call in mock_create.call_args_list}
        self.assertEqual(recipient_types, {RecipientType.OFFICE, RecipientType.CREW})

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001"])
    def test_feat_notif_001_happy_path_conflict_detected_and_resolved_notify_vessel(
        self,
        _mock_master_ids,
        mock_create,
    ):
        """PRD FEAT-NOTIF-001: conflict detected and resolved notifications reach vessel master."""
        notify_conflict_detected(self.vessel_id, "CAR", str(self.car.id))
        notify_conflict_resolved(self.vessel_id, "CAR", str(self.car.id), "KEEP_SERVER")

        self.assertEqual(mock_create.call_count, 2)
        notif_types = [call.kwargs["notification_type"] for call in mock_create.call_args_list]
        self.assertEqual(notif_types, [NotificationType.CONFLICT_DETECTED, NotificationType.CONFLICT_RESOLVED])

    @patch("apps.notifications.signals.create_notification")
    @patch("apps.notifications.signals._get_vessel_master_crew_ids", return_value=["KSM0001"])
    def test_feat_notif_001_happy_path_physical_verification_created_notifies_vessel(
        self,
        _mock_master_ids,
        mock_create,
    ):
        """PRD FEAT-NOTIF-001: PHYSICAL_VERIFICATION_CREATED notifies vessel master."""
        notify_physical_verification_created(self.pv, self.car, self.vessel_id)

        mock_create.assert_called_once()
        self.assertEqual(
            mock_create.call_args.kwargs["notification_type"],
            NotificationType.PHYSICAL_VERIFICATION_CREATED,
        )


class TestFEAT_NOTIF_001_OverdueNotificationRules(TestCase):
    """
    FEAT-NOTIF-001 overdue-notification rule coverage.

    PRD Reference: Docs/PRD.md FEAT-NOTIF-001
    """

    def setUp(self):
        self.command = OverdueActionCommand()
        self.vessel_id = str(uuid.uuid4())
        self.car = SimpleNamespace(car_number="PSC-2026-001")

    @patch("apps.notifications.management.commands.check_overdue_actions.create_notification")
    def test_feat_notif_001_happy_path_warning_notifies_action_owner_and_master(self, mock_create):
        """PRD FEAT-NOTIF-001: T-3 warning notifies action owner + vessel master."""
        action = SimpleNamespace(
            id=uuid.uuid4(),
            due_date=date.today() + timedelta(days=3),
            description="Action nearing due date for warning notification coverage.",
            owner_crew_id=None,
        )
        with patch.object(
            self.command,
            "_get_action_owner_and_masters",
            return_value={(RecipientType.CREW, "KSM0001"), (RecipientType.CREW, "KSM0002")},
        ):
            self.command._send_warning_notification(action, self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 2)
        self.assertTrue(
            all(
                call.kwargs["notification_type"] == NotificationType.ACTION_OVERDUE_WARNING
                for call in mock_create.call_args_list
            )
        )

    @patch("apps.notifications.management.commands.check_overdue_actions.create_notification")
    @patch("apps.notifications.management.commands.check_overdue_actions._get_office_users_for_vessel", return_value=["EMP001"])
    def test_feat_notif_001_happy_path_overdue_notifies_action_owner_master_and_office(
        self,
        _mock_office,
        mock_create,
    ):
        """PRD FEAT-NOTIF-001: overdue action notifies action owner + vessel master + office."""
        action = SimpleNamespace(
            id=uuid.uuid4(),
            due_date=date.today() - timedelta(days=2),
            description="Overdue action notification coverage entry.",
            owner_crew_id=None,
        )
        with patch.object(
            self.command,
            "_get_action_owner_and_masters",
            return_value={(RecipientType.CREW, "KSM0001"), (RecipientType.CREW, "KSM0002")},
        ):
            self.command._send_overdue_notification(action, self.car, self.vessel_id)

        self.assertEqual(mock_create.call_count, 3)
        self.assertIn(
            RecipientType.OFFICE,
            {call.kwargs["recipient_type"] for call in mock_create.call_args_list},
        )
        self.assertTrue(
            all(
                call.kwargs["notification_type"] == NotificationType.ACTION_OVERDUE
                for call in mock_create.call_args_list
            )
        )


class TestFEAT_NOTIF_001_GapClosingTests(TestCase):
    """
    FEAT-NOTIF-001: Gap-closing tests (Session 50).

    PRD Reference: Docs/PRD.md Section 2.7 (FEAT-NOTIF-001)
    Focus: Notification entity linking, content validation, and deduplication.
    """

    def setUp(self):
        self.factory = APIRequestFactory()
        self.vessel_id = uuid.uuid4()
        self.vessel_master = make_user(
            role=RoleCodes.VESSEL_MASTER,
            user_type="VESSEL",
            user_id="vm-notif-1",
            vessel_id=str(self.vessel_id),
            crew_id="KSM0001",
        )
        self.car_id = uuid.uuid4()

    def test_feat_notif_001_gap_notification_stores_entity_type_and_id(self):
        """PRD FEAT-NOTIF-001: notifications must include entity_type and entity_id for deep linking."""
        notif = Notification.objects.create(
            notification_type=NotificationType.CAR_CREATED,
            title="CAR Created",
            message="A new CAR was created for deficiency.",
            entity_type="CAR",
            entity_id=str(self.car_id),
            vessel_id=self.vessel_id,
            recipient_type=RecipientType.CREW,
            recipient_id="KSM0001",
        )

        view = NotificationListView.as_view()
        request = self.factory.get("/api/psc/notifications/")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        items = response.data["data"]
        self.assertGreaterEqual(len(items), 1)
        item = next(n for n in items if str(n["id"]) == str(notif.id))
        self.assertEqual(item["entity_type"], "CAR")
        self.assertEqual(item["entity_id"], str(self.car_id))

    def test_feat_notif_001_gap_mark_read_does_not_affect_other_users_notifications(self):
        """PRD FEAT-NOTIF-001: mark-read scoping prevents cross-user side effects."""
        other_vessel_id = uuid.uuid4()

        own_notif = Notification.objects.create(
            notification_type=NotificationType.CAR_CREATED,
            title="Own CAR Created",
            message="Own notification",
            entity_type="CAR",
            entity_id=str(self.car_id),
            vessel_id=self.vessel_id,
            recipient_type=RecipientType.CREW,
            recipient_id="KSM0001",
        )
        other_notif = Notification.objects.create(
            notification_type=NotificationType.CAR_CREATED,
            title="Other CAR Created",
            message="Other user notification",
            entity_type="CAR",
            entity_id=str(self.car_id),
            vessel_id=other_vessel_id,
            recipient_type=RecipientType.CREW,
            recipient_id="KSM0099",
        )

        view = MarkAllReadView.as_view()
        request = self.factory.post("/api/psc/notifications/mark-all-read/")
        force_authenticate(request, user=self.vessel_master)
        view(request)

        own_notif.refresh_from_db()
        other_notif.refresh_from_db()
        self.assertTrue(own_notif.is_read)
        self.assertFalse(other_notif.is_read, "Other vessel's notification should not be marked read.")
