# Generated by Django 5.2.7 on 2026-03-24 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewOnboardingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(blank=True, max_length=255, null=True)),
                ('Vessel', models.UUIDField(blank=True, null=True)),
                ('SignOnDate', models.DateTimeField(blank=True, null=True)),
                ('SignOnPort', models.CharField(blank=True, max_length=200, null=True)),
                ('CrewStatus', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verifiedByMtr', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('CycleId', models.UUIDField(blank=True, null=True)),
                ('Replacement_For', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'Crew_Onboarding_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentVessel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_id', models.UUIDField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Current Vessel',
                'verbose_name_plural': 'Current Vessels',
                'db_table': 'current_vessel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalCrewList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(blank=True, max_length=7, null=True)),
                ('CrewName', models.CharField(blank=True, max_length=100, null=True)),
                ('Crew_ref_id', models.UUIDField(blank=True, null=True)),
                ('Evl_ref_id', models.UUIDField(blank=True, null=True)),
                ('Assg_Vessel', models.UUIDField(blank=True, null=True)),
                ('Tentative_join_port', models.UUIDField(blank=True, null=True)),
                ('Tentative_join_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('Crew_Status', models.UUIDField(blank=True, null=True)),
                ('is_planned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Final_crew_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Name of the saved PDF file.', max_length=255)),
                ('filepath', models.CharField(help_text='Full path to the saved PDF file on the server.', max_length=500)),
                ('title', models.CharField(help_text="Title of the PDF content (e.g., 'Approved Logbook Entries 2023-10-27').", max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
                ('created_by', models.CharField(help_text='User who generated the PDF.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the PDF was generated and saved.')),
                ('vessel_id', models.UUIDField(blank=True, db_column='vessel_id', db_index=True, help_text='ID of the vessel the PDF relates to.', null=True)),
            ],
            options={
                'db_table': 'GeneratedPDFs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MappingORBCodeTankType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tank_type_id', models.CharField(db_column='tank_type_id', max_length=50)),
            ],
            options={
                'db_table': 'mapping_ORBCode_TankType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterAppliedRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('rank_level', models.IntegerField(blank=True, null=True)),
                ('department', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_applied_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel', models.UUIDField(blank=True, db_column='vessel', db_index=True, null=True)),
                ('date', models.DateTimeField(db_column='date')),
                ('item_no', models.CharField(db_column='item_no', max_length=50)),
                ('record_of_operation', models.TextField(blank=True, db_column='record_of_operation', null=True)),
                ('status', models.CharField(db_column='status', default='Draft', max_length=20)),
                ('submitted_by', models.CharField(blank=True, db_column='submitted_by', max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_column='submitted_at', null=True)),
                ('approved_by', models.CharField(blank=True, db_column='approved_by', max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='approved_at', null=True)),
                ('rejected_by', models.CharField(blank=True, db_column='rejected_by', max_length=50, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_column='rejected_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('entry_no', models.IntegerField(db_column='entry_no', null=True)),
                ('page_no', models.IntegerField(blank=True, null=True)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('IP', models.CharField(blank=True, max_length=255, null=True)),
                ('master_print', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Operations',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ORBCodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('part', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ORBCodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipUserMaster',
            fields=[
                ('userid', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('rankid', models.IntegerField()),
            ],
            options={
                'db_table': 'ShipUserMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VesselData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('vesselName', models.CharField(blank=True, db_column='VesselName', max_length=500, null=True)),
                ('vesselCode', models.CharField(blank=True, max_length=500, null=True)),
                ('deadweight', models.IntegerField(blank=True, null=True)),
                ('loa', models.CharField(blank=True, max_length=500, null=True)),
                ('maxdraft', models.CharField(blank=True, max_length=500, null=True)),
                ('beam', models.CharField(blank=True, max_length=500, null=True)),
                ('grt', models.CharField(blank=True, max_length=500, null=True)),
                ('nrt', models.CharField(blank=True, max_length=500, null=True)),
                ('flags', models.CharField(blank=True, max_length=500, null=True)),
                ('callsign', models.CharField(blank=True, max_length=500, null=True)),
                ('imonumber', models.CharField(blank=True, max_length=500, null=True)),
                ('hatchholds', models.CharField(blank=True, max_length=500, null=True)),
                ('swl', models.CharField(blank=True, max_length=500, null=True)),
                ('vesselothers', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('lastportofcall', models.CharField(blank=True, max_length=500, null=True)),
                ('piclub', models.UUIDField(blank=True, null=True)),
                ('classificationsociety', models.CharField(blank=True, max_length=500, null=True)),
                ('depth', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('vesseltypeid', models.UUIDField(blank=True, null=True)),
                ('shipowner', models.TextField(blank=True, null=True)),
                ('shipmanagement', models.TextField(blank=True, null=True)),
                ('propellerpitch', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('refcii', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vlsfoemissionfactor', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('lsmgoemissionfactor', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('vlsfoworking', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('lsmgoidle', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('lsmgoworking', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VesselData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VesselTankDetails',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tank_name', models.CharField(max_length=150)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('frame_from', models.IntegerField(blank=True, null=True)),
                ('frame_to', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vessel_tank_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VesselTankType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tank_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vessel_tank_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VesselType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_type_code', models.CharField(max_length=255)),
                ('vessel_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vessel_type',
                'managed': False,
            },
        ),
    ]
