/**
 * Tests for Auth Store (Zustand)
 *
 * PRD Reference: PRD.md FEAT-AUTH-001 User Authentication
 * Validation Reference: FRONTEND_GUIDELINES.md Section 4.2
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';

// ============================================================================
// MOCKS — must be set up before importing the store
// ============================================================================

const authApiMock = vi.hoisted(() => ({
  login: vi.fn(),
  logout: vi.fn(),
  refresh: vi.fn(),
  me: vi.fn(),
}));

vi.mock('@/lib/api/auth', () => ({
  authApi: authApiMock,
}));

vi.mock('@/lib/api/client', () => ({
  registerAuthStoreAccessor: vi.fn(),
}));

// Now import the store after mocks
import { useAuthStore } from './auth-store';

// ============================================================================
// HELPERS
// ============================================================================

function mockUser() {
  return {
    id: 'user-1',
    user_type: 'vessel' as const,
    full_name: 'Captain Test',
    role: 'VESSEL_MASTER',
    vessel_id: 'vessel-1',
    vessel_code: 'VES001',
    email: null,
    employee_id: null,
    crew_id: 'crew-1',
    rank: 'MASTER',
    form_ids: [],
    process_ids: [],
  };
}

function resetStore() {
  useAuthStore.setState({
    tokens: null,
    user: null,
    isAuthenticated: false,
    isLoading: false,
    isInitialized: false,
  });
}

// ============================================================================
// SETUP
// ============================================================================

beforeEach(() => {
  resetStore();
  vi.clearAllMocks();
  localStorage.clear();
});

// ============================================================================
// INITIAL STATE
// ============================================================================

describe('auth-store — initial state', () => {
  it('test_feat_auth_001_initial_state_is_unauthenticated', () => {
    const state = useAuthStore.getState();
    expect(state.tokens).toBeNull();
    expect(state.user).toBeNull();
    expect(state.isAuthenticated).toBe(false);
    expect(state.isLoading).toBe(false);
  });
});

// ============================================================================
// LOGIN
// ============================================================================

describe('auth-store — login', () => {
  it('test_feat_auth_001_happy_path_login_sets_tokens_and_user', async () => {
    const user = mockUser();
    authApiMock.login.mockResolvedValue({
      access: 'access-token',
      refresh: 'refresh-token',
      user,
    });

    const result = await useAuthStore.getState().login({
      username: 'master001',
      password: 'test123',
    });

    const state = useAuthStore.getState();
    expect(state.tokens).toEqual({ access: 'access-token', refresh: 'refresh-token' });
    expect(state.user).toEqual(user);
    expect(state.isAuthenticated).toBe(true);
    expect(state.isLoading).toBe(false);
    expect(result).toEqual(user);
  });

  it('test_feat_auth_001_login_sets_loading_during_request', async () => {
    let loadingDuringCall = false;
    authApiMock.login.mockImplementation(async () => {
      loadingDuringCall = useAuthStore.getState().isLoading;
      return { access: 'a', refresh: 'r', user: mockUser() };
    });

    await useAuthStore.getState().login({ username: 'u', password: 'p' });
    expect(loadingDuringCall).toBe(true);
    expect(useAuthStore.getState().isLoading).toBe(false);
  });

  it('test_feat_auth_001_login_failure_clears_loading_and_throws', async () => {
    authApiMock.login.mockRejectedValue(new Error('Invalid credentials'));

    await expect(
      useAuthStore.getState().login({ username: 'bad', password: 'bad' })
    ).rejects.toThrow('Invalid credentials');

    const state = useAuthStore.getState();
    expect(state.isLoading).toBe(false);
    expect(state.isAuthenticated).toBe(false);
    expect(state.tokens).toBeNull();
  });
});

// ============================================================================
// LOGOUT
// ============================================================================

describe('auth-store — logout', () => {
  it('test_feat_auth_001_happy_path_logout_clears_state', async () => {
    // Pre-populate state
    useAuthStore.setState({
      tokens: { access: 'a', refresh: 'r' },
      user: mockUser(),
      isAuthenticated: true,
    });

    authApiMock.logout.mockResolvedValue(undefined);

    await useAuthStore.getState().logout();

    const state = useAuthStore.getState();
    expect(state.tokens).toBeNull();
    expect(state.user).toBeNull();
    expect(state.isAuthenticated).toBe(false);
  });

  it('test_feat_auth_001_logout_clears_state_even_if_api_fails', async () => {
    useAuthStore.setState({
      tokens: { access: 'a', refresh: 'r' },
      user: mockUser(),
      isAuthenticated: true,
    });

    authApiMock.logout.mockRejectedValue(new Error('Network error'));

    await useAuthStore.getState().logout();

    // State should still be cleared
    expect(useAuthStore.getState().isAuthenticated).toBe(false);
    expect(useAuthStore.getState().tokens).toBeNull();
  });
});

// ============================================================================
// SET USER / SET TOKENS
// ============================================================================

describe('auth-store — setUser / setTokens', () => {
  it('test_feat_auth_001_set_user_updates_authenticated_state', () => {
    useAuthStore.getState().setUser(mockUser());
    expect(useAuthStore.getState().isAuthenticated).toBe(true);
    expect(useAuthStore.getState().user).toEqual(mockUser());
  });

  it('test_feat_auth_001_set_user_null_clears_authenticated_state', () => {
    useAuthStore.getState().setUser(mockUser());
    useAuthStore.getState().setUser(null);
    expect(useAuthStore.getState().isAuthenticated).toBe(false);
  });

  it('test_feat_auth_001_set_tokens_updates_authenticated_state', () => {
    useAuthStore.getState().setTokens({ access: 'a', refresh: 'r' });
    expect(useAuthStore.getState().isAuthenticated).toBe(true);
  });

  it('test_feat_auth_001_set_tokens_null_clears_authenticated_state', () => {
    useAuthStore.getState().setTokens({ access: 'a', refresh: 'r' });
    useAuthStore.getState().setTokens(null);
    expect(useAuthStore.getState().isAuthenticated).toBe(false);
  });
});

// ============================================================================
// REFRESH TOKENS
// ============================================================================

describe('auth-store — refreshTokens', () => {
  it('test_feat_auth_001_refresh_returns_null_without_tokens', async () => {
    const result = await useAuthStore.getState().refreshTokens();
    expect(result).toBeNull();
  });

  it('test_feat_auth_001_refresh_failure_clears_auth_state', async () => {
    // Create a non-expired refresh token (exp = 1 hour from now)
    const payload = { exp: Math.floor(Date.now() / 1000) + 3600 };
    const fakeRefresh = `header.${btoa(JSON.stringify(payload))}.sig`;

    useAuthStore.setState({
      tokens: { access: 'expired', refresh: fakeRefresh },
      user: mockUser(),
      isAuthenticated: true,
    });

    authApiMock.refresh.mockRejectedValue(new Error('Token expired'));

    const result = await useAuthStore.getState().refreshTokens();

    expect(result).toBeNull();
    expect(useAuthStore.getState().isAuthenticated).toBe(false);
    expect(useAuthStore.getState().tokens).toBeNull();
  });
});

// ============================================================================
// INITIALIZE
// ============================================================================

describe('auth-store — initialize', () => {
  it('test_feat_auth_001_initialize_clears_stale_authenticated_state_when_access_missing', async () => {
    useAuthStore.setState({
      tokens: null,
      user: mockUser(),
      isAuthenticated: true,
      isLoading: false,
      isInitialized: false,
    });

    await useAuthStore.getState().initialize();

    const state = useAuthStore.getState();
    expect(state.tokens).toBeNull();
    expect(state.user).toBeNull();
    expect(state.isAuthenticated).toBe(false);
    expect(state.isLoading).toBe(false);
    expect(state.isInitialized).toBe(true);
  });
});
