/**
 * Tests for use-auth hook — pure utility functions
 *
 * PRD Reference: PRD.md FEAT-AUTH-001, FEAT-AUTH-002
 * RBAC Reference: BACKEND_STRUCTURE.md Section 11.1
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import {
  isVesselRole,
  isOfficeRole,
  canPerformPICActions,
  canPerformDPAActions,
  classifyVesselRank,
  canAccessReportsFeature,
  canImportOpenSourceFeature,
} from './use-auth';

// ============================================================================
// isVesselRole
// ============================================================================

describe('isVesselRole', () => {
  it('test_feat_auth_002_vessel_master_is_vessel', () => {
    expect(isVesselRole('VESSEL_MASTER')).toBe(true);
  });

  it('test_feat_auth_002_vessel_crew_is_vessel', () => {
    expect(isVesselRole('VESSEL_CREW')).toBe(true);
  });

  it('test_feat_auth_002_office_pic_is_not_vessel', () => {
    expect(isVesselRole('OFFICE_PIC')).toBe(false);
  });

  it('test_feat_auth_002_dpa_is_not_vessel', () => {
    expect(isVesselRole('DPA')).toBe(false);
  });

  it('test_feat_auth_002_undefined_is_not_vessel', () => {
    expect(isVesselRole(undefined)).toBe(false);
  });
});

// ============================================================================
// isOfficeRole
// ============================================================================

describe('isOfficeRole', () => {
  it('test_feat_auth_002_office_pic_is_office', () => {
    expect(isOfficeRole('OFFICE_PIC')).toBe(true);
  });

  it('test_feat_auth_002_office_ssqe_is_office', () => {
    expect(isOfficeRole('OFFICE_SSQE')).toBe(true);
  });

  it('test_feat_auth_002_office_supt_is_office', () => {
    expect(isOfficeRole('OFFICE_SUPT')).toBe(true);
  });

  it('test_feat_auth_002_dpa_is_office', () => {
    expect(isOfficeRole('DPA')).toBe(true);
  });

  it('test_feat_auth_002_physical_verifier_is_office', () => {
    expect(isOfficeRole('PHYSICAL_VERIFIER')).toBe(true);
  });

  it('test_feat_auth_002_vessel_master_is_not_office', () => {
    expect(isOfficeRole('VESSEL_MASTER')).toBe(false);
  });

  it('test_feat_auth_002_vessel_crew_is_not_office', () => {
    expect(isOfficeRole('VESSEL_CREW')).toBe(false);
  });

  it('test_feat_auth_002_undefined_is_not_office', () => {
    expect(isOfficeRole(undefined)).toBe(false);
  });
});

// ============================================================================
// canPerformPICActions
// ============================================================================

describe('canPerformPICActions', () => {
  it('test_feat_auth_002_pic_can_perform_pic_actions', () => {
    expect(canPerformPICActions('OFFICE_PIC')).toBe(true);
  });

  it('test_feat_auth_002_ssqe_can_perform_pic_actions', () => {
    expect(canPerformPICActions('OFFICE_SSQE')).toBe(true);
  });

  it('test_feat_auth_002_supt_can_perform_pic_actions', () => {
    expect(canPerformPICActions('OFFICE_SUPT')).toBe(true);
  });

  it('test_feat_auth_002_dpa_can_perform_pic_actions', () => {
    expect(canPerformPICActions('DPA')).toBe(true);
  });

  it('test_feat_auth_002_vessel_master_cannot_perform_pic_actions', () => {
    expect(canPerformPICActions('VESSEL_MASTER')).toBe(false);
  });

  it('test_feat_auth_002_physical_verifier_cannot_perform_pic_actions', () => {
    expect(canPerformPICActions('PHYSICAL_VERIFIER')).toBe(false);
  });

  it('test_feat_auth_002_undefined_cannot_perform_pic_actions', () => {
    expect(canPerformPICActions(undefined)).toBe(false);
  });
});

// ============================================================================
// canPerformDPAActions
// ============================================================================

describe('canPerformDPAActions', () => {
  it('test_feat_auth_002_dpa_can_perform_dpa_actions', () => {
    expect(canPerformDPAActions('DPA')).toBe(true);
  });

  it('test_feat_auth_002_pic_cannot_perform_dpa_actions', () => {
    expect(canPerformDPAActions('OFFICE_PIC')).toBe(false);
  });

  it('test_feat_auth_002_vessel_master_cannot_perform_dpa_actions', () => {
    expect(canPerformDPAActions('VESSEL_MASTER')).toBe(false);
  });

  it('test_feat_auth_002_undefined_cannot_perform_dpa_actions', () => {
    expect(canPerformDPAActions(undefined)).toBe(false);
  });
});

// ============================================================================
// DefIntel RBAC helpers
// ============================================================================

describe('classifyVesselRank', () => {
  it('classifies master rank', () => {
    expect(classifyVesselRank('Master')).toBe('MASTER');
  });

  it('classifies chief officer rank', () => {
    expect(classifyVesselRank('Chief Officer')).toBe('CO');
  });

  it('classifies chief engineer rank', () => {
    expect(classifyVesselRank('Chief Engineer')).toBe('CE');
  });

  it('classifies second engineer rank', () => {
    expect(classifyVesselRank('2nd Engineer')).toBe('2E');
  });
});

describe('canAccessReportsFeature', () => {
  it('allows office users', () => {
    expect(canAccessReportsFeature('office', 'OFFICE_PIC', null)).toBe(true);
  });

  it('allows vessel master role', () => {
    expect(canAccessReportsFeature('vessel', 'VESSEL_MASTER', null)).toBe(true);
  });

  it('allows vessel 2e rank', () => {
    expect(canAccessReportsFeature('vessel', 'VESSEL_CREW', '2nd Engineer')).toBe(true);
  });

  it('denies other vessel ranks', () => {
    expect(canAccessReportsFeature('vessel', 'VESSEL_CREW', 'Bosun')).toBe(false);
  });
});

describe('canImportOpenSourceFeature', () => {
  it('allows office import', () => {
    expect(canImportOpenSourceFeature('office')).toBe(true);
  });

  it('blocks vessel import', () => {
    expect(canImportOpenSourceFeature('vessel')).toBe(false);
  });
});
