# Generated by Django 5.2.10 on 2026-02-06 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('CREW', 'Crew'), ('OFFICE', 'Office')], max_length=20)),
                ('recipient_id', models.CharField(max_length=100)),
                ('vessel_id', models.UUIDField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('CAR_CREATED', 'CAR Created'), ('CAR_SUBMITTED', 'CAR Submitted'), ('CAR_PIC_ACCEPTED', 'CAR PIC Accepted'), ('CAR_REWORK_REQUESTED', 'CAR Rework Requested'), ('CAR_DPA_CLOSED', 'CAR DPA Closed'), ('ACTION_OVERDUE_WARNING', 'Action Overdue Warning'), ('ACTION_OVERDUE', 'Action Overdue'), ('PSC_FOLLOW_UP_RECORDED', 'PSC Follow-up Recorded'), ('CONFLICT_DETECTED', 'Conflict Detected'), ('CONFLICT_RESOLVED', 'Conflict Resolved'), ('PHYSICAL_VERIFICATION_CREATED', 'Physical Verification Created')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('entity_type', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'psc_notification',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id'], name='ix_psc_notif_recipient'), models.Index(fields=['vessel_id'], name='ix_psc_notif_vessel_id'), models.Index(fields=['is_read'], name='ix_psc_notif_is_read'), models.Index(fields=['-created_date'], name='ix_psc_notif_created_date')],
            },
        ),
    ]
