# Generated by Django 5.2.10 on 2026-02-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_car_reopened_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CAR_CREATED', 'CAR Created'), ('CAR_SUBMITTED', 'CAR Submitted'), ('CAR_PIC_ACCEPTED', 'CAR PIC Accepted'), ('CAR_REWORK_REQUESTED', 'CAR Rework Requested'), ('CAR_REOPENED', 'CAR Reopened'), ('CAR_DPA_CLOSED', 'CAR DPA Closed'), ('INSPECTION_DPA_CLOSED', 'Inspection DPA Closed'), ('ACTION_OVERDUE_WARNING', 'Action Overdue Warning'), ('ACTION_OVERDUE', 'Action Overdue'), ('PSC_FOLLOW_UP_RECORDED', 'PSC Follow-up Recorded'), ('CONFLICT_DETECTED', 'Conflict Detected'), ('CONFLICT_RESOLVED', 'Conflict Resolved'), ('PHYSICAL_VERIFICATION_CREATED', 'Physical Verification Created'), ('DEF_ASSIGNED', 'Deficiency Assigned')], max_length=50),
        ),
    ]
