# Generated by Django 5.2.12 on 2026-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CAR_CREATED', 'CAR Created'), ('CAR_SUBMITTED', 'CAR Submitted'), ('CAR_PIC_ACCEPTED', 'CAR PIC Accepted'), ('CAR_REWORK_REQUESTED', 'CAR Rework Requested'), ('CAR_REOPENED', 'CAR Reopened'), ('CAR_DPA_CLOSED', 'CAR DPA Closed'), ('INSPECTION_DPA_CLOSED', 'Inspection DPA Closed'), ('ACTION_OVERDUE_WARNING', 'Action Overdue Warning'), ('ACTION_OVERDUE', 'Action Overdue'), ('PSC_FOLLOW_UP_RECORDED', 'PSC Follow-up Recorded'), ('CONFLICT_DETECTED', 'Conflict Detected'), ('CONFLICT_RESOLVED', 'Conflict Resolved'), ('PHYSICAL_VERIFICATION_CREATED', 'Physical Verification Created'), ('DEF_ASSIGNED', 'Deficiency Assigned'), ('CIRCULAR_CREATED', 'Circular Created'), ('CIRCULAR_PENDING_APPROVAL', 'Circular Pending Approval'), ('CIRCULAR_APPROVED', 'Circular Approved'), ('CIRCULAR_REJECTED', 'Circular Rejected'), ('NEAR_MISS_SUBMITTED', 'Near Miss Submitted'), ('NEAR_MISS_HOD_REVIEW_COMPLETE', 'Near Miss HOD Review Complete'), ('NEAR_MISS_REWORK_REQUIRED', 'Near Miss Rework Required'), ('NEAR_MISS_READY_FOR_OFFICE_COMMENTS', 'Near Miss Ready for Office Comments'), ('NEAR_MISS_FLEET_ALERT', 'Near Miss Fleet Alert'), ('NEAR_MISS_FLEET_ALERT_NUDGE_DAY_5', 'Near Miss Fleet Alert Nudge Day 5'), ('NEAR_MISS_FLEET_ALERT_NUDGE_DAY_6', 'Near Miss Fleet Alert Nudge Day 6'), ('NEAR_MISS_FLEET_ALERT_ESCALATION_DAY_8', 'Near Miss Fleet Alert Escalation Day 8'), ('INCIDENT_PHASE_2_HANDOFF_REQUIRED', 'Incident Phase 2 Handoff Required'), ('INCIDENT_PHASE_2_SUBMITTED', 'Incident Phase 2 Submitted')], max_length=50),
        ),
    ]
