# Generated by Django 5.2.10 on 2026-02-04 09:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewOnboardingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(blank=True, max_length=255, null=True)),
                ('Vessel', models.UUIDField(blank=True, null=True)),
                ('SignOnDate', models.DateTimeField(blank=True, null=True)),
                ('SignOnPort', models.CharField(blank=True, max_length=200, null=True)),
                ('CrewStatus', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verifiedByMtr', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('CycleId', models.UUIDField(blank=True, null=True)),
                ('Replacement_For', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'Crew_Onboarding_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HRM501',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('join_date', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_role', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_location', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('eng_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('eng_written', models.CharField(blank=True, max_length=255, null=True)),
                ('eng_understanding', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('upload_photo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_verified_forwarded', models.BooleanField(blank=True, null=True)),
                ('forwarded_to', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rejected', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_sign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skypeID', models.CharField(blank=True, max_length=255, null=True)),
                ('ProfileCompletionContainer', models.CharField(blank=True, max_length=3, null=True)),
                ('notificationCount', models.CharField(blank=True, max_length=255, null=True)),
                ('CrewID', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'HRM501',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterAppliedRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'master_applied_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Msc2ndSubCat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'msc_2nd_sub_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'msc_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dept', models.UUIDField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('office_instructions', models.TextField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('publish_status', models.IntegerField()),
                ('publish_comment', models.TextField(blank=True, null=True)),
                ('published_by', models.CharField(blank=True, max_length=255, null=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('is_superseeded', models.BooleanField(default=False, null=True)),
                ('superseeded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('attachment_path', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('vessel_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'msc_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_sr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('crew_id', models.CharField(max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField()),
            ],
            options={
                'db_table': 'msc_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'msc_priority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField(default=uuid.uuid4)),
                ('profile_name', models.CharField(max_length=255)),
                ('work_side', models.BooleanField()),
                ('form_ids', models.TextField(blank=True, null=True)),
                ('process_ids', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscRankAssigned',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msc_sr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_id', models.UUIDField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'msc_rank_assigned',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscShipNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_sr_no_val', models.CharField(blank=True, db_column='msc_sr_no_', max_length=255, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'msc_ship_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscSubCat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'msc_sub_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'msc_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VesselData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('vesselName', models.CharField(blank=True, max_length=255, null=True)),
                ('vesselCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'VesselData',
                'managed': False,
            },
        ),
    ]
