# Generated by Django 5.2.11 on 2026-02-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circular', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrewOnboardingHistory',
        ),
        migrations.DeleteModel(
            name='MasterAppliedRank',
        ),
        migrations.DeleteModel(
            name='VesselData',
        ),
        migrations.AlterModelTable(
            name='mscprofile',
            table='msc_profiles',
        ),
    ]
