# Generated by Django 5.2.11 on 2026-02-09 05:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circular', '0002_delete_crewonboardinghistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewOnboardingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(blank=True, max_length=255, null=True)),
                ('Vessel', models.UUIDField(blank=True, null=True)),
                ('SignOnDate', models.DateTimeField(blank=True, null=True)),
                ('SignOnPort', models.CharField(blank=True, max_length=200, null=True)),
                ('CrewStatus', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verifiedByMtr', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('CycleId', models.UUIDField(blank=True, null=True)),
                ('Replacement_For', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'Crew_Onboarding_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterAppliedRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('rank_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_applied_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VesselData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('vesselName', models.CharField(blank=True, max_length=255, null=True)),
                ('vesselCode', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'VesselData',
                'managed': False,
            },
        ),
    ]
