# Generated by Django 5.2.11 on 2026-02-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circular', '0003_crewonboardinghistory_masterappliedrank_vesseldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrewOnboardingHistory',
        ),
        migrations.DeleteModel(
            name='MasterAppliedRank',
        ),
        migrations.DeleteModel(
            name='VesselData',
        ),
    ]
