[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main,mypy_drf_plugin.main
files = apps,core,conftest.py,manage.py
exclude = (?x)(^venv/|^apps/.*/migrations/|^tests/|^nul$)
disallow_untyped_globals = False
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = False
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True

[mypy.plugins.django-stubs]
django_settings_module = core.settings_test

[mypy-mssql.*]
ignore_missing_imports = True
