/**
 * Tests for AuthGuard Component
 *
 * PRD Reference: PRD.md FEAT-AUTH-001 User Authentication
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen } from '@testing-library/react';

// ============================================================================
// MOCKS
// ============================================================================

const useAuthMock = vi.hoisted(() => ({
  isAuthenticated: false,
  isInitialized: true,
  isLoading: false,
}));

vi.mock('@/hooks/use-auth', () => ({
  useAuth: () => useAuthMock,
  default: () => useAuthMock,
}));

vi.mock('react-router-dom', () => ({
  Navigate: ({ to, state }: { to: string; state?: unknown }) => (
    <div data-testid="navigate" data-to={to} data-state={JSON.stringify(state)} />
  ),
  useLocation: () => ({ pathname: '/inspections' }),
}));

import { AuthGuard } from './auth-guard';

// ============================================================================
// SETUP
// ============================================================================

beforeEach(() => {
  useAuthMock.isAuthenticated = false;
  useAuthMock.isInitialized = true;
  useAuthMock.isLoading = false;
});

// ============================================================================
// TESTS
// ============================================================================

describe('AuthGuard', () => {
  it('test_feat_auth_001_happy_path_renders_children_when_authenticated', () => {
    useAuthMock.isAuthenticated = true;
    useAuthMock.isInitialized = true;

    render(
      <AuthGuard>
        <div>Protected Content</div>
      </AuthGuard>
    );

    expect(screen.getByText('Protected Content')).toBeInTheDocument();
  });

  it('test_feat_auth_001_redirects_to_login_when_not_authenticated', () => {
    useAuthMock.isAuthenticated = false;
    useAuthMock.isInitialized = true;

    render(
      <AuthGuard>
        <div>Protected Content</div>
      </AuthGuard>
    );

    expect(screen.queryByText('Protected Content')).not.toBeInTheDocument();
    const nav = screen.getByTestId('navigate');
    expect(nav.getAttribute('data-to')).toBe('/login');
  });

  it('test_feat_auth_001_preserves_return_path_on_redirect', () => {
    useAuthMock.isAuthenticated = false;
    useAuthMock.isInitialized = true;

    render(
      <AuthGuard>
        <div>Protected</div>
      </AuthGuard>
    );

    const nav = screen.getByTestId('navigate');
    const state = JSON.parse(nav.getAttribute('data-state') || '{}');
    expect(state.from).toBe('/inspections');
  });

  it('test_feat_auth_001_shows_loading_while_initializing', () => {
    useAuthMock.isAuthenticated = false;
    useAuthMock.isInitialized = false;
    useAuthMock.isLoading = true;

    const { container } = render(
      <AuthGuard>
        <div>Protected Content</div>
      </AuthGuard>
    );

    expect(screen.queryByText('Protected Content')).not.toBeInTheDocument();
    // Should render the loading spinner (animate-spin class)
    expect(container.querySelector('.animate-spin')).not.toBeNull();
  });

  it('test_feat_auth_001_shows_custom_fallback_while_loading', () => {
    useAuthMock.isAuthenticated = false;
    useAuthMock.isInitialized = false;
    useAuthMock.isLoading = true;

    render(
      <AuthGuard fallback={<div>Custom Loading...</div>}>
        <div>Protected Content</div>
      </AuthGuard>
    );

    expect(screen.getByText('Custom Loading...')).toBeInTheDocument();
    expect(screen.queryByText('Protected Content')).not.toBeInTheDocument();
  });

  it('test_feat_auth_001_shows_loading_when_isLoading_true_even_if_initialized', () => {
    useAuthMock.isAuthenticated = false;
    useAuthMock.isInitialized = true;
    useAuthMock.isLoading = true;

    const { container } = render(
      <AuthGuard>
        <div>Protected Content</div>
      </AuthGuard>
    );

    // isLoading=true should show loading fallback, not redirect
    expect(screen.queryByText('Protected Content')).not.toBeInTheDocument();
    expect(container.querySelector('.animate-spin')).not.toBeNull();
  });
});
