/**
 * Tests for RoleGuard, VesselOnlyGuard, OfficeOnlyGuard, DPAOnlyGuard, PICGuard
 *
 * PRD Reference: PRD.md FEAT-AUTH-002 Role-Based Access Control
 * RBAC Reference: BACKEND_STRUCTURE.md Section 11.1
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen } from '@testing-library/react';

// ============================================================================
// MOCKS
// ============================================================================

const useAuthMock = vi.hoisted(() => ({
  role: undefined as string | undefined,
  isVessel: false,
  isOffice: false,
  isPIC: false,
  isDPA: false,
}));

vi.mock('@/hooks/use-auth', () => ({
  useAuth: () => useAuthMock,
  default: () => useAuthMock,
}));

vi.mock('react-router-dom', () => ({
  Link: ({ children, to }: { children: React.ReactNode; to: string }) => (
    <a href={to}>{children}</a>
  ),
}));

import {
  RoleGuard,
  VesselOnlyGuard,
  OfficeOnlyGuard,
  DPAOnlyGuard,
  PICGuard,
} from './role-guard';

// ============================================================================
// SETUP
// ============================================================================

beforeEach(() => {
  useAuthMock.role = undefined;
  useAuthMock.isVessel = false;
  useAuthMock.isOffice = false;
  useAuthMock.isPIC = false;
  useAuthMock.isDPA = false;
});

// ============================================================================
// RoleGuard — allowedRoles
// ============================================================================

describe('RoleGuard — allowedRoles', () => {
  it('test_feat_auth_002_happy_path_matching_role_renders_children', () => {
    useAuthMock.role = 'VESSEL_MASTER';

    render(
      <RoleGuard allowedRoles={['VESSEL_MASTER']}>
        <div>Allowed Content</div>
      </RoleGuard>
    );

    expect(screen.getByText('Allowed Content')).toBeInTheDocument();
  });

  it('test_feat_auth_002_non_matching_role_shows_access_denied', () => {
    useAuthMock.role = 'VESSEL_CREW';

    render(
      <RoleGuard allowedRoles={['VESSEL_MASTER']}>
        <div>Allowed Content</div>
      </RoleGuard>
    );

    expect(screen.queryByText('Allowed Content')).not.toBeInTheDocument();
    expect(screen.getByText('Access Denied')).toBeInTheDocument();
  });

  it('test_feat_auth_002_undefined_role_shows_access_denied', () => {
    useAuthMock.role = undefined;

    render(
      <RoleGuard allowedRoles={['VESSEL_MASTER']}>
        <div>Allowed Content</div>
      </RoleGuard>
    );

    expect(screen.queryByText('Allowed Content')).not.toBeInTheDocument();
  });

  it('test_feat_auth_002_multiple_allowed_roles_any_match_passes', () => {
    useAuthMock.role = 'DPA';

    render(
      <RoleGuard allowedRoles={['OFFICE_PIC', 'DPA']}>
        <div>Allowed Content</div>
      </RoleGuard>
    );

    expect(screen.getByText('Allowed Content')).toBeInTheDocument();
  });

  it('test_feat_auth_002_empty_allowed_roles_renders_children', () => {
    useAuthMock.role = 'VESSEL_MASTER';

    render(
      <RoleGuard allowedRoles={[]}>
        <div>Allowed Content</div>
      </RoleGuard>
    );

    expect(screen.getByText('Allowed Content')).toBeInTheDocument();
  });

  it('test_feat_auth_002_custom_fallback_rendered_on_deny', () => {
    useAuthMock.role = 'VESSEL_CREW';

    render(
      <RoleGuard allowedRoles={['DPA']} fallback={<div>Custom Denied</div>}>
        <div>Allowed Content</div>
      </RoleGuard>
    );

    expect(screen.getByText('Custom Denied')).toBeInTheDocument();
    expect(screen.queryByText('Allowed Content')).not.toBeInTheDocument();
  });
});

// ============================================================================
// RoleGuard — allowVessel / allowOffice
// ============================================================================

describe('RoleGuard — allowVessel/allowOffice', () => {
  it('test_feat_auth_002_allow_vessel_passes_for_vessel_user', () => {
    useAuthMock.isVessel = true;

    render(
      <RoleGuard allowedRoles={[]} allowVessel>
        <div>Vessel Content</div>
      </RoleGuard>
    );

    expect(screen.getByText('Vessel Content')).toBeInTheDocument();
  });

  it('test_feat_auth_002_allow_vessel_blocks_office_user', () => {
    useAuthMock.isVessel = false;
    useAuthMock.isOffice = true;

    render(
      <RoleGuard allowedRoles={[]} allowVessel>
        <div>Vessel Content</div>
      </RoleGuard>
    );

    expect(screen.queryByText('Vessel Content')).not.toBeInTheDocument();
  });

  it('test_feat_auth_002_allow_office_passes_for_office_user', () => {
    useAuthMock.isOffice = true;

    render(
      <RoleGuard allowedRoles={[]} allowOffice>
        <div>Office Content</div>
      </RoleGuard>
    );

    expect(screen.getByText('Office Content')).toBeInTheDocument();
  });
});

// ============================================================================
// VesselOnlyGuard
// ============================================================================

describe('VesselOnlyGuard', () => {
  it('test_feat_auth_002_vessel_user_sees_content', () => {
    useAuthMock.isVessel = true;

    render(
      <VesselOnlyGuard>
        <div>Vessel Only</div>
      </VesselOnlyGuard>
    );

    expect(screen.getByText('Vessel Only')).toBeInTheDocument();
  });

  it('test_feat_auth_002_office_user_sees_access_denied', () => {
    useAuthMock.isVessel = false;

    render(
      <VesselOnlyGuard>
        <div>Vessel Only</div>
      </VesselOnlyGuard>
    );

    expect(screen.queryByText('Vessel Only')).not.toBeInTheDocument();
    expect(screen.getByText('Access Denied')).toBeInTheDocument();
  });
});

// ============================================================================
// OfficeOnlyGuard
// ============================================================================

describe('OfficeOnlyGuard', () => {
  it('test_feat_auth_002_office_user_sees_content', () => {
    useAuthMock.isOffice = true;

    render(
      <OfficeOnlyGuard>
        <div>Office Only</div>
      </OfficeOnlyGuard>
    );

    expect(screen.getByText('Office Only')).toBeInTheDocument();
  });

  it('test_feat_auth_002_vessel_user_sees_access_denied', () => {
    useAuthMock.isOffice = false;

    render(
      <OfficeOnlyGuard>
        <div>Office Only</div>
      </OfficeOnlyGuard>
    );

    expect(screen.queryByText('Office Only')).not.toBeInTheDocument();
  });
});

// ============================================================================
// DPAOnlyGuard
// ============================================================================

describe('DPAOnlyGuard', () => {
  it('test_feat_auth_002_dpa_user_sees_content', () => {
    useAuthMock.isDPA = true;

    render(
      <DPAOnlyGuard>
        <div>DPA Only</div>
      </DPAOnlyGuard>
    );

    expect(screen.getByText('DPA Only')).toBeInTheDocument();
  });

  it('test_feat_auth_002_non_dpa_user_sees_access_denied', () => {
    useAuthMock.isDPA = false;

    render(
      <DPAOnlyGuard>
        <div>DPA Only</div>
      </DPAOnlyGuard>
    );

    expect(screen.queryByText('DPA Only')).not.toBeInTheDocument();
  });
});

// ============================================================================
// PICGuard
// ============================================================================

describe('PICGuard', () => {
  it('test_feat_auth_002_pic_user_sees_content', () => {
    useAuthMock.isPIC = true;

    render(
      <PICGuard>
        <div>PIC Only</div>
      </PICGuard>
    );

    expect(screen.getByText('PIC Only')).toBeInTheDocument();
  });

  it('test_feat_auth_002_non_pic_user_sees_access_denied', () => {
    useAuthMock.isPIC = false;

    render(
      <PICGuard>
        <div>PIC Only</div>
      </PICGuard>
    );

    expect(screen.queryByText('PIC Only')).not.toBeInTheDocument();
  });
});
