/**
 * Tests for Date Formatting Utilities
 *
 * Validation Reference: VALIDATION_RULES.md date display format
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import { formatDisplayDate, formatAPIDate } from './format-date';

// ============================================================================
// formatDisplayDate
// ============================================================================

describe('formatDisplayDate', () => {
  it('test_util_happy_path_formats_iso_date_correctly', () => {
    expect(formatDisplayDate('2026-02-05')).toBe('05 Feb 2026');
  });

  it('test_util_happy_path_formats_full_iso_datetime', () => {
    expect(formatDisplayDate('2026-12-25T10:30:00Z')).toBe('25 Dec 2026');
  });

  it('test_util_edge_case_null_returns_empty_string', () => {
    expect(formatDisplayDate(null)).toBe('');
  });

  it('test_util_edge_case_undefined_returns_empty_string', () => {
    expect(formatDisplayDate(undefined)).toBe('');
  });

  it('test_util_edge_case_empty_string_returns_empty_string', () => {
    expect(formatDisplayDate('')).toBe('');
  });

  it('test_util_edge_case_invalid_date_returns_original_string', () => {
    expect(formatDisplayDate('not-a-date')).toBe('not-a-date');
  });
});

// ============================================================================
// formatAPIDate
// ============================================================================

describe('formatAPIDate', () => {
  it('test_util_happy_path_formats_date_object_to_iso', () => {
    const date = new Date(2026, 1, 5); // Feb 5, 2026
    expect(formatAPIDate(date)).toBe('2026-02-05');
  });

  it('test_util_happy_path_formats_jan_1_correctly', () => {
    const date = new Date(2026, 0, 1);
    expect(formatAPIDate(date)).toBe('2026-01-01');
  });

  it('test_util_happy_path_formats_dec_31_correctly', () => {
    const date = new Date(2026, 11, 31);
    expect(formatAPIDate(date)).toBe('2026-12-31');
  });
});
