/**
 * Tests for Status Formatting Utilities
 *
 * PRD Reference: PRD.md state machines (Inspection + CAR status)
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import { getStatusVariant, getStatusLabel } from './format-status';

// ============================================================================
// getStatusVariant
// ============================================================================

describe('getStatusVariant', () => {
  it('test_util_happy_path_draft_returns_draft_variant', () => {
    expect(getStatusVariant('DRAFT')).toBe('draft');
  });

  it('test_util_happy_path_submitted_returns_submitted_variant', () => {
    expect(getStatusVariant('SUBMITTED')).toBe('submitted');
  });

  it('test_util_happy_path_closed_returns_dpa_closed_variant', () => {
    expect(getStatusVariant('CLOSED')).toBe('dpa_closed');
  });

  it('test_util_happy_path_pic_reviewed_returns_pic_reviewed_variant', () => {
    expect(getStatusVariant('PIC_REVIEWED')).toBe('pic_reviewed');
  });

  it('test_util_happy_path_pic_review_returns_pic_accepted_variant', () => {
    expect(getStatusVariant('PIC_REVIEW')).toBe('pic_accepted');
  });

  it('test_util_happy_path_returned_for_rework_returns_rework_variant', () => {
    expect(getStatusVariant('RETURNED_FOR_REWORK')).toBe('rework_requested');
  });

  it('test_util_happy_path_overdue_returns_overdue_variant', () => {
    expect(getStatusVariant('OVERDUE')).toBe('overdue');
  });

  it('test_util_happy_path_detention_returns_detention_variant', () => {
    expect(getStatusVariant('DETENTION')).toBe('detention');
  });

  it('test_util_edge_case_unknown_status_returns_default', () => {
    // Cast to bypass TS for testing unknown runtime values
    expect(getStatusVariant('UNKNOWN' as 'DRAFT')).toBe('default');
  });
});

// ============================================================================
// getStatusLabel
// ============================================================================

describe('getStatusLabel', () => {
  it('test_util_happy_path_all_statuses_have_labels', () => {
    const expected: Record<string, string> = {
      DRAFT: 'Draft',
      SUBMITTED: 'Submitted',
      CLOSED: 'Closed',
      PIC_REVIEWED: 'PIC Reviewed',
      PIC_REVIEW: 'PIC Review',
      RETURNED_FOR_REWORK: 'Rework',
      OVERDUE: 'Overdue',
      DETENTION: 'Detention',
    };

    for (const [status, label] of Object.entries(expected)) {
      expect(getStatusLabel(status as 'DRAFT'), `label for ${status}`).toBe(label);
    }
  });

  it('test_util_edge_case_unknown_status_returns_raw_value', () => {
    expect(getStatusLabel('UNKNOWN' as 'DRAFT')).toBe('UNKNOWN');
  });
});
