export const FORM_IDS = {
  DASHBOARD: 'PSC_F_001',
  INSPECTIONS: 'PSC_F_002',
  DEFICIENCIES: 'PSC_F_003',
  CARS: 'PSC_F_004',
  NOTIFICATIONS: 'PSC_F_005',
  SYNC: 'PSC_F_006',
  REPORTS: 'PSC_F_007',
  SETTINGS: 'PSC_F_008',
} as const;

export const PROCESS_IDS = {
  VIEW_DASHBOARD: 'PSC_P_001',
  VIEW_INSPECTIONS: 'PSC_P_002',
  CREATE_INSPECTION: 'PSC_P_003',
  VIEW_INSPECTION_DETAIL: 'PSC_P_004',
  EDIT_INSPECTION: 'PSC_P_005',
  SUBMIT_FOLLOW_UP: 'PSC_P_006',
  VIEW_DEFICIENCIES: 'PSC_P_007',
  ALLOCATE_DEFICIENCY: 'PSC_P_008',
  VIEW_CARS: 'PSC_P_009',
  EDIT_CAR: 'PSC_P_010',
  CAR_WORKFLOW: 'PSC_P_011',
  VIEW_NOTIFICATIONS: 'PSC_P_012',
  MANAGE_NOTIFICATIONS: 'PSC_P_013',
  VIEW_SYNC: 'PSC_P_014',
  VIEW_REPORTS: 'PSC_P_015',
  VIEW_SETTINGS: 'PSC_P_016',
} as const;
