from __future__ import annotations

import datetime

from django.db import migrations, models
from django.db.models import F, Q
from django.db.models.functions import Now


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterMscatTaxonomy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category_id", models.IntegerField()),
                ("category_name", models.CharField(max_length=128)),
                ("subcode_id", models.CharField(max_length=16)),
                ("subcode_description", models.TextField()),
                ("cause_type", models.CharField(max_length=32)),
                ("active", models.BooleanField(db_default=True, default=True)),
                ("seeded_version", models.CharField(db_default="v1.0-Round21", default="v1.0-Round21", max_length=16)),
                ("schema_version", models.IntegerField(db_default=1, default=1)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "master_mscat_taxonomy",
                "constraints": [
                    models.UniqueConstraint(fields=("subcode_id",), name="uq_master_mscat_taxonomy_subcode"),
                    models.CheckConstraint(
                        condition=Q(
                            cause_type__in=[
                                "BASIC_CAUSE",
                                "IMMEDIATE_SUBSTANDARD_ACT",
                                "IMMEDIATE_SUBSTANDARD_CONDITION",
                                "LACK_OF_CONTROL",
                            ]
                        ),
                        name="ck_master_mscat_taxonomy_cause_type",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("category_id", "subcode_id"), name="ix_master_mscat_taxonomy_category"),
                    models.Index(fields=("cause_type", "active"), name="ix_master_mscat_taxonomy_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterImmediateCauses",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category_id", models.IntegerField()),
                ("category_name", models.CharField(max_length=128)),
                ("subcode_id", models.CharField(max_length=16)),
                ("subcode_description", models.TextField()),
                ("cause_type", models.CharField(max_length=32)),
                ("active", models.BooleanField(db_default=True, default=True)),
                ("seeded_version", models.CharField(db_default="v1.0", default="v1.0", max_length=16)),
                ("schema_version", models.IntegerField(db_default=1, default=1)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "master_immediate_causes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category_id", "subcode_id"),
                        name="uq_master_immediate_causes_category_subcode",
                    ),
                    models.CheckConstraint(
                        condition=Q(
                            cause_type__in=[
                                "IMMEDIATE_SUBSTANDARD_ACT",
                                "IMMEDIATE_SUBSTANDARD_CONDITION",
                            ]
                        ),
                        name="ck_master_immediate_causes_type",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("category_id",), name="ix_master_immediate_causes_category"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterLossTypes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("loss_type_id", models.IntegerField()),
                ("loss_type_name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
                ("active", models.BooleanField(db_default=True, default=True)),
                ("seeded_version", models.CharField(db_default="v1.0", default="v1.0", max_length=16)),
            ],
            options={
                "db_table": "master_loss_types",
                "constraints": [
                    models.UniqueConstraint(fields=("loss_type_id",), name="uq_master_loss_types_loss_type_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterSoiArea",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("area_id", models.IntegerField()),
                ("area_name", models.CharField(max_length=128)),
                ("section_12_flag", models.BooleanField(default=False)),
                ("display_order", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "seeded_version",
                    models.CharField(
                        default="v1.0 (SQE S 608 - SSQE Rev 02 baseline + Section 12)",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "master_soi_area",
                "constraints": [
                    models.UniqueConstraint(fields=("area_id",), name="uq_master_soi_area_area_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterSoiAreaItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("area_id", models.IntegerField()),
                ("area_name", models.CharField(max_length=128)),
                ("subsection_id", models.IntegerField()),
                ("subsection_name", models.CharField(max_length=128)),
                ("item_number", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("tier", models.CharField(max_length=16)),
                ("active", models.BooleanField(default=True)),
                ("seeded_version", models.CharField(default="v1.0", max_length=16)),
                ("schema_version", models.IntegerField(default=1)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "master_soi_area_item",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(tier__in=["BASELINE", "CROSS_CUTTING"]),
                        name="ck_master_soi_area_item_tier",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("area_id", "subsection_id", "item_number"), name="ix_master_soi_area_item_area"),
                    models.Index(fields=("tier", "active"), name="ix_master_soi_area_item_tier"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterSoiChecklistVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version_label", models.CharField(max_length=16)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("source_description", models.CharField(max_length=256)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_default=Now())),
            ],
            options={
                "db_table": "master_soi_checklist_version",
                "constraints": [
                    models.UniqueConstraint(fields=("version_label",), name="uq_master_soi_checklist_version_label"),
                ],
                "indexes": [
                    models.Index(fields=("effective_from", "effective_to"), name="ix_master_soi_checklist_version_effective"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterSafetyIncidentType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type_code", models.CharField(max_length=32)),
                ("type_name", models.CharField(max_length=128)),
                ("imo_reportable", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "master_safety_incident_type",
                "constraints": [
                    models.UniqueConstraint(fields=("type_code",), name="uq_master_safety_incident_type_code"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterSafetyBiasGuard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("guard_code", models.CharField(max_length=32)),
                ("guard_name", models.CharField(max_length=128)),
                ("family", models.CharField(max_length=16)),
                ("description", models.TextField()),
                ("bit_position", models.PositiveSmallIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "master_safety_bias_guard",
                "constraints": [
                    models.UniqueConstraint(fields=("guard_code",), name="uq_master_safety_bias_guard_code"),
                    models.CheckConstraint(
                        condition=Q(family__in=["DNV", "ORG_TRAP"]),
                        name="ck_master_safety_bias_guard_family",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyIncident",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_number", models.CharField(max_length=32)),
                ("vessel_id", models.CharField(max_length=64)),
                ("record_type", models.CharField(max_length=16)),
                ("state", models.CharField(max_length=48)),
                ("phase", models.PositiveSmallIntegerField()),
                ("risk_band", models.CharField(blank=True, max_length=8, null=True)),
                ("imo_classifier", models.CharField(blank=True, max_length=16, null=True)),
                ("incident_type_id", models.IntegerField(blank=True, null=True)),
                ("loss_type_primary_id", models.IntegerField(blank=True, null=True)),
                ("investigation_depth", models.CharField(blank=True, max_length=8, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("position_source", models.CharField(blank=True, max_length=32, null=True)),
                ("position_daily_report_id", models.CharField(blank=True, max_length=64, null=True)),
                ("narrative", models.TextField(blank=True, null=True)),
                ("awaiting_daily_report_match", models.BooleanField(default=False)),
                ("first_hour_checklist_done", models.BooleanField(default=False)),
                ("slack_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_channel_count", models.IntegerField(default=0)),
                ("resources_allocated", models.TextField(blank=True, null=True)),
                ("pic_user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("dpa_notified_at", models.DateTimeField(blank=True, null=True)),
                ("fm_notified_at", models.DateTimeField(blank=True, null=True)),
                ("office_notified_at", models.DateTimeField(blank=True, null=True)),
                ("near_miss_priority", models.CharField(blank=True, max_length=8, null=True)),
                ("reporter_id", models.CharField(blank=True, max_length=64, null=True)),
                ("reporter_name", models.CharField(blank=True, max_length=128, null=True)),
                ("reporter_rank", models.CharField(blank=True, max_length=64, null=True)),
                ("reporter_email", models.CharField(blank=True, max_length=128, null=True)),
                ("reporter_department", models.CharField(blank=True, max_length=64, null=True)),
                ("reporter_device_fingerprint", models.CharField(blank=True, max_length=256, null=True)),
                ("chain_of_custody_ok", models.BooleanField(default=False)),
                ("marine_docs_checklist_done", models.BooleanField(default=False)),
                ("cargo_evidence_applicable", models.BooleanField(default=False)),
                ("health_fatigue_applicable", models.BooleanField(default=False)),
                ("causal_layering_complete", models.BooleanField(default=False)),
                ("alarp_attested", models.BooleanField(default=False)),
                ("bias_guard_attestations", models.CharField(default="", max_length=64)),
                ("blame_fixation_override_by", models.CharField(blank=True, max_length=64, null=True)),
                ("dpa_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("dpa_accepted_by", models.CharField(blank=True, max_length=64, null=True)),
                ("fm_approved_at", models.DateTimeField(blank=True, null=True)),
                ("fm_approved_by", models.CharField(blank=True, max_length=64, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_reason", models.TextField(blank=True, null=True)),
                ("linked_incident_id", models.BigIntegerField(blank=True, null=True)),
                ("superseded_by_id", models.BigIntegerField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_incident",
                "constraints": [
                    models.UniqueConstraint(fields=("incident_number",), name="uq_vims_safety_incident_number"),
                    models.CheckConstraint(
                        condition=Q(record_type__in=["INCIDENT", "NEAR_MISS"]),
                        name="ck_vims_safety_incident_record_type",
                    ),
                    models.CheckConstraint(
                        condition=Q(risk_band__isnull=True) | Q(risk_band__in=["GREEN", "YELLOW", "RED"]),
                        name="ck_vims_safety_incident_risk_band",
                    ),
                    models.CheckConstraint(
                        condition=Q(imo_classifier__isnull=True)
                        | Q(imo_classifier__in=["SMC", "MC", "MI", "NOT_APPLICABLE"]),
                        name="ck_vims_safety_incident_imo_classifier",
                    ),
                    models.CheckConstraint(condition=Q(phase__gte=0) & Q(phase__lte=8), name="ck_vims_safety_incident_phase"),
                ],
                "indexes": [
                    models.Index(
                        fields=("vessel_id", "occurred_at"),
                        name="ix_vims_safety_incident_vessel_date",
                        condition=Q(is_deleted=False),
                    ),
                    models.Index(fields=("state",), name="ix_vims_safety_incident_state", condition=Q(is_deleted=False)),
                    models.Index(fields=("record_type", "state"), name="ix_vims_safety_incident_record_type"),
                    models.Index(
                        fields=("risk_band",),
                        name="ix_vims_safety_incident_risk_band",
                        condition=Q(risk_band__isnull=False),
                    ),
                    models.Index(
                        fields=("linked_incident_id",),
                        name="ix_vims_safety_incident_linked",
                        condition=Q(linked_incident_id__isnull=False),
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyIncidentPhaseLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("phase_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("phase_to", models.PositiveSmallIntegerField()),
                ("transition_type", models.CharField(max_length=24)),
                ("loop_back_reason", models.TextField(blank=True, null=True)),
                ("actor_user_id", models.CharField(max_length=64)),
                ("actor_role_code", models.CharField(max_length=16)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=256, null=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_incident_phase_log",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(transition_type__in=["FORWARD", "LOOP_BACK", "REWORK", "REOPEN", "CLOSE"]),
                        name="ck_vims_safety_incident_phase_log_transition",
                    ),
                    models.CheckConstraint(
                        condition=~Q(transition_type="LOOP_BACK") | Q(loop_back_reason__isnull=False),
                        name="ck_vims_safety_incident_phase_log_loop_back_reason",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "occurred_at"), name="ix_vims_safety_incident_phase_log_incident"),
                    models.Index(fields=("actor_user_id", "occurred_at"), name="ix_vims_safety_incident_phase_log_actor"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyFieldHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("parent_table", models.CharField(max_length=64)),
                ("parent_id", models.BigIntegerField()),
                ("field_name", models.CharField(max_length=128)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("actor_user_id", models.CharField(max_length=64)),
                ("actor_role_code", models.CharField(max_length=16)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_field_history",
                "indexes": [
                    models.Index(
                        fields=("parent_table", "parent_id", "changed_at"),
                        name="ix_vims_safety_field_history_parent",
                    ),
                    models.Index(fields=("actor_user_id", "changed_at"), name="ix_vims_safety_field_history_actor"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyIncidentEvidence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("tab_code", models.CharField(max_length=16)),
                ("summary", models.TextField(blank=True, default="")),
                ("entry_count", models.PositiveIntegerField(default=0)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("status_chip", models.CharField(blank=True, default="", max_length=64)),
                ("na_justification", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_incident_evidence",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident_id", "tab_code"),
                        name="uq_vims_safety_incident_evidence_tab",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "tab_code"), name="ix_vims_safety_incident_evidence_tab"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyEvidenceItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("evidence_tab_id", models.BigIntegerField(blank=True, null=True)),
                ("item_type", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                ("source_label", models.CharField(blank=True, default="", max_length=128)),
                ("finding", models.CharField(blank=True, default="", max_length=256)),
                ("pro_evidence", models.TextField(blank=True, default="")),
                ("con_evidence", models.TextField(blank=True, default="")),
                ("comments", models.TextField(blank=True, default="")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_evidence_item",
                "indexes": [
                    models.Index(fields=("incident_id", "item_type"), name="ix_vims_safety_evidence_item_kind"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyFact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("sequence_index", models.PositiveIntegerField(default=1)),
                ("fact_text", models.TextField()),
                ("fact_timestamp", models.DateTimeField(blank=True, null=True)),
                ("source_evidence_id", models.PositiveBigIntegerField()),
                ("confidence", models.CharField(default="MEDIUM", max_length=16)),
                ("contradicts_fact_id", models.BigIntegerField(blank=True, null=True)),
                ("hindsight_guard_triggered", models.BooleanField(default=False)),
                ("hindsight_override_reason", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_fact",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident_id", "sequence_index"),
                        name="uq_vims_safety_fact_sequence",
                    ),
                    models.CheckConstraint(
                        condition=Q(confidence__in=["LOW", "MEDIUM", "HIGH"]),
                        name="ck_vims_safety_fact_confidence",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "sequence_index"), name="ix_vims_safety_fact_incident"),
                    models.Index(
                        fields=("contradicts_fact_id",),
                        name="ix_vims_safety_fact_contradiction",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyIncidentPhase5Assessment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField(unique=True)),
                ("people_contribution_text", models.TextField(blank=True, default="")),
                ("process_gap_text", models.TextField(blank=True, default="")),
                ("plant_failure_text", models.TextField(blank=True, default="")),
                ("analysis_tools_used", models.JSONField(blank=True, default=list)),
                ("human_factors_payload", models.JSONField(blank=True, default=dict)),
                ("confirmation_override_reason", models.TextField(blank=True, null=True)),
                ("monocausal_justification", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_incident_phase5_assessment",
                "indexes": [
                    models.Index(fields=("incident_id",), name="ix_vims_safety_phase5_assessment"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyCauseTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("source_fact_id", models.BigIntegerField()),
                ("mscat_subcode_id", models.CharField(max_length=16)),
                ("causal_layer", models.CharField(max_length=16)),
                ("analysis_tool", models.CharField(max_length=16)),
                ("rationale", models.TextField()),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_cause_tag",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(causal_layer__in=["IMMEDIATE", "INTERMEDIATE", "ROOT"]),
                        name="ck_vims_safety_cause_tag_layer",
                    ),
                    models.CheckConstraint(
                        condition=Q(analysis_tool__in=["STEP", "FACT_TREE", "ECF", "BARRIER", "CHANGE"]),
                        name="ck_vims_safety_cause_tag_tool",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "causal_layer"), name="ix_vims_safety_cause_tag_layer"),
                    models.Index(fields=("incident_id", "analysis_tool"), name="ix_vims_safety_cause_tag_tool"),
                    models.Index(fields=("mscat_subcode_id",), name="ix_vims_safety_cause_tag_subcode"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySafeguardFailure",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("safeguard_name", models.CharField(max_length=256)),
                ("design_mscat_subcode_id", models.CharField(max_length=16)),
                ("installation_mscat_subcode_id", models.CharField(max_length=16)),
                ("maintenance_mscat_subcode_id", models.CharField(max_length=16)),
                ("operation_mscat_subcode_id", models.CharField(max_length=16)),
                ("testing_mscat_subcode_id", models.CharField(max_length=16)),
                ("override_mscat_subcode_id", models.CharField(max_length=16)),
                ("notes", models.TextField(blank=True, default="")),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_safeguard_failure",
                "indexes": [
                    models.Index(fields=("incident_id",), name="ix_vims_safety_safeguard_incident"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyBiasGuardResponse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("guard_code", models.CharField(max_length=32)),
                ("acknowledged", models.BooleanField(default=False)),
                ("evaluation_state", models.CharField(default="UNCHECKED", max_length=24)),
                ("justification", models.TextField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=128, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_bias_guard_response",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident_id", "guard_code"),
                        name="uq_vims_safety_bias_guard_response",
                    ),
                    models.CheckConstraint(
                        condition=Q(
                            evaluation_state__in=[
                                "UNCHECKED",
                                "PASSED",
                                "WARNED",
                                "BLOCKED",
                                "OVERRIDE",
                                "JUSTIFIED",
                                "SOFTWARN_OVERRIDE",
                            ]
                        ),
                        name="ck_vims_safety_bias_guard_state",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "guard_code"), name="ix_vims_safety_bias_guard_response"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyBlameOverride",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField(unique=True)),
                ("justification", models.TextField()),
                ("approved_by", models.CharField(max_length=128)),
                ("approved_role", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField()),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_blame_override",
                "indexes": [
                    models.Index(fields=("incident_id",), name="ix_vims_safety_blame_override"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyChainOfCustody",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("evidence_item_id", models.BigIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("collection_timestamp", models.DateTimeField()),
                ("collector_name", models.CharField(max_length=128)),
                ("collector_signature", models.TextField()),
                ("storage_location", models.CharField(max_length=256)),
                ("witness_signature", models.TextField()),
                ("current_holder", models.CharField(max_length=128)),
                ("handover_log", models.JSONField(blank=True, default=list)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_chain_of_custody",
                "indexes": [
                    models.Index(fields=("incident_id", "collection_timestamp"), name="ix_vims_safety_coc_incident"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyWitnessInterview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("witness_name", models.CharField(max_length=128)),
                ("interview_type", models.CharField(max_length=16)),
                ("reason_formal_impossible", models.TextField(blank=True, null=True)),
                ("make_acquaintance_notes", models.TextField(blank=True, default="")),
                ("introduction_notes", models.TextField(blank=True, default="")),
                ("meeting_notes", models.TextField(blank=True, default="")),
                ("conclusion_notes", models.TextField(blank=True, default="")),
                ("question_rows", models.JSONField(blank=True, default=list)),
                ("read_back_confirmed", models.BooleanField(default=False)),
                ("witness_signature", models.TextField(blank=True, null=True)),
                ("copy_to_witness_recorded", models.BooleanField(default=False)),
                ("is_final", models.BooleanField(default=False)),
                ("phase_count", models.PositiveSmallIntegerField(default=0)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_witness_interview",
                "indexes": [
                    models.Index(fields=("incident_id", "interview_type"), name="ix_vims_safety_interview_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyEvidenceDeadlineTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("task_code", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=128)),
                ("due_at", models.DateTimeField()),
                ("due_within", models.DurationField(default=datetime.timedelta)),
                ("severity", models.CharField(max_length=16)),
                ("status", models.CharField(max_length=16)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_evidence_deadline_task",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident_id", "task_code"),
                        name="uq_vims_safety_deadline_task_code",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "due_at"), name="ix_vims_safety_deadline_due"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySoiInspection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vessel_id", models.CharField(max_length=64)),
                ("inspection_reference", models.CharField(max_length=32)),
                ("cycle_label", models.CharField(max_length=16)),
                ("state", models.CharField(max_length=24)),
                ("planned_date", models.DateField()),
                ("safety_officer_crew_id", models.CharField(max_length=64)),
                ("safety_officer_department", models.CharField(max_length=16)),
                ("assistant_crew_id", models.CharField(max_length=64)),
                ("assistant_department", models.CharField(max_length=16)),
                ("master_crew_id", models.CharField(blank=True, max_length=64, null=True)),
                ("checklist_unique_id", models.CharField(blank=True, max_length=32, null=True)),
                ("checklist_generated_at", models.DateTimeField(blank=True, null=True)),
                ("checklist_format", models.CharField(blank=True, max_length=8, null=True)),
                ("fieldwork_started_at", models.DateTimeField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("lost_paper_flag", models.BooleanField(default=False)),
                ("lost_paper_note", models.TextField(blank=True, null=True)),
                ("section_12_included", models.BooleanField(default=False)),
                ("schema_version", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_soi_inspection",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection_reference",),
                        name="uq_vims_safety_soi_inspection_reference",
                    ),
                    models.UniqueConstraint(
                        fields=("checklist_unique_id",),
                        name="uq_vims_safety_soi_checklist_unique_id",
                    ),
                    models.CheckConstraint(
                        condition=Q(state__in=["PLANNED", "DOWNLOADED", "IN_FIELDWORK", "REPORTED", "CLOSED"]),
                        name="ck_vims_safety_soi_inspection_state",
                    ),
                    models.CheckConstraint(
                        condition=Q(checklist_format__isnull=True) | Q(checklist_format__in=["PDF", "XLSX"]),
                        name="ck_vims_safety_soi_inspection_format",
                    ),
                    models.CheckConstraint(
                        condition=~Q(assistant_department=F("safety_officer_department")),
                        name="ck_vims_safety_soi_inspection_cross_functional",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("vessel_id", "state"), name="ix_vims_safety_soi_inspection_vessel_state"),
                    models.Index(fields=("vessel_id", "cycle_label"), name="ix_vims_safety_soi_inspection_cycle"),
                    models.Index(
                        fields=("checklist_unique_id",),
                        name="ix_vims_safety_soi_inspection_unique_id",
                        condition=Q(checklist_unique_id__isnull=False),
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySoiInspectionArea",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("inspection_id", models.BigIntegerField()),
                ("area_id", models.IntegerField()),
                ("inspected", models.BooleanField(default=False)),
                ("last_inspected_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_soi_inspection_area",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection_id", "area_id"),
                        name="uq_vims_safety_soi_inspection_area",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("inspection_id",), name="ix_vims_safety_soi_inspection_area_inspection"),
                    models.Index(fields=("area_id", "last_inspected_at"), name="ix_vims_safety_soi_inspection_area_area"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySoiFinding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("inspection_id", models.BigIntegerField()),
                ("area_id", models.IntegerField()),
                ("item_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("severity", models.CharField(max_length=8)),
                ("priority", models.CharField(max_length=8)),
                ("mscat_category_id", models.IntegerField(blank=True, null=True)),
                ("mscat_subcode_id", models.CharField(blank=True, max_length=16, null=True)),
                ("shell_tag", models.CharField(blank=True, max_length=16, null=True)),
                ("assigned_crew_id", models.CharField(blank=True, max_length=64, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("proposed_action", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=24)),
                ("carried_forward_count", models.IntegerField(default=0)),
                ("photo_attachment_path", models.CharField(blank=True, max_length=512, null=True)),
                ("master_approved_at", models.DateTimeField(blank=True, null=True)),
                ("master_approved_by", models.CharField(blank=True, max_length=64, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_note", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_soi_finding",
                "constraints": [
                    models.CheckConstraint(condition=Q(severity__in=["HIGH", "MED", "LOW"]), name="ck_vims_safety_soi_finding_severity"),
                    models.CheckConstraint(condition=Q(priority__in=["HIGH", "MED", "LOW"]), name="ck_vims_safety_soi_finding_priority"),
                    models.CheckConstraint(
                        condition=Q(
                            status__in=[
                                "OPEN",
                                "PENDING_CLOSURE",
                                "MASTER_APPROVED",
                                "CLOSED",
                                "CARRIED_FORWARD",
                            ]
                        ),
                        name="ck_vims_safety_soi_finding_status",
                    ),
                    models.CheckConstraint(
                        condition=~Q(severity="HIGH") | Q(photo_attachment_path__isnull=False),
                        name="ck_vims_safety_soi_finding_high_photo",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("inspection_id",), name="ix_vims_safety_soi_finding_inspection"),
                    models.Index(fields=("status",), name="ix_vims_safety_soi_finding_status", condition=Q(is_deleted=False)),
                    models.Index(fields=("assigned_crew_id", "due_date"), name="ix_vims_safety_soi_finding_assigned"),
                    models.Index(fields=("severity", "status"), name="ix_vims_safety_soi_finding_severity"),
                    models.Index(fields=("mscat_category_id", "mscat_subcode_id"), name="ix_vims_safety_soi_finding_mscat"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySoiVesselAreaMap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vessel_id", models.CharField(max_length=64)),
                ("area_id", models.IntegerField()),
                ("applicable", models.BooleanField(default=True)),
                ("last_inspected_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_soi_vessel_area_map",
                "constraints": [
                    models.UniqueConstraint(fields=("vessel_id", "area_id"), name="uq_vims_safety_soi_vessel_area"),
                ],
                "indexes": [
                    models.Index(
                        fields=("vessel_id", "due_at"),
                        name="ix_vims_safety_soi_vessel_area_map_due",
                        condition=Q(applicable=True),
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySoiApplicabilityLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vessel_id", models.CharField(max_length=64)),
                ("area_id", models.IntegerField()),
                ("old_applicable", models.BooleanField()),
                ("new_applicable", models.BooleanField()),
                ("reason", models.TextField()),
                ("master_requested_by", models.CharField(max_length=64)),
                ("master_requested_at", models.DateTimeField()),
                ("master_signature", models.CharField(max_length=256)),
                ("dpa_approved_by", models.CharField(blank=True, max_length=64, null=True)),
                ("dpa_approved_at", models.DateTimeField(blank=True, null=True)),
                ("dpa_signature", models.CharField(blank=True, max_length=256, null=True)),
                ("dpa_decision", models.CharField(blank=True, max_length=16, null=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_soi_applicability_log",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(dpa_decision__isnull=True) | Q(dpa_decision__in=["APPROVED", "REJECTED"]),
                        name="ck_vims_safety_soi_applicability_log_decision",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("vessel_id", "area_id", "master_requested_at"),
                        name="ix_vims_safety_soi_applicability_log_vessel_area",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetySoiTrainee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("inspection_id", models.BigIntegerField()),
                ("crew_id", models.CharField(max_length=64)),
                ("trainee_slot", models.PositiveSmallIntegerField()),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_soi_trainee",
                "constraints": [
                    models.UniqueConstraint(fields=("inspection_id", "crew_id"), name="uq_vims_safety_soi_trainee_crew"),
                    models.UniqueConstraint(fields=("inspection_id", "trainee_slot"), name="uq_vims_safety_soi_trainee_slot"),
                    models.CheckConstraint(condition=Q(trainee_slot__gte=1) & Q(trainee_slot__lte=3), name="ck_vims_safety_soi_trainee_slot"),
                ],
                "indexes": [
                    models.Index(fields=("crew_id",), name="ix_vims_safety_soi_trainee_crew"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyScmMeeting",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vessel_id", models.CharField(max_length=64)),
                ("scm_number", models.CharField(max_length=48)),
                ("meeting_type", models.CharField(max_length=16)),
                ("meeting_date", models.DateField()),
                ("meeting_time_local", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=128, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("voyage_no", models.CharField(blank=True, max_length=32, null=True)),
                ("chair_crew_id", models.CharField(max_length=64)),
                ("prepared_by_crew_id", models.CharField(max_length=64)),
                ("ad_hoc_trigger_reason", models.TextField(blank=True, null=True)),
                ("office_comment", models.TextField(blank=True, null=True)),
                ("office_comment_by", models.CharField(blank=True, max_length=64, null=True)),
                ("office_comment_at", models.DateTimeField(blank=True, null=True)),
                ("state", models.CharField(max_length=24)),
                ("master_signed_off_at", models.DateTimeField(blank=True, null=True)),
                ("master_signed_off_by", models.CharField(blank=True, max_length=64, null=True)),
                ("pdf_export_path", models.CharField(blank=True, max_length=512, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_scm_meeting",
                "constraints": [
                    models.UniqueConstraint(fields=("scm_number",), name="uq_vims_safety_scm_meeting_number"),
                    models.CheckConstraint(condition=Q(meeting_type__in=["REGULAR", "AD_HOC"]), name="ck_vims_safety_scm_meeting_type"),
                    models.CheckConstraint(
                        condition=Q(state__in=["DRAFT", "SUBMITTED", "SIGNED_OFF", "REOPENED"]),
                        name="ck_vims_safety_scm_meeting_state",
                    ),
                    models.CheckConstraint(
                        condition=~Q(meeting_type="AD_HOC") | Q(ad_hoc_trigger_reason__isnull=False),
                        name="ck_vims_safety_scm_meeting_adhoc_reason",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("vessel_id", "meeting_date"), name="ix_vims_safety_scm_meeting_vessel_date"),
                    models.Index(fields=("state",), name="ix_vims_safety_scm_meeting_state"),
                    models.Index(fields=("meeting_type", "meeting_date"), name="ix_vims_safety_scm_meeting_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyScmAttendance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meeting_id", models.BigIntegerField()),
                ("crew_id", models.CharField(max_length=64)),
                ("rank_name", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=128)),
                ("present", models.BooleanField(default=True)),
                ("absence_reason", models.TextField(blank=True, null=True)),
                ("wrh_data_available", models.BooleanField(default=True)),
                ("wrh_rest_hours_24h", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("wrh_rest_hours_7d", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("wrh_non_compliance_flag", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_scm_attendance",
                "constraints": [
                    models.UniqueConstraint(fields=("meeting_id", "crew_id"), name="uq_vims_safety_scm_attendance"),
                ],
                "indexes": [
                    models.Index(fields=("meeting_id",), name="ix_vims_safety_scm_attendance_meeting"),
                    models.Index(fields=("crew_id",), name="ix_vims_safety_scm_attendance_crew"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyScmAgenda",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meeting_id", models.BigIntegerField()),
                ("agenda_item_number", models.IntegerField()),
                ("section_label", models.CharField(max_length=128)),
                ("auto_populated", models.BooleanField(default=False)),
                ("content", models.TextField()),
                ("decision", models.TextField(blank=True, null=True)),
                ("linked_finding_ids", models.TextField(blank=True, null=True)),
                ("linked_incident_ids", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "vims_safety_scm_agenda",
                "constraints": [
                    models.UniqueConstraint(fields=("meeting_id", "agenda_item_number"), name="uq_vims_safety_scm_agenda_item"),
                ],
                "indexes": [
                    models.Index(fields=("meeting_id", "agenda_item_number"), name="ix_vims_safety_scm_agenda_meeting"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyRecommendation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.BigIntegerField()),
                ("tier", models.CharField(max_length=16)),
                ("theme_code", models.CharField(blank=True, max_length=32, null=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("rationale", models.TextField(blank=True, null=True)),
                ("estimated_effort", models.TextField(blank=True, null=True)),
                ("estimated_likelihood_reduction", models.CharField(blank=True, max_length=24, null=True)),
                ("residual_risk_statement", models.TextField(blank=True, null=True)),
                ("alarp_attested", models.BooleanField(default=False)),
                ("tolerable_failure_filter", models.BooleanField(default=False)),
                ("linked_ca_ids", models.TextField(blank=True, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_recommendation",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(tier__in=["CORRECTIVE", "PREVENTIVE", "LESSONS_LEARNT"]),
                        name="ck_vims_safety_recommendation_tier",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("incident_id", "tier"), name="ix_vims_safety_recommendation_incident"),
                    models.Index(fields=("theme_code",), name="ix_vims_safety_recommendation_theme", condition=Q(theme_code__isnull=False)),
                    models.Index(fields=("alarp_attested",), name="ix_vims_safety_recommendation_alarp"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VimsSafetyCorrectiveAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_table", models.CharField(max_length=64)),
                ("source_id", models.BigIntegerField()),
                ("recommendation_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("assigned_crew_id", models.CharField(blank=True, max_length=64, null=True)),
                ("assigned_office_user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("verifier_user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(max_length=24)),
                ("purchase_req_id", models.BigIntegerField(blank=True, null=True)),
                ("physical_verification_done", models.BooleanField(default=False)),
                ("physical_verification_at", models.DateTimeField(blank=True, null=True)),
                ("physical_verification_by", models.CharField(blank=True, max_length=64, null=True)),
                ("physical_verification_note", models.TextField(blank=True, null=True)),
                ("aging_bucket", models.CharField(blank=True, max_length=16, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=64, null=True)),
                ("schema_version", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vims_safety_corrective_action",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(status__in=["OPEN", "IN_PROGRESS", "PENDING_VERIFY", "CLOSED", "REOPENED"]),
                        name="ck_vims_safety_corrective_action_status",
                    ),
                ],
                "indexes": [
                    models.Index(fields=("source_table", "source_id"), name="ix_vims_safety_corrective_action_source"),
                    models.Index(fields=("status",), name="ix_vims_safety_corrective_action_status", condition=Q(is_deleted=False)),
                    models.Index(fields=("due_date", "status"), name="ix_vims_safety_corrective_action_due"),
                    models.Index(
                        fields=("purchase_req_id",),
                        name="ix_vims_safety_corrective_action_purchase",
                        condition=Q(purchase_req_id__isnull=False),
                    ),
                    models.Index(fields=("aging_bucket",), name="ix_vims_safety_corrective_action_aging"),
                ],
            },
        ),
    ]
