from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0015_enable_sql_server_fts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MasterImmediateCauses",
            new_name="MasterImmediateCause",
        ),
        migrations.RenameModel(
            old_name="MasterLossTypes",
            new_name="MasterLossType",
        ),
        migrations.RenameModel(
            old_name="MasterSoiChecklistVersion",
            new_name="SOIChecklistVersion",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyIncident",
            new_name="Incident",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyIncidentPhaseLog",
            new_name="IncidentPhaseLog",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyFieldHistory",
            new_name="SafetyFieldHistory",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyIncidentEvidence",
            new_name="IncidentEvidence",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyEvidenceItem",
            new_name="EvidenceItem",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyFact",
            new_name="IncidentFact",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyIncidentPhase5Assessment",
            new_name="IncidentPhase5Assessment",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyCauseTag",
            new_name="IncidentCauseTag",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySafeguardFailure",
            new_name="IncidentSafeguardFailure",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyBiasGuardResponse",
            new_name="IncidentBiasGuardResponse",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyBlameOverride",
            new_name="IncidentBlameOverride",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyChainOfCustody",
            new_name="ChainOfCustody",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyWitnessInterview",
            new_name="WitnessInterview",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyEvidenceDeadlineTask",
            new_name="EvidenceDeadlineTask",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySoiInspection",
            new_name="SOIInspection",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySoiInspectionArea",
            new_name="SOIInspectionArea",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySoiFinding",
            new_name="SOIFinding",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySoiVesselAreaMap",
            new_name="SOIVesselAreaMap",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySoiApplicabilityLog",
            new_name="SOIApplicabilityLog",
        ),
        migrations.RenameModel(
            old_name="VimsSafetySoiTrainee",
            new_name="SOITrainee",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyScmMeeting",
            new_name="SCMMeeting",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyScmAttendance",
            new_name="SCMAttendance",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyScmAgenda",
            new_name="SCMAgendaItem",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyRecommendation",
            new_name="Recommendation",
        ),
        migrations.RenameModel(
            old_name="VimsSafetyCorrectiveAction",
            new_name="CorrectiveAction",
        ),
    ]
