from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0016_rename_model_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="incidentevidence",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="incidentevidence",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="evidence_tabs",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="evidenceitem",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.RenameField(
                    model_name="evidenceitem",
                    old_name="evidence_tab_id",
                    new_name="evidence_tab",
                ),
                migrations.AlterField(
                    model_name="evidenceitem",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="safety.incident",
                    ),
                ),
                migrations.AlterField(
                    model_name="evidenceitem",
                    name="evidence_tab",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="items",
                        to="safety.incidentevidence",
                    ),
                ),
                migrations.RenameField(
                    model_name="chainofcustody",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="chainofcustody",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="chain_of_custody_rows",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="chainofcustody",
                    old_name="evidence_item_id",
                    new_name="evidence_item",
                ),
                migrations.AlterField(
                    model_name="chainofcustody",
                    name="evidence_item",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="custody_rows",
                        to="safety.evidenceitem",
                    ),
                ),
                migrations.RenameField(
                    model_name="witnessinterview",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="witnessinterview",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="witness_interviews",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="evidencedeadlinetask",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="evidencedeadlinetask",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="evidence_deadline_tasks",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentfact",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.RenameField(
                    model_name="incidentfact",
                    old_name="contradicts_fact_id",
                    new_name="contradicts_fact",
                ),
                migrations.AlterField(
                    model_name="incidentfact",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="facts",
                        to="safety.incident",
                    ),
                ),
                migrations.AlterField(
                    model_name="incidentfact",
                    name="contradicts_fact",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="contradicted_by",
                        to="safety.incidentfact",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentphase5assessment",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="incidentphase5assessment",
                    name="incident",
                    field=models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="phase5_assessment",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentcausetag",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.RenameField(
                    model_name="incidentcausetag",
                    old_name="source_fact_id",
                    new_name="source_fact",
                ),
                migrations.AlterField(
                    model_name="incidentcausetag",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="cause_tags",
                        to="safety.incident",
                    ),
                ),
                migrations.AlterField(
                    model_name="incidentcausetag",
                    name="source_fact",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="cause_tags",
                        to="safety.incidentfact",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentsafeguardfailure",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="incidentsafeguardfailure",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="safeguard_failures",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentbiasguardresponse",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="incidentbiasguardresponse",
                    name="incident",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="bias_guard_responses",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentblameoverride",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="incidentblameoverride",
                    name="incident",
                    field=models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="blame_override",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="incidentphaselog",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="incidentphaselog",
                    name="incident",
                    field=models.ForeignKey(
                        db_column="incident_id",
                        db_constraint=False,
                        on_delete=models.deletion.DO_NOTHING,
                        related_name="phase_logs",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="recommendation",
                    old_name="incident_id",
                    new_name="incident",
                ),
                migrations.AlterField(
                    model_name="recommendation",
                    name="incident",
                    field=models.ForeignKey(
                        db_column="incident_id",
                        on_delete=models.deletion.CASCADE,
                        related_name="recommendations",
                        to="safety.incident",
                    ),
                ),
                migrations.RenameField(
                    model_name="correctiveaction",
                    old_name="recommendation_id",
                    new_name="recommendation",
                ),
                migrations.AlterField(
                    model_name="correctiveaction",
                    name="recommendation",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="recommendation_id",
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="corrective_actions",
                        to="safety.recommendation",
                    ),
                ),
            ],
        ),
    ]
