# Generated by Django 5.2.7 on 2026-05-19 10:58

import datetime
import django.core.validators
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0024_soi_checklist_unique_id_filtered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('-created_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='incidentfact',
            options={'ordering': ('sequence_index', 'id')},
        ),
        migrations.AlterModelOptions(
            name='incidentphaselog',
            options={'ordering': ('occurred_at', 'id')},
        ),
        migrations.AlterModelOptions(
            name='masterimmediatecause',
            options={'managed': False, 'ordering': ('category_id', 'subcode_id')},
        ),
        migrations.AlterModelOptions(
            name='masterlosstype',
            options={'managed': False, 'ordering': ('loss_type_id',)},
        ),
        migrations.AlterModelOptions(
            name='mastermscattaxonomy',
            options={'managed': False, 'ordering': ('category_id', 'subcode_id')},
        ),
        migrations.AlterModelOptions(
            name='mastersafetybiasguard',
            options={'managed': False, 'ordering': ('bit_position', 'id')},
        ),
        migrations.AlterModelOptions(
            name='mastersafetyincidenttype',
            options={'managed': False, 'ordering': ('type_code',)},
        ),
        migrations.AlterModelOptions(
            name='mastersoiarea',
            options={'managed': False, 'ordering': ('display_order', 'area_id')},
        ),
        migrations.AlterModelOptions(
            name='mastersoiareaitem',
            options={'managed': False, 'ordering': ('area_id', 'subsection_id', 'item_number', 'id')},
        ),
        migrations.AlterModelOptions(
            name='safetycasestudy',
            options={'managed': False, 'ordering': ('display_order', 'title')},
        ),
        migrations.AlterModelOptions(
            name='safetyfieldhistory',
            options={'ordering': ('changed_at', 'id')},
        ),
        migrations.AlterModelOptions(
            name='scmagendaitem',
            options={'ordering': ('agenda_item_number', 'id')},
        ),
        migrations.AlterModelOptions(
            name='scmmeeting',
            options={'ordering': ('-meeting_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='soichecklistversion',
            options={'managed': False, 'ordering': ('-effective_from', '-id')},
        ),
        migrations.AlterModelOptions(
            name='soifinding',
            options={'ordering': ('-created_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='soiinspection',
            options={'ordering': ('-planned_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='soiinspectionarea',
            options={'ordering': ('inspection_id', 'area_id', 'id')},
        ),
        migrations.AlterModelOptions(
            name='soitrainee',
            options={'ordering': ('inspection_id', 'trainee_slot', 'id')},
        ),
        migrations.RemoveConstraint(
            model_name='correctiveaction',
            name='ck_vims_safety_corrective_action_status',
        ),
        migrations.RemoveConstraint(
            model_name='evidencedeadlinetask',
            name='uq_vims_safety_deadline_task_code',
        ),
        migrations.RemoveConstraint(
            model_name='incident',
            name='uq_vims_safety_incident_number',
        ),
        migrations.RemoveConstraint(
            model_name='incident',
            name='ck_vims_safety_incident_phase',
        ),
        migrations.RemoveConstraint(
            model_name='incidentbiasguardresponse',
            name='uq_vims_safety_bias_guard_response',
        ),
        migrations.RemoveConstraint(
            model_name='incidentbiasguardresponse',
            name='ck_vims_safety_bias_guard_state',
        ),
        migrations.RemoveConstraint(
            model_name='incidentcausetag',
            name='ck_vims_safety_cause_tag_layer',
        ),
        migrations.RemoveConstraint(
            model_name='incidentcausetag',
            name='ck_vims_safety_cause_tag_tool',
        ),
        migrations.RemoveConstraint(
            model_name='incidentevidence',
            name='uq_vims_safety_incident_evidence_tab',
        ),
        migrations.RemoveConstraint(
            model_name='incidentfact',
            name='uq_vims_safety_fact_sequence',
        ),
        migrations.RemoveConstraint(
            model_name='incidentfact',
            name='ck_vims_safety_fact_confidence',
        ),
        migrations.RemoveConstraint(
            model_name='recommendation',
            name='uq_vims_safety_recommendation_incident_tier_active',
        ),
        migrations.RemoveConstraint(
            model_name='scmmeeting',
            name='uq_vims_safety_scm_meeting_number',
        ),
        migrations.RemoveConstraint(
            model_name='soiinspection',
            name='uq_vims_safety_soi_inspection_reference',
        ),
        migrations.RemoveConstraint(
            model_name='soiinspection',
            name='ck_vims_safety_soi_inspection_cross_functional',
        ),
        migrations.RemoveIndex(
            model_name='chainofcustody',
            name='ix_vims_safety_coc_incident',
        ),
        migrations.RemoveIndex(
            model_name='evidencedeadlinetask',
            name='ix_vims_safety_deadline_due',
        ),
        migrations.RemoveIndex(
            model_name='evidenceitem',
            name='ix_vims_safety_evidence_item_kind',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='ix_vims_safety_incident_vessel_date',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='ix_vims_safety_incident_state',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='ix_vims_safety_incident_record_type',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='ix_vims_safety_incident_risk_band',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='ix_vims_safety_incident_linked',
        ),
        migrations.RemoveIndex(
            model_name='incidentbiasguardresponse',
            name='ix_vims_safety_bias_guard_response',
        ),
        migrations.RemoveIndex(
            model_name='incidentblameoverride',
            name='ix_vims_safety_blame_override',
        ),
        migrations.RemoveIndex(
            model_name='incidentcausetag',
            name='ix_vims_safety_cause_tag_layer',
        ),
        migrations.RemoveIndex(
            model_name='incidentcausetag',
            name='ix_vims_safety_cause_tag_tool',
        ),
        migrations.RemoveIndex(
            model_name='incidentevidence',
            name='ix_vims_safety_incident_evidence_tab',
        ),
        migrations.RemoveIndex(
            model_name='incidentfact',
            name='ix_vims_safety_fact_incident',
        ),
        migrations.RemoveIndex(
            model_name='incidentfact',
            name='ix_vims_safety_fact_contradiction',
        ),
        migrations.RemoveIndex(
            model_name='incidentphase5assessment',
            name='ix_vims_safety_phase5_assessment',
        ),
        migrations.RemoveIndex(
            model_name='incidentsafeguardfailure',
            name='ix_vims_safety_safeguard_incident',
        ),
        migrations.RemoveIndex(
            model_name='recommendation',
            name='ix_vims_safety_recommendation_incident',
        ),
        migrations.RemoveIndex(
            model_name='safetyfieldhistory',
            name='ix_vims_safety_field_history_parent',
        ),
        migrations.RemoveIndex(
            model_name='safetyfieldhistory',
            name='ix_vims_safety_field_history_actor',
        ),
        migrations.RemoveIndex(
            model_name='soifinding',
            name='ix_vims_safety_soi_finding_status',
        ),
        migrations.RemoveIndex(
            model_name='soiinspection',
            name='ix_vims_safety_soi_inspection_unique_id',
        ),
        migrations.RemoveIndex(
            model_name='soivesselareamap',
            name='ix_vims_safety_soi_vessel_area_map_due',
        ),
        migrations.RemoveIndex(
            model_name='witnessinterview',
            name='ix_vims_safety_interview_type',
        ),
        migrations.AlterField(
            model_name='incident',
            name='phase',
            field=models.PositiveSmallIntegerField(db_column='phase', default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='phase',
            new_name='current_phase',
        ),
        migrations.RenameIndex(
            model_name='correctiveaction',
            new_name='ix_safe_ca_source',
            old_name='ix_vims_safety_corrective_action_source',
        ),
        migrations.RenameIndex(
            model_name='correctiveaction',
            new_name='ix_safe_ca_status',
            old_name='ix_vims_safety_corrective_action_status',
        ),
        migrations.RenameIndex(
            model_name='correctiveaction',
            new_name='ix_safe_ca_due',
            old_name='ix_vims_safety_corrective_action_due',
        ),
        migrations.RenameIndex(
            model_name='correctiveaction',
            new_name='ix_safe_ca_purchase',
            old_name='ix_vims_safety_corrective_action_purchase',
        ),
        migrations.RenameIndex(
            model_name='correctiveaction',
            new_name='ix_safe_ca_aging',
            old_name='ix_vims_safety_corrective_action_aging',
        ),
        migrations.RenameIndex(
            model_name='incidentcausetag',
            new_name='ix_safe_cause_subcode',
            old_name='ix_vims_safety_cause_tag_subcode',
        ),
        migrations.RenameIndex(
            model_name='incidentphaselog',
            new_name='ix_safe_phase_inc',
            old_name='ix_vims_safety_incident_phase_log_incident',
        ),
        migrations.RenameIndex(
            model_name='incidentphaselog',
            new_name='ix_safe_phase_actor',
            old_name='ix_vims_safety_incident_phase_log_actor',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='ix_safe_rec_theme',
            old_name='ix_vims_safety_recommendation_theme',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='ix_safe_rec_alarp',
            old_name='ix_vims_safety_recommendation_alarp',
        ),
        migrations.RenameIndex(
            model_name='recommendationverification',
            new_name='ix_safe_recv_rec',
            old_name='ix_vims_safety_recommendation_verification_rec',
        ),
        migrations.RenameIndex(
            model_name='recommendationverification',
            new_name='ix_safe_recv_eff',
            old_name='ix_vims_safety_recommendation_verification_effective',
        ),
        migrations.RenameIndex(
            model_name='safetydashboardrollup',
            new_name='ix_safe_dash_scope',
            old_name='ix_vims_safety_dashboard_rollup_scope',
        ),
        migrations.RenameIndex(
            model_name='safetydashboardrollup',
            new_name='ix_safe_dash_period',
            old_name='ix_vims_safety_dashboard_rollup_period',
        ),
        migrations.RenameIndex(
            model_name='scmagendaitem',
            new_name='ix_safe_scma_meet',
            old_name='ix_vims_safety_scm_agenda_meeting',
        ),
        migrations.RenameIndex(
            model_name='scmattendance',
            new_name='ix_safe_scmt_meet',
            old_name='ix_vims_safety_scm_attendance_meeting',
        ),
        migrations.RenameIndex(
            model_name='scmattendance',
            new_name='ix_safe_scmt_crew',
            old_name='ix_vims_safety_scm_attendance_crew',
        ),
        migrations.RenameIndex(
            model_name='scmmeeting',
            new_name='ix_safe_scmm_vsl_dt',
            old_name='ix_vims_safety_scm_meeting_vessel_date',
        ),
        migrations.RenameIndex(
            model_name='scmmeeting',
            new_name='ix_safe_scmm_state',
            old_name='ix_vims_safety_scm_meeting_state',
        ),
        migrations.RenameIndex(
            model_name='scmmeeting',
            new_name='ix_safe_scmm_type',
            old_name='ix_vims_safety_scm_meeting_type',
        ),
        migrations.RenameIndex(
            model_name='soiapplicabilitylog',
            new_name='ix_safe_soial_vsl_area',
            old_name='ix_vims_safety_soi_applicability_log_vessel_area',
        ),
        migrations.RenameIndex(
            model_name='soifinding',
            new_name='ix_safe_soif_insp',
            old_name='ix_vims_safety_soi_finding_inspection',
        ),
        migrations.RenameIndex(
            model_name='soifinding',
            new_name='ix_safe_soif_assgn',
            old_name='ix_vims_safety_soi_finding_assigned',
        ),
        migrations.RenameIndex(
            model_name='soifinding',
            new_name='ix_safe_soif_sev',
            old_name='ix_vims_safety_soi_finding_severity',
        ),
        migrations.RenameIndex(
            model_name='soifinding',
            new_name='ix_safe_soif_mscat',
            old_name='ix_vims_safety_soi_finding_mscat',
        ),
        migrations.RenameIndex(
            model_name='soiinspection',
            new_name='ix_safe_soii_vsl_state',
            old_name='ix_vims_safety_soi_inspection_vessel_state',
        ),
        migrations.RenameIndex(
            model_name='soiinspection',
            new_name='ix_safe_soii_cycle',
            old_name='ix_vims_safety_soi_inspection_cycle',
        ),
        migrations.RenameIndex(
            model_name='soiinspectionarea',
            new_name='ix_safe_soia_insp',
            old_name='ix_vims_safety_soi_inspection_area_inspection',
        ),
        migrations.RenameIndex(
            model_name='soiinspectionarea',
            new_name='ix_safe_soia_area',
            old_name='ix_vims_safety_soi_inspection_area_area',
        ),
        migrations.RenameIndex(
            model_name='soitrainee',
            new_name='ix_safe_soit_crew',
            old_name='ix_vims_safety_soi_trainee_crew',
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFY', 'Pending Verify'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], max_length=24),
        ),
        migrations.AlterField(
            model_name='evidencedeadlinetask',
            name='due_within',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='evidencedeadlinetask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evidencedeadlinetask',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evidencedeadlinetask',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('ALERT', 'Alert'), ('HARD_ALARM', 'Hard Alarm')], default='INFO', max_length=16),
        ),
        migrations.AlterField(
            model_name='evidencedeadlinetask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='item_type',
            field=models.CharField(choices=[('MATRIX', 'Evidence Matrix'), ('PHYSICAL', 'Physical Evidence')], max_length=16),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_by',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='imo_classifier',
            field=models.CharField(blank=True, choices=[('SMC', 'Serious Marine Casualty'), ('MC', 'Marine Casualty'), ('MI', 'Marine Incident'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='investigation_depth',
            field=models.CharField(blank=True, choices=[('SHALLOW', 'Shallow'), ('MEDIUM', 'Medium'), ('DEEP', 'Deep')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='record_type',
            field=models.CharField(choices=[('INCIDENT', 'Incident'), ('NEAR_MISS', 'Near Miss')], default='INCIDENT', max_length=16),
        ),
        migrations.AlterField(
            model_name='incident',
            name='risk_band',
            field=models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='schema_version',
            field=models.PositiveIntegerField(db_default=2, default=2),
        ),
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('SENT_BACK', 'Sent Back'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('TRIAGED', 'Triaged'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=48),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_by',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vessel_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='incidentbiasguardresponse',
            name='evaluation_state',
            field=models.CharField(choices=[('UNCHECKED', 'Unchecked'), ('PASSED', 'Passed'), ('WARNED', 'Warned'), ('BLOCKED', 'Blocked'), ('OVERRIDE', 'Override'), ('JUSTIFIED', 'Justified'), ('SOFTWARN_OVERRIDE', 'Soft Warn Override')], default='UNCHECKED', max_length=24),
        ),
        migrations.AlterField(
            model_name='incidentbiasguardresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentbiasguardresponse',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentblameoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentblameoverride',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentcausetag',
            name='analysis_tool',
            field=models.CharField(choices=[('STEP', 'Step'), ('FACT_TREE', 'Fact Tree'), ('ECF', 'Ecf'), ('BARRIER', 'Barrier'), ('CHANGE', 'Change')], max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentcausetag',
            name='causal_layer',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('INTERMEDIATE', 'Intermediate'), ('ROOT', 'Root')], max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentcausetag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentcausetag',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentevidence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentevidence',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentevidence',
            name='tab_code',
            field=models.CharField(choices=[('POSITION', 'Position'), ('PEOPLE', 'People'), ('PARTS', 'Parts'), ('PAPER', 'Paper'), ('ELECTRONIC', 'Electronic')], max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='confidence',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentphase5assessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentphase5assessment',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentphaselog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentphaselog',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidentphaselog',
            name='transition_type',
            field=models.CharField(choices=[('FORWARD', 'Forward'), ('LOOP_BACK', 'Loop Back'), ('REWORK', 'Rework'), ('REOPEN', 'Reopen'), ('CLOSE', 'Close')], max_length=24),
        ),
        migrations.AlterField(
            model_name='incidentsafeguardfailure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentsafeguardfailure',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='estimated_likelihood_reduction',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('QUANTIFIED', 'Quantified')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='tier',
            field=models.CharField(choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('LESSONS_LEARNT', 'Lessons Learnt')], max_length=16),
        ),
        migrations.AlterField(
            model_name='safetyfieldhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='safetyfieldhistory',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scmagendaitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scmattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scmmeeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scmmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('AD_HOC', 'Ad-Hoc')], default='REGULAR', max_length=16),
        ),
        migrations.AlterField(
            model_name='scmmeeting',
            name='scm_number',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='scmmeeting',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SIGNED_OFF', 'Signed Off'), ('REOPENED', 'Reopened')], default='DRAFT', max_length=24),
        ),
        migrations.AlterField(
            model_name='soiapplicabilitylog',
            name='dpa_decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='soiapplicabilitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soiapplicabilitylog',
            name='master_requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soiapplicabilitylog',
            name='schema_version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='carried_forward_count',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='created_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='is_deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=8),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='schema_version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=8),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING_CLOSURE', 'Pending Closure'), ('MASTER_APPROVED', 'Master Approved'), ('CLOSED', 'Closed'), ('CARRIED_FORWARD', 'Carried Forward')], default='OPEN', max_length=24),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='checklist_format',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='inspection_reference',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='is_deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='lost_paper_flag',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='schema_version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='section_12_included',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='state',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('DOWNLOADED', 'Downloaded'), ('IN_FIELDWORK', 'In Fieldwork'), ('REPORTED', 'Reported'), ('CLOSED', 'Closed')], default='PLANNED', max_length=24),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='vessel_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='soiinspectionarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soiinspectionarea',
            name='inspected',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='soiinspectionarea',
            name='schema_version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='soitrainee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soitrainee',
            name='schema_version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='soivesselareamap',
            name='applicable',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='soivesselareamap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soivesselareamap',
            name='schema_version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='witnessinterview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='witnessinterview',
            name='interview_type',
            field=models.CharField(choices=[('FORMAL', 'Formal'), ('INFORMAL', 'Informal')], max_length=16),
        ),
        migrations.AlterField(
            model_name='witnessinterview',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='chainofcustody',
            index=models.Index(fields=['incident', 'collection_timestamp'], name='ix_vims_safety_coc_incident'),
        ),
        migrations.AddIndex(
            model_name='evidencedeadlinetask',
            index=models.Index(fields=['incident', 'due_at'], name='ix_vims_safety_deadline_due'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['incident', 'item_type'], name='ix_safe_evi_kind'),
        ),
        migrations.AddIndex(
            model_name='incidentbiasguardresponse',
            index=models.Index(fields=['incident', 'guard_code'], name='ix_safe_bias_resp'),
        ),
        migrations.AddIndex(
            model_name='incidentcausetag',
            index=models.Index(fields=['incident', 'causal_layer'], name='ix_vims_safety_cause_tag_layer'),
        ),
        migrations.AddIndex(
            model_name='incidentcausetag',
            index=models.Index(fields=['incident', 'analysis_tool'], name='ix_vims_safety_cause_tag_tool'),
        ),
        migrations.AddIndex(
            model_name='incidentevidence',
            index=models.Index(fields=['incident', 'tab_code'], name='ix_safe_inc_ev_tab'),
        ),
        migrations.AddIndex(
            model_name='incidentfact',
            index=models.Index(fields=['incident', 'sequence_index'], name='ix_vims_safety_fact_incident'),
        ),
        migrations.AddIndex(
            model_name='incidentfact',
            index=models.Index(fields=['contradicts_fact'], name='ix_safe_fact_contra'),
        ),
        migrations.AddIndex(
            model_name='incidentsafeguardfailure',
            index=models.Index(fields=['incident'], name='ix_safe_sg_inc'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['incident', 'tier'], name='ix_safe_rec_inc'),
        ),
        migrations.AddIndex(
            model_name='soifinding',
            index=models.Index(fields=['status'], name='ix_safe_soif_status'),
        ),
        migrations.AddIndex(
            model_name='soiinspection',
            index=models.Index(fields=['checklist_unique_id'], name='ix_safe_soii_uid'),
        ),
        migrations.AddIndex(
            model_name='soivesselareamap',
            index=models.Index(fields=['vessel_id', 'due_at'], name='ix_safe_soivam_due'),
        ),
        migrations.AddIndex(
            model_name='witnessinterview',
            index=models.Index(fields=['incident', 'interview_type'], name='ix_vims_safety_interview_type'),
        ),
        migrations.AddConstraint(
            model_name='evidencedeadlinetask',
            constraint=models.UniqueConstraint(fields=('incident', 'task_code'), name='uq_vims_safety_deadline_task_code'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schema_version__lt', 2), ('current_phase__gte', 0), ('current_phase__lte', 9)), models.Q(('schema_version__gte', 2), ('current_phase__gte', 1), ('current_phase__lte', 9)), _connector='OR'), name='ck_vims_safety_incident_phase'),
        ),
        migrations.AddConstraint(
            model_name='incidentbiasguardresponse',
            constraint=models.UniqueConstraint(fields=('incident', 'guard_code'), name='uq_vims_safety_bias_guard_response'),
        ),
        migrations.AddConstraint(
            model_name='incidentevidence',
            constraint=models.UniqueConstraint(fields=('incident', 'tab_code'), name='uq_vims_safety_incident_evidence_tab'),
        ),
        migrations.AddConstraint(
            model_name='incidentfact',
            constraint=models.UniqueConstraint(fields=('incident', 'sequence_index'), name='uq_vims_safety_fact_sequence'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('incident', 'tier'), name='uq_vims_safety_recommendation_incident_tier_active'),
        ),
        migrations.AddConstraint(
            model_name='soiinspection',
            constraint=models.CheckConstraint(condition=models.Q(('assistant_department', models.F('safety_officer_department')), _negated=True), name='ck_vims_safety_soi_inspection_xfunc'),
        ),
    ]
