# Generated by Django 5.2.12 on 2026-05-21 05:09

from django.db import migrations, models


TABLE_MODEL_NAMES = {
    "vims_safety_incident": "Incident",
    "vims_safety_incident_phase_log": "IncidentPhaseLog",
    "vims_safety_field_history": "SafetyFieldHistory",
    "vims_safety_fact": "IncidentFact",
    "vims_safety_incident_phase5_assessment": "IncidentPhase5Assessment",
    "vims_safety_cause_tag": "IncidentCauseTag",
    "vims_safety_safeguard_failure": "IncidentSafeguardFailure",
    "vims_safety_bias_guard_response": "IncidentBiasGuardResponse",
    "vims_safety_blame_override": "IncidentBlameOverride",
    "vims_safety_incident_evidence": "IncidentEvidence",
    "vims_safety_evidence_item": "EvidenceItem",
    "vims_safety_chain_of_custody": "ChainOfCustody",
    "vims_safety_witness_interview": "WitnessInterview",
    "vims_safety_evidence_deadline_task": "EvidenceDeadlineTask",
    "vims_safety_external_party_injury": "ExternalPartyInjury",
    "vims_safety_recommendation": "Recommendation",
    "vims_safety_corrective_action": "CorrectiveAction",
    "vims_safety_recommendation_verification": "RecommendationVerification",
    "vims_safety_scm_meeting": "SCMMeeting",
    "vims_safety_scm_attendance": "SCMAttendance",
    "vims_safety_scm_signature": "SCMSignature",
    "vims_safety_scm_agenda": "SCMAgendaItem",
    "vims_safety_scm_legacy_field": "SCMLegacyField",
    "vims_safety_soi_inspection": "SOIInspection",
    "vims_safety_soi_finding": "SOIFinding",
    "vims_safety_soi_inspection_area": "SOIInspectionArea",
    "vims_safety_soi_trainee": "SOITrainee",
}


def _split_legacy_id_list(value):
    if value in (None, ""):
        return []
    items = []
    for part in str(value).split(","):
        part = part.strip()
        if not part:
            continue
        try:
            items.append(int(part))
        except (TypeError, ValueError):
            continue
    return items


def _resolve_uuid_list(model, legacy_ids):
    ids = list(dict.fromkeys(legacy_ids))
    if not ids:
        return None
    rows = model.objects.filter(pk__in=ids).values_list("pk", "public_id")
    mapping = {int(pk): str(public_id) for pk, public_id in rows}
    values = [mapping[item] for item in ids if item in mapping]
    return ",".join(values) if values else None


def _backfill_direct_reference(apps, *, model_name, uuid_field, target_model_name, legacy_field):
    model = apps.get_model("safety", model_name)
    target_model = apps.get_model("safety", target_model_name)
    for row in (
        model.objects.filter(**{f"{uuid_field}__isnull": True})
        .exclude(**{f"{legacy_field}__isnull": True})
        .values("pk", legacy_field)
        .iterator(chunk_size=500)
    ):
        public_id = target_model.objects.filter(pk=row[legacy_field]).values_list("public_id", flat=True).first()
        if public_id is not None:
            model.objects.filter(pk=row["pk"]).update(**{uuid_field: public_id})


def _backfill_source_evidence_uuid(apps):
    fact_model = apps.get_model("safety", "IncidentFact")
    source_models = [
        apps.get_model("safety", "EvidenceItem"),
        apps.get_model("safety", "WitnessInterview"),
        apps.get_model("safety", "ChainOfCustody"),
        apps.get_model("safety", "IncidentEvidence"),
    ]
    for row in (
        fact_model.objects.filter(source_evidence_uuid__isnull=True)
        .exclude(source_evidence_id__isnull=True)
        .values("pk", "incident_id", "source_evidence_id")
        .iterator(chunk_size=500)
    ):
        public_id = None
        for source_model in source_models:
            queryset = source_model.objects.filter(pk=row["source_evidence_id"])
            if row.get("incident_id") is not None and any(field.name == "incident" for field in source_model._meta.fields):
                queryset = queryset.filter(incident_id=row["incident_id"])
            public_id = queryset.values_list("public_id", flat=True).first()
            if public_id is not None:
                break
        if public_id is not None:
            fact_model.objects.filter(pk=row["pk"]).update(source_evidence_uuid=public_id)


def _backfill_polymorphic_references(apps):
    history_model = apps.get_model("safety", "SafetyFieldHistory")
    action_model = apps.get_model("safety", "CorrectiveAction")

    for row in (
        history_model.objects.filter(parent_uuid__isnull=True)
        .values("pk", "parent_table", "parent_id")
        .iterator(chunk_size=500)
    ):
        model_name = TABLE_MODEL_NAMES.get(str(row["parent_table"] or "").strip())
        if not model_name:
            continue
        target_model = apps.get_model("safety", model_name)
        public_id = target_model.objects.filter(pk=row["parent_id"]).values_list("public_id", flat=True).first()
        if public_id is not None:
            history_model.objects.filter(pk=row["pk"]).update(parent_uuid=public_id)

    for row in (
        action_model.objects.filter(source_uuid__isnull=True)
        .values("pk", "source_table", "source_id")
        .iterator(chunk_size=500)
    ):
        model_name = TABLE_MODEL_NAMES.get(str(row["source_table"] or "").strip())
        if not model_name:
            continue
        target_model = apps.get_model("safety", model_name)
        public_id = target_model.objects.filter(pk=row["source_id"]).values_list("public_id", flat=True).first()
        if public_id is not None:
            action_model.objects.filter(pk=row["pk"]).update(source_uuid=public_id)


def _backfill_agenda_link_uuid_lists(apps):
    agenda_model = apps.get_model("safety", "SCMAgendaItem")
    finding_model = apps.get_model("safety", "SOIFinding")
    incident_model = apps.get_model("safety", "Incident")
    for row in agenda_model.objects.all().values("pk", "linked_finding_ids", "linked_incident_ids").iterator(chunk_size=500):
        update_fields = {}
        finding_uuids = _resolve_uuid_list(finding_model, _split_legacy_id_list(row["linked_finding_ids"]))
        incident_uuids = _resolve_uuid_list(incident_model, _split_legacy_id_list(row["linked_incident_ids"]))
        if finding_uuids:
            update_fields["linked_finding_uuids"] = finding_uuids
        if incident_uuids:
            update_fields["linked_incident_uuids"] = incident_uuids
        if update_fields:
            agenda_model.objects.filter(pk=row["pk"]).update(**update_fields)


def backfill_uuid_references(apps, schema_editor):
    direct_specs = (
        ("Incident", "linked_incident_uuid", "Incident", "linked_incident_id"),
        ("Incident", "superseded_by_uuid", "Incident", "superseded_by_id"),
        ("IncidentPhaseLog", "incident_uuid", "Incident", "incident_id"),
        ("IncidentEvidence", "incident_uuid", "Incident", "incident_id"),
        ("EvidenceItem", "incident_uuid", "Incident", "incident_id"),
        ("EvidenceItem", "evidence_tab_uuid", "IncidentEvidence", "evidence_tab_id"),
        ("ChainOfCustody", "incident_uuid", "Incident", "incident_id"),
        ("ChainOfCustody", "evidence_item_uuid", "EvidenceItem", "evidence_item_id"),
        ("WitnessInterview", "incident_uuid", "Incident", "incident_id"),
        ("EvidenceDeadlineTask", "incident_uuid", "Incident", "incident_id"),
        ("ExternalPartyInjury", "incident_uuid", "Incident", "incident_id"),
        ("IncidentFact", "incident_uuid", "Incident", "incident_id"),
        ("IncidentFact", "contradicts_fact_uuid", "IncidentFact", "contradicts_fact_id"),
        ("IncidentPhase5Assessment", "incident_uuid", "Incident", "incident_id"),
        ("IncidentCauseTag", "incident_uuid", "Incident", "incident_id"),
        ("IncidentCauseTag", "source_fact_uuid", "IncidentFact", "source_fact_id"),
        ("IncidentSafeguardFailure", "incident_uuid", "Incident", "incident_id"),
        ("IncidentBiasGuardResponse", "incident_uuid", "Incident", "incident_id"),
        ("IncidentBlameOverride", "incident_uuid", "Incident", "incident_id"),
        ("Recommendation", "incident_uuid", "Incident", "incident_id"),
        ("CorrectiveAction", "recommendation_uuid", "Recommendation", "recommendation_id"),
        ("RecommendationVerification", "recommendation_uuid", "Recommendation", "recommendation_id"),
        ("SCMAttendance", "meeting_uuid", "SCMMeeting", "meeting_id"),
        ("SCMSignature", "meeting_uuid", "SCMMeeting", "meeting_id"),
        ("SCMAgendaItem", "meeting_uuid", "SCMMeeting", "meeting_id"),
        ("SCMLegacyField", "meeting_uuid", "SCMMeeting", "meeting_id"),
        ("SOIFinding", "inspection_uuid", "SOIInspection", "inspection_id"),
        ("SOIInspectionArea", "inspection_uuid", "SOIInspection", "inspection_id"),
        ("SOITrainee", "inspection_uuid", "SOIInspection", "inspection_id"),
    )
    for model_name, uuid_field, target_model_name, legacy_field in direct_specs:
        _backfill_direct_reference(
            apps,
            model_name=model_name,
            uuid_field=uuid_field,
            target_model_name=target_model_name,
            legacy_field=legacy_field,
        )
    _backfill_source_evidence_uuid(apps)
    _backfill_polymorphic_references(apps)
    _backfill_agenda_link_uuid_lists(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0030_uuid_master_reference_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='evidence_item_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='recommendation_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='source_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencedeadlinetask',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='evidence_tab_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='externalpartyinjury',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='linked_incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='superseded_by_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentbiasguardresponse',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentblameoverride',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentcausetag',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentcausetag',
            name='source_fact_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentevidence',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='contradicts_fact_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='source_evidence_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentphase5assessment',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentphaselog',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentsafeguardfailure',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationverification',
            name='recommendation_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyfieldhistory',
            name='parent_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scmagendaitem',
            name='linked_finding_uuids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scmagendaitem',
            name='linked_incident_uuids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scmagendaitem',
            name='meeting_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scmattendance',
            name='meeting_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scmlegacyfield',
            name='meeting_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scmsignature',
            name='meeting_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='soifinding',
            name='inspection_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='soiinspectionarea',
            name='inspection_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='soitrainee',
            name='inspection_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='witnessinterview',
            name='incident_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_uuid_references, migrations.RunPython.noop),
    ]
