# Generated by Django 5.2.12 on 2026-05-21 05:30

import uuid
from django.db import migrations, models



RESET_MODEL_NAMES = (
    "RecommendationVerification",
    "CorrectiveAction",
    "Recommendation",
    "IncidentBiasGuardResponse",
    "IncidentBlameOverride",
    "IncidentCauseTag",
    "IncidentSafeguardFailure",
    "IncidentPhase5Assessment",
    "IncidentFact",
    "EvidenceDeadlineTask",
    "ChainOfCustody",
    "EvidenceItem",
    "IncidentEvidence",
    "WitnessInterview",
    "ExternalPartyInjury",
    "IncidentPhaseLog",
    "SafetyFieldHistory",
    "Incident",
    "SCMSignature",
    "SCMLegacyField",
    "SCMAgendaItem",
    "SCMAttendance",
    "SCMMeeting",
    "SOIApplicabilityLog",
    "SOIOfficerSetting",
    "SOITrainee",
    "SOIInspectionArea",
    "SOIVesselAreaMap",
    "SOIFinding",
    "SOIInspection",
    "SafetyDashboardRollup",
    "SafetyCaseStudy",
    "SOIChecklistVersion",
    "MasterSoiAreaItem",
    "MasterSoiArea",
    "MasterSafetyBiasGuard",
    "MasterSafetyIncidentType",
    "MasterLossType",
    "MasterImmediateCause",
    "MasterMscatTaxonomy",
)

CREATE_MODEL_NAMES = tuple(reversed(RESET_MODEL_NAMES))


def rebuild_safety_uuid_schema(apps, schema_editor):
    # Final UUID identity cleanup is intentionally destructive, but scoped to
    # Safety-owned managed tables only. External VIMS/shared tables are not touched.
    from apps.safety import models as live_models

    for model_name in RESET_MODEL_NAMES:
        model = getattr(live_models, model_name)
        try:
            schema_editor.delete_model(model)
        except Exception:
            # Tables may be absent in fresh/dev databases. Creation below is the
            # authoritative final shape for this reset migration.
            pass

    for model_name in CREATE_MODEL_NAMES:
        model = getattr(live_models, model_name)
        schema_editor.create_model(model)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0031_uuid_reference_readiness'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rebuild_safety_uuid_schema, noop_reverse),
            ],
            state_operations=[
        migrations.RemoveField(
            model_name='chainofcustody',
            name='evidence_item_uuid',
        ),
        migrations.RemoveField(
            model_name='chainofcustody',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='chainofcustody',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='recommendation_uuid',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='source_uuid',
        ),
        migrations.RemoveField(
            model_name='evidencedeadlinetask',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='evidencedeadlinetask',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='evidenceitem',
            name='evidence_tab_uuid',
        ),
        migrations.RemoveField(
            model_name='evidenceitem',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='evidenceitem',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='externalpartyinjury',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='externalpartyinjury',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='linked_incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='superseded_by_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentbiasguardresponse',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentbiasguardresponse',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentblameoverride',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentblameoverride',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentcausetag',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentcausetag',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentcausetag',
            name='source_fact_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentevidence',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentevidence',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='contradicts_fact_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='source_evidence_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentphase5assessment',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentphase5assessment',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentphaselog',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentphaselog',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='incidentsafeguardfailure',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='incidentsafeguardfailure',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='recommendationverification',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='recommendationverification',
            name='recommendation_uuid',
        ),
        migrations.RemoveField(
            model_name='safetydashboardrollup',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='safetyfieldhistory',
            name='parent_uuid',
        ),
        migrations.RemoveField(
            model_name='safetyfieldhistory',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='scmagendaitem',
            name='linked_finding_uuids',
        ),
        migrations.RemoveField(
            model_name='scmagendaitem',
            name='linked_incident_uuids',
        ),
        migrations.RemoveField(
            model_name='scmagendaitem',
            name='meeting_uuid',
        ),
        migrations.RemoveField(
            model_name='scmagendaitem',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='scmattendance',
            name='meeting_uuid',
        ),
        migrations.RemoveField(
            model_name='scmattendance',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='scmlegacyfield',
            name='meeting_uuid',
        ),
        migrations.RemoveField(
            model_name='scmlegacyfield',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='scmmeeting',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='scmsignature',
            name='meeting_uuid',
        ),
        migrations.RemoveField(
            model_name='scmsignature',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soiapplicabilitylog',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soifinding',
            name='inspection_uuid',
        ),
        migrations.RemoveField(
            model_name='soifinding',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soiinspection',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soiinspectionarea',
            name='inspection_uuid',
        ),
        migrations.RemoveField(
            model_name='soiinspectionarea',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soiofficersetting',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soitrainee',
            name='inspection_uuid',
        ),
        migrations.RemoveField(
            model_name='soitrainee',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='soivesselareamap',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='witnessinterview',
            name='incident_uuid',
        ),
        migrations.RemoveField(
            model_name='witnessinterview',
            name='public_id',
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='source_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='evidencedeadlinetask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='externalpartyinjury',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='linked_incident_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='superseded_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentbiasguardresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentblameoverride',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentcausetag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentevidence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='source_evidence_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='incidentphase5assessment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentphaselog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentsafeguardfailure',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendationverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetydashboardrollup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetyfieldhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetyfieldhistory',
            name='parent_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='scmagendaitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scmagendaitem',
            name='meeting_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='scmattendance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scmattendance',
            name='meeting_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='scmlegacyfield',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scmlegacyfield',
            name='meeting_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='scmmeeting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scmsignature',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scmsignature',
            name='meeting_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='soiapplicabilitylog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='inspection_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='soifinding',
            name='item_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiinspection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soiinspectionarea',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soiinspectionarea',
            name='inspection_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='soiofficersetting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soitrainee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soitrainee',
            name='inspection_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='soivesselareamap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='witnessinterview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
            ],
        ),
    ]

