# Generated by Django 5.2.12 on 2026-05-27 06:02

import django.core.validators
import uuid
from django.db import migrations, models


def seed_near_miss_guidance(apps, schema_editor):
    NearMissGuidancePrompt = apps.get_model("safety", "NearMissGuidancePrompt")
    prompts = [
        (None, "What almost happened, and what stopped it from becoming an accident?"),
        (None, "Where exactly did it happen, and what task was being done?"),
        (None, "What immediate action did the crew take to make the situation safe?"),
        ("Safety", "What unsafe act or unsafe condition was noticed?"),
        ("Security", "What security control was weak, missing, or bypassed?"),
        ("Environment", "Was there any pollution, spill, emission, or waste-handling risk?"),
        ("MLC", "Was the issue connected to crew welfare, living condition, rest, or working condition?"),
        ("Training", "Was lack of training, familiarisation, or supervision a possible reason?"),
        ("Operational", "Which operation or procedure needs better control?"),
        ("Management", "Was the issue linked to planning, communication, resources, or follow-up?"),
        ("Others", "Describe the risk clearly if it does not fit another category."),
    ]
    for display_order, (category_tag, prompt_text) in enumerate(prompts, start=1):
        NearMissGuidancePrompt.objects.get_or_create(
            category_tag=category_tag,
            incident_type_id=None,
            prompt_text=prompt_text,
            defaults={"display_order": display_order, "active": True, "created_by": "migration"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0032_uuid_id_final_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='near_miss_corrective_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_equipment_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_lessons_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_root_cause_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_weather_voyage_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NearMissGuidancePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_tag', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('incident_type_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('prompt_text', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vims_safety_near_miss_guidance_prompt',
                'ordering': ('display_order', 'category_tag', 'incident_type_id'),
                'indexes': [models.Index(fields=['active', 'category_tag'], name='ix_nm_guidance_category'), models.Index(fields=['active', 'incident_type_id'], name='ix_nm_guidance_type')],
            },
        ),
        migrations.CreateModel(
            name='NearMissKpiTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_id', models.CharField(db_index=True, max_length=64)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_count', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vims_safety_near_miss_kpi_target',
                'ordering': ('vessel_id', 'year', 'month'),
                'indexes': [models.Index(fields=['vessel_id', 'year', 'month'], name='ix_nm_kpi_target_period')],
                'constraints': [models.UniqueConstraint(fields=('vessel_id', 'year', 'month'), name='uq_vims_safety_nm_kpi_target_period')],
            },
        ),
        migrations.RunPython(seed_near_miss_guidance, migrations.RunPython.noop),
    ]
