# Generated by Django 5.2.12 on 2026-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0033_incident_near_miss_corrective_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='near_miss_category_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_incident_type_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_mscat_subcode_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='near_miss_place',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('near_miss_place__isnull', True), ('near_miss_place__in', ('AT_ANCHOR', 'AT_SEA', 'AT_PORT')), _connector='OR'), name='ck_vims_safety_incident_nm_place'),
        ),
    ]
