# Generated by Django 5.2.10 on 2026-02-06 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0002_car_deficiency_deficiencyactionhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField()),
                ('vessel_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=500)),
                ('performed_by', models.CharField(max_length=100)),
                ('performed_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'psc_activity_history',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='psc_activit_entity__734102_idx'), models.Index(fields=['vessel_id'], name='psc_activit_vessel__d40563_idx'), models.Index(fields=['-performed_at'], name='psc_activit_perform_63e5d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('performed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('is_office_edit_assist', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'psc_audit_log',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='psc_audit_l_entity__2ae1e0_idx'), models.Index(fields=['-performed_at'], name='psc_audit_l_perform_de4e13_idx'), models.Index(fields=['performed_by'], name='psc_audit_l_perform_f389e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarClcMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clc_item_id', models.UUIDField(db_index=True)),
                ('custom_cause_text', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clc_mappings', to='inspection.car')),
            ],
            options={
                'db_table': 'psc_car_clc_mapping',
                'indexes': [models.Index(fields=['car'], name='psc_car_clc_car_id_9e931d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('LONG_TERM', 'Long Term')], max_length=20)),
                ('description', models.TextField()),
                ('owner_crew_id', models.UUIDField(blank=True, null=True)),
                ('owner_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_remarks', models.TextField(blank=True, null=True)),
                ('sequence_no', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='inspection.car')),
            ],
            options={
                'db_table': 'psc_corrective_action',
                'ordering': ['sequence_no', 'created_date'],
                'indexes': [models.Index(fields=['car'], name='psc_correct_car_id_cc3115_idx'), models.Index(fields=['owner_crew_id'], name='psc_correct_owner_c_05b162_idx'), models.Index(fields=['is_completed'], name='psc_correct_is_comp_0949fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After'), ('EVIDENCE', 'Evidence'), ('OTHER', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='inspection.car')),
            ],
            options={
                'db_table': 'psc_evidence',
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['car'], name='psc_evidenc_car_id_32638f_idx'), models.Index(fields=['evidence_type'], name='psc_evidenc_evidenc_9fab1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhysicalVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_port', models.CharField(blank=True, max_length=200, null=True)),
                ('verifier_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('verifier_crew_id', models.UUIDField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_verifications', to='inspection.car')),
            ],
            options={
                'db_table': 'psc_physical_verification',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['car'], name='psc_physica_car_id_b78328_idx'), models.Index(fields=['status'], name='psc_physica_status_7c9e8c_idx')],
            },
        ),
    ]
