# Generated by Django 5.2.10 on 2026-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carclcmapping',
            name='clc_item_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
