# Generated by Django 5.2.10 on 2026-02-05 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_id', models.UUIDField(db_index=True)),
                ('inspection_type', models.CharField(choices=[('PSC', 'Port State Control'), ('RS', 'RightShip'), ('AUDIT', 'Audit'), ('INTERNAL', 'Internal')], db_index=True, max_length=20)),
                ('psc_subtype', models.CharField(blank=True, choices=[('INITIAL', 'Initial'), ('EXPANDED', 'Expanded'), ('CIC', 'Concentrated Inspection Campaign'), ('FOLLOW_UP', 'Follow-up')], max_length=20, null=True)),
                ('inspection_date', models.DateField(db_index=True)),
                ('port_place', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('mou_id', models.CharField(blank=True, max_length=20, null=True)),
                ('authority', models.CharField(blank=True, max_length=200, null=True)),
                ('inspector_name', models.CharField(blank=True, max_length=200, null=True)),
                ('report_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_detention', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PIC_REVIEWED', 'PIC Reviewed'), ('DPA_CLOSED', 'DPA Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('revision_no', models.IntegerField(default=1)),
                ('pic_comment', models.TextField(blank=True, null=True)),
                ('pic_reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dpa_comment', models.TextField(blank=True, null=True)),
                ('dpa_closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dpa_closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=1)),
                ('parent_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='inspection.inspection')),
            ],
            options={
                'db_table': 'psc_inspection',
                'ordering': ['-inspection_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inspection.inspection')),
            ],
            options={
                'db_table': 'psc_inspection_report',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['vessel_id'], name='psc_inspect_vessel__f350e1_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='psc_inspect_status_ca2ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-inspection_date'], name='psc_inspect_inspect_38d5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_type'], name='psc_inspect_inspect_50a065_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['inspection'], name='psc_inspect_inspect_97061f_idx'),
        ),
    ]
