# Generated by Django 5.2.10 on 2026-02-05 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PIC_ACCEPTED', 'PIC Accepted'), ('REWORK_REQUESTED', 'Rework Requested'), ('DPA_CLOSED', 'DPA Closed')], db_index=True, default='DRAFT', max_length=30)),
                ('root_cause_summary', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('pic_comment', models.TextField(blank=True, null=True)),
                ('pic_accepted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rework_reason', models.TextField(blank=True, null=True)),
                ('rework_requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rework_requested_at', models.DateTimeField(blank=True, null=True)),
                ('rework_count', models.IntegerField(default=0)),
                ('dpa_comment', models.TextField(blank=True, null=True)),
                ('dpa_closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dpa_closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'psc_car',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['car_number'], name='psc_car_car_num_256380_idx'), models.Index(fields=['status'], name='psc_car_status_672ba5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('def_code_id', models.CharField(db_index=True, max_length=5)),
                ('def_code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('action_code_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action_code', models.CharField(blank=True, max_length=10, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_cleared', models.BooleanField(db_index=True, default=False)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('sequence_no', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=1)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deficiency', to='inspection.car')),
                ('cleared_by_follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_deficiencies', to='inspection.inspection')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficiencies', to='inspection.inspection')),
            ],
            options={
                'db_table': 'psc_deficiency',
                'ordering': ['sequence_no', 'created_date'],
            },
        ),
        migrations.CreateModel(
            name='DeficiencyActionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_action_code_id', models.IntegerField(blank=True, null=True)),
                ('previous_action_code', models.CharField(blank=True, max_length=10, null=True)),
                ('new_action_code_id', models.IntegerField()),
                ('new_action_code', models.CharField(max_length=10)),
                ('change_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('deficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to='inspection.deficiency')),
                ('follow_up_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_code_changes', to='inspection.inspection')),
            ],
            options={
                'db_table': 'psc_deficiency_action_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deficiency',
            index=models.Index(fields=['inspection'], name='psc_deficie_inspect_b0f12d_idx'),
        ),
        migrations.AddIndex(
            model_name='deficiency',
            index=models.Index(fields=['def_code'], name='psc_deficie_def_cod_92ddf3_idx'),
        ),
        migrations.AddIndex(
            model_name='deficiency',
            index=models.Index(fields=['is_cleared'], name='psc_deficie_is_clea_467a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='deficiencyactionhistory',
            index=models.Index(fields=['deficiency'], name='psc_deficie_deficie_339c2a_idx'),
        ),
    ]
