# Generated by Django 5.2.7 on 2026-02-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_car_deficiency_deficiencyactionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deficiency',
            name='assigned_crew_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='deficiency',
            index=models.Index(fields=['assigned_crew_id'], name='psc_deficie_assigne_bf98ea_idx'),
        ),
    ]
