# Generated by Django 5.2.10 on 2026-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_add_assigned_crew_id_to_deficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deficiency',
            name='def_status',
            field=models.CharField(choices=[('ALLOCATED', 'Allocated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted')], db_index=True, default='ALLOCATED', max_length=20),
        ),
        migrations.AddField(
            model_name='deficiency',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deficiency',
            name='owner_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deficiency',
            name='reviewer_crew_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deficiency',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deficiency',
            name='reviewer_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
