# Generated by Django 5.2.10 on 2026-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_workflow_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='report_type',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('FOLLOW_UP', 'Follow-up')], default='ORIGINAL', max_length=20),
        ),
    ]
