# Generated by Django 5.2.10 on 2026-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_add_report_type_to_inspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='def_reported',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
    ]
