# Generated by Django 5.2.10 on 2026-02-11 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_car_initial_action_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('inserted_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'psc_opensource_import_run',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenSourceDeficiencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('def_code_norm', models.CharField(db_index=True, max_length=5)),
                ('action_code_norm', models.IntegerField(db_index=True)),
                ('port_norm', models.CharField(db_index=True, max_length=200)),
                ('mou_norm', models.CharField(db_index=True, max_length=20)),
                ('country_norm', models.CharField(blank=True, max_length=100, null=True)),
                ('description_raw', models.TextField(blank=True, null=True)),
                ('dedup_key_hash', models.CharField(max_length=64, unique=True)),
                ('import_run', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='records', to='inspection.opensourceimportrun')),
            ],
            options={
                'db_table': 'psc_opensource_deficiency_record',
                'indexes': [
                    models.Index(fields=['year', 'def_code_norm'], name='psc_openso_year_878e3d_idx'),
                    models.Index(fields=['port_norm', 'mou_norm'], name='psc_openso_port_no_9dd0a4_idx'),
                ],
            },
        ),
    ]
