# Generated by Django 5.2.7 on 2026-02-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_opensource_import_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opensourcedeficiencyrecord',
            new_name='psc_opensou_year_ebb002_idx',
            old_name='psc_openso_year_878e3d_idx',
        ),
        migrations.RenameIndex(
            model_name='opensourcedeficiencyrecord',
            new_name='psc_opensou_port_no_b0480f_idx',
            old_name='psc_openso_port_no_9dd0a4_idx',
        ),
    ]
