# Generated by Django 5.2.7 on 2026-02-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_rename_psc_openso_year_878e3d_idx_psc_opensou_year_ebb002_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficiency',
            name='assigned_crew_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
