# Generated by Django 5.2.7 on 2026-02-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('inspection', '0011_alter_deficiency_assigned_crew_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deficiency',
            new_name='psc_deficie_assigne_90d61e_idx',
            old_name='psc_deficie_assigne_bf98ea_idx',
        ),
        migrations.AlterField(
            model_name='deficiency',
            name='assigned_crew_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.masterappliedrank'),
        ),
    ]
