# Generated by Django 5.2.7 on 2026-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_rename_psc_deficie_assigne_bf98ea_idx_psc_deficie_assigne_90d61e_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deficiency',
            new_name='psc_deficie_assigne_bf98ea_idx',
            old_name='psc_deficie_assigne_90d61e_idx',
        ),
        migrations.AlterField(
            model_name='deficiency',
            name='assigned_crew_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
