# Generated by Django 5.2.7 on 2026-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0015_rename_psc_deficie_assigne_90d61e_idx_psc_deficie_assigne_bf98ea_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficiency',
            name='reviewer_crew_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
