# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0016_alter_deficiency_reviewer_crew_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionreport",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
