"""
Tests for sync feature backfill.

PRD Reference: Docs/PRD.md Section 2.6 (FEAT-SYNC-002, FEAT-SYNC-003, FEAT-SYNC-004)
Validation Reference: Docs/VALIDATION_RULES.md Section 9
API/RBAC Reference: Docs/BACKEND_STRUCTURE.md Section 10.9 and Section 11.1

Generated by: Test Backfill Agent
Date: 2026-02-07
"""

import json
import uuid
from datetime import date, timedelta
from types import SimpleNamespace
from unittest.mock import patch

from django.test import TestCase
from django.core import signing
from django.utils import timezone
from rest_framework import status
from rest_framework.test import APIRequestFactory, force_authenticate

from apps.accounts.models import RoleCodes
from apps.car.models import ActionType, ActivityHistory, AuditLog, CorrectiveAction, Evidence
from apps.inspection.deficiency_models import CAR, CARStatus, Deficiency
from apps.inspection.models import Inspection, InspectionStatus
from apps.sync.models import (
    ConflictStatus,
    SyncConflict,
    SyncDetailStatus,
    SyncLog,
    SyncLogDetail,
    SyncToken,
)
from apps.sync import sync_service
from apps.sync.views import (
    SyncAttachmentUploadView,
    SyncConflictListView,
    SyncPullView,
    SyncPushView,
    SyncResolveConflictView,
)


def make_user(
    *,
    role: str,
    user_type: str,
    vessel_id: str | None = None,
    user_id: str = "test-user",
    display_name: str = "Test User",
    employee_id: str | None = None,
):
    return SimpleNamespace(
        id=user_id,
        role=role,
        user_type=user_type,
        vessel_id=vessel_id,
        employee_id=employee_id or user_id,
        display_name=display_name,
        username=display_name.lower().replace(" ", "_"),
        is_authenticated=True,
    )


class BaseSyncAPITestCase(TestCase):
    """Shared fixtures/helpers for sync endpoint tests."""

    def setUp(self):
        self.factory = APIRequestFactory()
        self.vessel_id = uuid.uuid4()
        self.other_vessel_id = uuid.uuid4()

        self.vessel_master = make_user(
            role=RoleCodes.VESSEL_MASTER,
            user_type="VESSEL",
            vessel_id=str(self.vessel_id),
            user_id="vm-1",
            employee_id="vm-emp-1",
            display_name="Vessel Master",
        )
        self.vessel_crew = make_user(
            role=RoleCodes.VESSEL_CREW,
            user_type="VESSEL",
            vessel_id=str(self.vessel_id),
            user_id="vc-1",
            employee_id="vc-emp-1",
            display_name="Vessel Crew",
        )
        self.other_vessel_master = make_user(
            role=RoleCodes.VESSEL_MASTER,
            user_type="VESSEL",
            vessel_id=str(self.other_vessel_id),
            user_id="vm-2",
            employee_id="vm-emp-2",
            display_name="Other Vessel Master",
        )
        self.office_pic = make_user(
            role=RoleCodes.OFFICE_PIC,
            user_type="OFFICE",
            vessel_id=None,
            user_id="office-1",
            employee_id="office-emp-1",
            display_name="Office PIC",
        )
        self.dpa = make_user(
            role=RoleCodes.DPA,
            user_type="OFFICE",
            vessel_id=None,
            user_id="dpa-1",
            employee_id="dpa-emp-1",
            display_name="DPA",
        )

    def create_inspection(self, **overrides):
        payload = {
            "vessel_id": self.vessel_id,
            "inspection_type": "RS",
            "inspection_date": date.today(),
            "port_place": "Singapore",
            "status": InspectionStatus.DRAFT,
            "created_by": self.vessel_master.employee_id,
            "sync_version": 1,
        }
        payload.update(overrides)
        return Inspection.objects.create(**payload)

    def create_car_with_deficiency(self, inspection=None, **deficiency_overrides):
        inspection = inspection or self.create_inspection()
        car = CAR.objects.create(
            car_number=CAR.generate_car_number(),
            status=CARStatus.DRAFT,
            target_date=date.today() + timedelta(days=7),
            created_by=self.vessel_master.employee_id,
            sync_version=1,
        )
        deficiency_payload = {
            "inspection": inspection,
            "def_code_id": "10101",
            "def_code": "10101",
            "description": "Deficiency for sync backfill tests.",
            "action_code_id": 30,
            "action_code": "30",
            "car": car,
            "created_by": self.vessel_master.employee_id,
            "sync_version": 1,
        }
        deficiency_payload.update(deficiency_overrides)
        deficiency = Deficiency.objects.create(**deficiency_payload)
        return car, deficiency

    def build_create_inspection_event(self, *, client_id=None, event_id=None):
        client_id = client_id or str(uuid.uuid4())
        return {
            "event_id": event_id or str(uuid.uuid4()),
            "entity_type": "INSPECTION",
            "entity_id": str(uuid.uuid4()),
            "client_id": client_id,
            "operation": "CREATE",
            "client_version": 1,
            "data": {
                "inspection_type": "RS",
                "inspection_date": str(date.today()),
                "port_place": "Busan",
                "status": "DRAFT",
            },
            "timestamp": timezone.now().isoformat(),
        }

    def build_update_inspection_event(
        self,
        *,
        entity_id,
        client_id=None,
        client_version=1,
        port_place="Updated Port",
        event_id=None,
        timestamp=None,
    ):
        return {
            "event_id": event_id or str(uuid.uuid4()),
            "entity_type": "INSPECTION",
            "entity_id": str(entity_id),
            "client_id": client_id,
            "operation": "UPDATE",
            "client_version": client_version,
            "data": {"port_place": port_place},
            "timestamp": (timestamp or timezone.now()).isoformat(),
        }


class TestFEAT_SYNC_002_SyncPull(BaseSyncAPITestCase):
    """FEAT-SYNC-002: Sync Pull (Server -> Vessel)."""

    def test_feat_sync_002_happy_path_returns_delta_data_buckets(self):
        """PRD FEAT-SYNC-002: pull returns inspection/deficiency/CAR/action/evidence/activity updates."""
        inspection = self.create_inspection(sync_version=5)
        car, _ = self.create_car_with_deficiency(inspection=inspection, sync_version=4)
        CorrectiveAction.objects.create(
            car=car,
            action_type=ActionType.IMMEDIATE,
            description="Immediate corrective action",
            created_by=self.vessel_master.employee_id,
            sync_version=3,
        )
        Evidence.objects.create(
            car=car,
            evidence_type="BEFORE",
            file_name="before.jpg",
            file_path="/tmp/before.jpg",
            file_size=1024,
            mime_type="image/jpeg",
            description="Before evidence",
            uploaded_by=self.vessel_master.employee_id,
        )
        ActivityHistory.objects.create(
            entity_type="INSPECTION",
            entity_id=inspection.id,
            vessel_id=self.vessel_id,
            event_type="INSPECTION_CREATED",
            event_description="Inspection created for sync pull test",
            performed_by=self.vessel_master.employee_id,
        )

        view = SyncPullView.as_view()
        payload = {
            "vessel_id": str(self.vessel_id),
            "last_sync_token": str(uuid.uuid4()),
            "last_server_version": 0,
        }
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("data", response.data)
        self.assertIn("sync_token", response.data)
        self.assertIn("server_version", response.data)
        self.assertGreaterEqual(len(response.data["data"]["inspections"]), 1)
        self.assertGreaterEqual(len(response.data["data"]["deficiencies"]), 1)
        self.assertGreaterEqual(len(response.data["data"]["cars"]), 1)
        self.assertGreaterEqual(len(response.data["data"]["corrective_actions"]), 1)
        self.assertGreaterEqual(len(response.data["data"]["evidence_metadata"]), 1)
        self.assertGreaterEqual(len(response.data["data"]["activity_history"]), 1)

    def test_feat_sync_002_happy_path_activity_history_present_and_no_audit_logs(self):
        """PRD FEAT-SYNC-002: pull includes activity events and excludes audit logs."""
        inspection = self.create_inspection()
        ActivityHistory.objects.create(
            entity_type="INSPECTION",
            entity_id=inspection.id,
            vessel_id=self.vessel_id,
            event_type="INSPECTION_SUBMITTED",
            event_description="Submitted for review",
            performed_by=self.vessel_master.employee_id,
        )

        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("activity_history", response.data["data"])
        self.assertNotIn("audit_log", response.data["data"])

    def test_feat_sync_002_happy_path_includes_soft_deleted_records(self):
        """PRD FEAT-SYNC-002: deleted records are included for client-side reconciliation."""
        deleted_inspection = self.create_inspection(is_deleted=True, sync_version=9)

        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        records = {item["id"]: item for item in response.data["data"]["inspections"]}
        self.assertIn(str(deleted_inspection.id), records)
        self.assertTrue(records[str(deleted_inspection.id)]["is_deleted"])

    def test_feat_sync_002_rbac_office_user_cannot_pull(self):
        """RBAC BACKEND_STRUCTURE 10.9/11.1: pull endpoint is vessel-role only."""
        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.office_pic)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_sync_002_rbac_vessel_mismatch_returns_403(self):
        """VALIDATION_RULES 9.1: vessel_id must match authenticated vessel user."""
        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.other_vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(response.data["message"], "Vessel ID does not match your assigned vessel.")

    def test_feat_sync_002_rbac_unauthenticated_pull_rejected(self):
        """RBAC BACKEND_STRUCTURE 11.1: unauthenticated pull requests are rejected."""
        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        response = view(request)

        self.assertIn(response.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))

    def test_feat_sync_002_happy_path_updates_sync_token(self):
        """PRD FEAT-SYNC-002: pull returns sync token and updates server sync checkpoint."""
        self.create_inspection(sync_version=2)

        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_crew)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        token = SyncToken.objects.get(vessel_id=self.vessel_id)
        self.assertEqual(token.last_server_version, response.data["server_version"])
        self.assertIsNotNone(token.last_sync_id)

    def test_feat_sync_002_gap_pull_should_include_master_data_updates(self):
        """GAP PRD FEAT-SYNC-002: pull payload should include master data updates."""
        self.create_inspection(sync_version=2)

        view = SyncPullView.as_view()
        payload = {"vessel_id": str(self.vessel_id), "last_server_version": 0}
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("masters", response.data["data"])


class TestFEAT_SYNC_003_SyncPush(BaseSyncAPITestCase):
    """FEAT-SYNC-003: Sync Push (Vessel -> Server)."""

    def test_feat_sync_003_happy_path_processes_events_in_order(self):
        """PRD FEAT-SYNC-003: queued events are processed in order."""
        client_id = str(uuid.uuid4())
        create_event = self.build_create_inspection_event(client_id=client_id)
        update_event = self.build_update_inspection_event(
            entity_id=uuid.uuid4(),
            client_id=client_id,
            client_version=1,
            port_place="Updated After Create",
        )

        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "a" * 64,
            "events": [create_event, update_event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["processed"], 2)
        self.assertEqual(response.data["data"]["failed"], 0)
        self.assertEqual(response.data["data"]["conflicts"], [])
        self.assertIn(client_id, response.data["data"]["id_mappings"])

        inspection = Inspection.objects.get(client_id=uuid.UUID(client_id))
        self.assertEqual(inspection.port_place, "Updated After Create")

    def test_feat_sync_003_happy_path_returns_attachment_upload_urls(self):
        """PRD FEAT-SYNC-003: push returns upload URLs for queued attachments."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "b" * 64,
            "events": [],
            "attachments": [
                {
                    "client_id": str(uuid.uuid4()),
                    "car_id": str(uuid.uuid4()),
                    "evidence_type": "BEFORE",
                    "file_name": "evidence-before.jpg",
                    "file_size": 1024,
                }
            ],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_crew)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        urls = response.data["data"]["attachment_upload_urls"]
        self.assertEqual(len(urls), 1)
        self.assertIn("/api/psc/sync/upload/", urls[0]["upload_url"])

    def test_feat_sync_003_gap_upload_endpoint_accepts_tokenized_url(self):
        """BACKEND_STRUCTURE 10.9: /sync/upload/{token}/ endpoint exists for attachment payload."""
        client_id = str(uuid.uuid4())
        token = signing.dumps(
            {"sync_id": str(uuid.uuid4()), "client_id": client_id},
            salt=sync_service.UPLOAD_TOKEN_SALT,
        )
        view = SyncAttachmentUploadView.as_view()
        request = self.factory.put(
            f"/api/psc/sync/upload/{token}/",
            b"binary-payload",
            content_type="image/jpeg",
        )

        response = view(request, token=token)

        # Route resolves and token is accepted; missing evidence maps to 404.
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_feat_sync_003_validation_upload_endpoint_rejects_invalid_token(self):
        """Invalid upload token should be rejected (400) instead of writing payload."""
        view = SyncAttachmentUploadView.as_view()
        request = self.factory.put(
            "/api/psc/sync/upload/not-a-valid-token/",
            b"binary-payload",
            content_type="image/jpeg",
        )

        response = view(request, token="not-a-valid-token")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_happy_path_duplicate_sync_id_returns_cached_result(self):
        """VALIDATION_RULES 9.1 idempotency key: duplicate sync_id should not re-process events."""
        sync_id = str(uuid.uuid4())
        payload = {
            "sync_id": sync_id,
            "vessel_id": str(self.vessel_id),
            "checksum": "c" * 64,
            "events": [self.build_create_inspection_event()],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        first_request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(first_request, user=self.vessel_master)
        first_response = view(first_request)

        second_request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(second_request, user=self.vessel_master)
        second_response = view(second_request)

        self.assertEqual(first_response.status_code, status.HTTP_200_OK)
        self.assertEqual(second_response.status_code, status.HTTP_200_OK)
        self.assertEqual(SyncLog.objects.filter(sync_id=sync_id).count(), 1)
        self.assertEqual(second_response.data["data"]["processed"], first_response.data["data"]["processed"])

    def test_feat_sync_003_happy_path_partial_failures_reported(self):
        """PRD FEAT-SYNC-003: partial failures are reported without aborting whole batch."""
        valid_event = self.build_create_inspection_event()
        failing_event = self.build_update_inspection_event(
            entity_id=uuid.uuid4(),
            client_id=None,
            client_version=1,
        )
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "d" * 64,
            "events": [valid_event, failing_event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["processed"], 1)
        self.assertEqual(response.data["data"]["failed"], 1)

    def test_feat_sync_003_rbac_office_user_cannot_push(self):
        """RBAC BACKEND_STRUCTURE 10.9/11.1: push endpoint is vessel-role only."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "e" * 64,
            "events": [],
            "attachments": [],
        }
        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.office_pic)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_sync_003_rbac_vessel_mismatch_returns_403(self):
        """VALIDATION_RULES 9.1: push vessel_id must match authenticated vessel."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "f" * 64,
            "events": [],
            "attachments": [],
        }
        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.other_vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(response.data["message"], "Vessel ID does not match your assigned vessel.")

    def test_feat_sync_003_rbac_unauthenticated_push_rejected(self):
        """RBAC BACKEND_STRUCTURE 11.1: unauthenticated push requests are rejected."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "1" * 64,
            "events": [],
            "attachments": [],
        }
        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        response = view(request)

        self.assertIn(response.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))

    def test_feat_sync_003_validation_invalid_entity_type_rejected(self):
        """VALIDATION_RULES 9.1: entity_type must be a valid enum value."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "2" * 64,
            "events": [
                {
                    "event_id": str(uuid.uuid4()),
                    "entity_type": "INVALID_ENTITY",
                    "entity_id": str(uuid.uuid4()),
                    "client_id": str(uuid.uuid4()),
                    "operation": "CREATE",
                    "client_version": 1,
                    "data": {},
                    "timestamp": timezone.now().isoformat(),
                }
            ],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_validation_invalid_operation_rejected(self):
        """VALIDATION_RULES 9.1: operation must be CREATE, UPDATE, or DELETE."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "3" * 64,
            "events": [
                {
                    "event_id": str(uuid.uuid4()),
                    "entity_type": "INSPECTION",
                    "entity_id": str(uuid.uuid4()),
                    "client_id": str(uuid.uuid4()),
                    "operation": "UPSERT",
                    "client_version": 1,
                    "data": {},
                    "timestamp": timezone.now().isoformat(),
                }
            ],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_gap_client_version_must_be_gte_one(self):
        """GAP VALIDATION_RULES 9.1: client_version should reject values below 1."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "4" * 64,
            "events": [
                {
                    "event_id": str(uuid.uuid4()),
                    "entity_type": "INSPECTION",
                    "entity_id": str(uuid.uuid4()),
                    "client_id": str(uuid.uuid4()),
                    "operation": "UPDATE",
                    "client_version": 0,
                    "data": {},
                    "timestamp": timezone.now().isoformat(),
                }
            ],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_gap_future_event_timestamp_should_be_rejected(self):
        """GAP VALIDATION_RULES 9.1: future event timestamp should be rejected."""
        future_ts = timezone.now() + timedelta(days=1)
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "5" * 64,
            "events": [
                {
                    "event_id": str(uuid.uuid4()),
                    "entity_type": "INSPECTION",
                    "entity_id": str(uuid.uuid4()),
                    "client_id": str(uuid.uuid4()),
                    "operation": "UPDATE",
                    "client_version": 1,
                    "data": {},
                    "timestamp": future_ts.isoformat(),
                }
            ],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_gap_event_count_should_be_capped_at_100(self):
        """GAP VALIDATION_RULES 9.1: push should reject payloads larger than 100 events."""
        events = []
        for _ in range(101):
            events.append(
                {
                    "event_id": str(uuid.uuid4()),
                    "entity_type": "INSPECTION",
                    "entity_id": str(uuid.uuid4()),
                    "client_id": str(uuid.uuid4()),
                    "operation": "UPDATE",
                    "client_version": 1,
                    "data": {},
                    "timestamp": timezone.now().isoformat(),
                }
            )

        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "6" * 64,
            "events": events,
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_gap_duplicate_event_ids_should_be_rejected(self):
        """GAP VALIDATION_RULES 9.1: duplicate event_id values in one sync should be rejected."""
        duplicate_event_id = str(uuid.uuid4())
        events = [
            {
                "event_id": duplicate_event_id,
                "entity_type": "INSPECTION",
                "entity_id": str(uuid.uuid4()),
                "client_id": str(uuid.uuid4()),
                "operation": "UPDATE",
                "client_version": 1,
                "data": {},
                "timestamp": timezone.now().isoformat(),
            },
            {
                "event_id": duplicate_event_id,
                "entity_type": "INSPECTION",
                "entity_id": str(uuid.uuid4()),
                "client_id": str(uuid.uuid4()),
                "operation": "UPDATE",
                "client_version": 1,
                "data": {},
                "timestamp": timezone.now().isoformat(),
            },
        ]

        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "7" * 64,
            "events": events,
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_feat_sync_003_gap_checksum_should_be_verified(self):
        """GAP VALIDATION_RULES 9.1: checksum should be validated against payload integrity."""
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "0" * 64,
            "events": [],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)


class TestFEAT_SYNC_004_ConflictDetection(BaseSyncAPITestCase):
    """FEAT-SYNC-004: Conflict Detection."""

    def test_feat_sync_004_happy_path_stale_client_version_creates_conflict(self):
        """PRD FEAT-SYNC-004: stale client_version should queue conflict for resolution."""
        inspection = self.create_inspection(sync_version=5, port_place="Singapore")
        event = self.build_update_inspection_event(
            entity_id=inspection.id,
            client_version=1,
            port_place="Rotterdam",
        )
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "8" * 64,
            "events": [event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        with patch("apps.sync.conflict_resolver.notify_conflict_detected"):
            request = self.factory.post("/api/psc/sync/push/", payload, format="json")
            force_authenticate(request, user=self.vessel_master)
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["processed"], 1)
        self.assertEqual(response.data["data"]["failed"], 0)
        self.assertEqual(len(response.data["data"]["conflicts"]), 1)

        conflict = SyncConflict.objects.get(id=response.data["data"]["conflicts"][0])
        self.assertEqual(conflict.status, ConflictStatus.PENDING)
        self.assertEqual(conflict.entity_type, "INSPECTION")
        self.assertEqual(conflict.entity_id, inspection.id)

    def test_feat_sync_004_happy_path_conflicting_fields_are_identified(self):
        """PRD FEAT-SYNC-004: conflict record should include conflicting fields list."""
        inspection = self.create_inspection(sync_version=4, port_place="Old Port")
        event = self.build_update_inspection_event(
            entity_id=inspection.id,
            client_version=1,
            port_place="New Port",
        )
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "9" * 64,
            "events": [event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        with patch("apps.sync.conflict_resolver.notify_conflict_detected"):
            request = self.factory.post("/api/psc/sync/push/", payload, format="json")
            force_authenticate(request, user=self.vessel_master)
            response = view(request)

        conflict = SyncConflict.objects.get(id=response.data["data"]["conflicts"][0])
        fields = json.loads(conflict.conflicting_fields)
        self.assertIn("port_place", fields)

    def test_feat_sync_004_happy_path_conflict_notifies_vessel_master(self):
        """PRD FEAT-SYNC-004: vessel master is notified when conflict is detected."""
        inspection = self.create_inspection(sync_version=3)
        event = self.build_update_inspection_event(
            entity_id=inspection.id,
            client_version=1,
            port_place="Conflict Port",
        )
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "a" * 64,
            "events": [event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        with patch("apps.sync.conflict_resolver.notify_conflict_detected") as mock_notify:
            request = self.factory.post("/api/psc/sync/push/", payload, format="json")
            force_authenticate(request, user=self.vessel_master)
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        mock_notify.assert_called_once_with(str(self.vessel_id), "INSPECTION", str(inspection.id))

    def test_feat_sync_004_happy_path_equal_versions_apply_update_without_conflict(self):
        """PRD FEAT-SYNC-004: no conflict when client_version equals server sync_version."""
        inspection = self.create_inspection(sync_version=2, port_place="Initial Port")
        event = self.build_update_inspection_event(
            entity_id=inspection.id,
            client_version=2,
            port_place="Updated Without Conflict",
        )
        payload = {
            "sync_id": str(uuid.uuid4()),
            "vessel_id": str(self.vessel_id),
            "checksum": "b" * 64,
            "events": [event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        request = self.factory.post("/api/psc/sync/push/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["conflicts"], [])
        inspection.refresh_from_db()
        self.assertEqual(inspection.port_place, "Updated Without Conflict")
        self.assertEqual(inspection.sync_version, 3)

    def test_feat_sync_004_happy_path_conflict_sync_log_detail_marked_conflict(self):
        """PRD FEAT-SYNC-004: queued conflict should be tracked in sync detail log."""
        inspection = self.create_inspection(sync_version=6)
        event = self.build_update_inspection_event(
            entity_id=inspection.id,
            client_version=1,
            port_place="Trigger Conflict",
        )
        sync_id = str(uuid.uuid4())
        payload = {
            "sync_id": sync_id,
            "vessel_id": str(self.vessel_id),
            "checksum": "c" * 64,
            "events": [event],
            "attachments": [],
        }

        view = SyncPushView.as_view()
        with patch("apps.sync.conflict_resolver.notify_conflict_detected"):
            request = self.factory.post("/api/psc/sync/push/", payload, format="json")
            force_authenticate(request, user=self.vessel_master)
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        detail = SyncLogDetail.objects.get(sync_log__sync_id=sync_id)
        self.assertEqual(detail.sync_status, SyncDetailStatus.CONFLICT)

    def test_feat_sync_004_happy_path_conflict_list_vessel_scope(self):
        """PRD FEAT-SYNC-004: vessel users should only see own vessel conflicts."""
        own_conflict = SyncConflict.objects.create(
            vessel_id=self.vessel_id,
            entity_type="INSPECTION",
            entity_id=uuid.uuid4(),
            server_data=json.dumps({"port_place": "A"}),
            vessel_data=json.dumps({"port_place": "B"}),
            conflicting_fields=json.dumps(["port_place"]),
            status=ConflictStatus.PENDING,
        )
        SyncConflict.objects.create(
            vessel_id=self.other_vessel_id,
            entity_type="INSPECTION",
            entity_id=uuid.uuid4(),
            server_data=json.dumps({"port_place": "X"}),
            vessel_data=json.dumps({"port_place": "Y"}),
            conflicting_fields=json.dumps(["port_place"]),
            status=ConflictStatus.PENDING,
        )

        view = SyncConflictListView.as_view()
        request = self.factory.get("/api/psc/sync/conflicts/")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data["data"]), 1)
        self.assertEqual(response.data["data"][0]["id"], str(own_conflict.id))

    def test_feat_sync_004_happy_path_conflict_list_office_sees_all_pending(self):
        """PRD FEAT-SYNC-004: pending conflicts are visible to office users for triage."""
        SyncConflict.objects.create(
            vessel_id=self.vessel_id,
            entity_type="CAR",
            entity_id=uuid.uuid4(),
            server_data=json.dumps({"status": "SUBMITTED"}),
            vessel_data=json.dumps({"status": "DRAFT"}),
            conflicting_fields=json.dumps(["status"]),
            status=ConflictStatus.PENDING,
        )
        SyncConflict.objects.create(
            vessel_id=self.other_vessel_id,
            entity_type="INSPECTION",
            entity_id=uuid.uuid4(),
            server_data=json.dumps({"port_place": "A"}),
            vessel_data=json.dumps({"port_place": "B"}),
            conflicting_fields=json.dumps(["port_place"]),
            status=ConflictStatus.PENDING,
        )

        view = SyncConflictListView.as_view()
        request = self.factory.get("/api/psc/sync/conflicts/")
        force_authenticate(request, user=self.office_pic)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data["data"]), 2)

    def test_feat_sync_004_rbac_unauthenticated_conflict_list_rejected(self):
        """RBAC BACKEND_STRUCTURE 11.1: unauthenticated conflict-list request is rejected."""
        view = SyncConflictListView.as_view()
        request = self.factory.get("/api/psc/sync/conflicts/")
        response = view(request)

        self.assertIn(response.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))


class TestFEAT_SYNC_005_ConflictResolution(BaseSyncAPITestCase):
    """FEAT-SYNC-005: Conflict Resolution."""

    def _create_conflict(
        self,
        *,
        entity_type="INSPECTION",
        entity_id=None,
        server_data=None,
        vessel_data=None,
        conflicting_fields=None,
        conflict_status=ConflictStatus.PENDING,
    ):
        return SyncConflict.objects.create(
            vessel_id=self.vessel_id,
            entity_type=entity_type,
            entity_id=entity_id or uuid.uuid4(),
            server_data=json.dumps(server_data or {"port_place": "Server Port"}),
            vessel_data=json.dumps(vessel_data or {"port_place": "Vessel Port"}),
            conflicting_fields=json.dumps(conflicting_fields or ["port_place"]),
            status=conflict_status,
        )

    def _resolve(self, payload, user=None):
        view = SyncResolveConflictView.as_view()
        request = self.factory.post("/api/psc/sync/resolve-conflict/", payload, format="json")
        if user:
            force_authenticate(request, user=user)
        return view(request)

    @patch("apps.sync.conflict_resolver.notify_conflict_resolved")
    def test_feat_sync_005_happy_path_office_pic_can_keep_server(self, mock_notify):
        """PRD FEAT-SYNC-005: Office users can resolve conflict with KEEP_SERVER."""
        conflict = self._create_conflict()
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "KEEP_SERVER",
            "notes": "Office version is authoritative.",
        }

        response = self._resolve(payload, user=self.office_pic)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        conflict.refresh_from_db()
        self.assertEqual(conflict.status, ConflictStatus.RESOLVED)
        self.assertEqual(conflict.resolution, "KEEP_SERVER")
        self.assertEqual(conflict.resolved_by, self.office_pic.employee_id)
        self.assertTrue(
            AuditLog.objects.filter(
                entity_type="SYNC_CONFLICT",
                entity_id=conflict.id,
                action="RESOLVE",
            ).exists()
        )
        mock_notify.assert_called_once_with(
            str(self.vessel_id),
            "INSPECTION",
            str(conflict.entity_id),
            "KEEP_SERVER",
        )

    @patch("apps.sync.conflict_resolver.notify_conflict_resolved")
    def test_feat_sync_005_happy_path_dpa_keep_vessel_applies_changes_and_audits(self, mock_notify):
        """PRD FEAT-SYNC-005: KEEP_VESSEL applies vessel data and creates audit records."""
        inspection = self.create_inspection(sync_version=2, port_place="Server Port")
        conflict = self._create_conflict(
            entity_type="INSPECTION",
            entity_id=inspection.id,
            server_data={"port_place": "Server Port"},
            vessel_data={"port_place": "Vessel Port"},
            conflicting_fields=["port_place"],
        )
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "KEEP_VESSEL",
            "notes": "Vessel provided corrected value.",
        }

        response = self._resolve(payload, user=self.dpa)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        inspection.refresh_from_db()
        self.assertEqual(inspection.port_place, "Vessel Port")
        self.assertEqual(inspection.sync_version, 3)
        self.assertTrue(
            AuditLog.objects.filter(
                entity_type="INSPECTION",
                entity_id=inspection.id,
                action="UPDATE",
                field_name="port_place",
                performed_by=self.dpa.employee_id,
            ).exists()
        )
        self.assertTrue(
            AuditLog.objects.filter(
                entity_type="SYNC_CONFLICT",
                entity_id=conflict.id,
                action="RESOLVE",
            ).exists()
        )
        mock_notify.assert_called_once()

    @patch("apps.sync.conflict_resolver.notify_conflict_resolved")
    def test_feat_sync_005_happy_path_reopen_for_merge_sets_car_to_rework_requested(self, mock_notify):
        """PRD FEAT-SYNC-005: REOPEN_FOR_MERGE sets CAR to REWORK_REQUESTED."""
        car, _ = self.create_car_with_deficiency()
        car.status = CARStatus.PIC_ACCEPTED
        car.save(update_fields=["status"])
        conflict = self._create_conflict(
            entity_type="CAR",
            entity_id=car.id,
            server_data={"status": CARStatus.PIC_ACCEPTED},
            vessel_data={"status": CARStatus.DRAFT},
            conflicting_fields=["status"],
        )
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "REOPEN_FOR_MERGE",
            "notes": "Needs vessel rework.",
        }

        response = self._resolve(payload, user=self.office_pic)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        car.refresh_from_db()
        self.assertEqual(car.status, CARStatus.REWORK_REQUESTED)
        self.assertEqual(car.rework_count, 1)
        self.assertEqual(car.rework_requested_by, self.office_pic.employee_id)
        self.assertEqual(car.sync_version, 2)
        self.assertTrue(
            AuditLog.objects.filter(
                entity_type="CAR",
                entity_id=car.id,
                action="UPDATE",
                field_name="status",
            ).exists()
        )
        mock_notify.assert_called_once()

    @patch("apps.sync.conflict_resolver.notify_conflict_resolved")
    def test_feat_sync_005_happy_path_reopen_for_merge_sets_inspection_to_draft(self, mock_notify):
        """PRD FEAT-SYNC-005: REOPEN_FOR_MERGE reopens inspection to DRAFT."""
        inspection = self.create_inspection(status=InspectionStatus.SUBMITTED, sync_version=3)
        conflict = self._create_conflict(
            entity_type="INSPECTION",
            entity_id=inspection.id,
            server_data={"status": InspectionStatus.SUBMITTED},
            vessel_data={"status": InspectionStatus.DRAFT},
            conflicting_fields=["status"],
        )
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "REOPEN_FOR_MERGE",
            "notes": "Reopen for merge.",
        }

        response = self._resolve(payload, user=self.dpa)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        inspection.refresh_from_db()
        self.assertEqual(inspection.status, InspectionStatus.DRAFT)
        self.assertEqual(inspection.sync_version, 4)
        mock_notify.assert_called_once()

    def test_feat_sync_005_rbac_vessel_master_cannot_resolve_conflict(self):
        """RBAC BACKEND_STRUCTURE 11.1: vessel roles cannot resolve sync conflicts."""
        conflict = self._create_conflict()
        payload = {"conflict_id": str(conflict.id), "resolution": "KEEP_SERVER"}

        response = self._resolve(payload, user=self.vessel_master)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_sync_005_rbac_unauthenticated_resolve_rejected(self):
        """RBAC BACKEND_STRUCTURE 11.1: resolve-conflict endpoint requires authentication."""
        conflict = self._create_conflict()
        payload = {"conflict_id": str(conflict.id), "resolution": "KEEP_SERVER"}

        response = self._resolve(payload, user=None)

        self.assertIn(response.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))

    def test_feat_sync_005_validation_conflict_must_exist(self):
        """VALIDATION_RULES 9.2: conflict_id must reference an existing conflict."""
        payload = {
            "conflict_id": str(uuid.uuid4()),
            "resolution": "KEEP_SERVER",
        }
        response = self._resolve(payload, user=self.office_pic)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("conflict_id", response.data)

    def test_feat_sync_005_validation_conflict_must_be_pending(self):
        """VALIDATION_RULES 9.2: only PENDING conflicts can be resolved."""
        conflict = self._create_conflict(conflict_status=ConflictStatus.RESOLVED)
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "KEEP_SERVER",
        }

        response = self._resolve(payload, user=self.office_pic)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("conflict_id", response.data)

    def test_feat_sync_005_validation_resolution_must_be_valid_option(self):
        """VALIDATION_RULES 9.2: resolution must be KEEP_SERVER, KEEP_VESSEL, or REOPEN_FOR_MERGE."""
        conflict = self._create_conflict()
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "INVALID_OPTION",
        }

        response = self._resolve(payload, user=self.office_pic)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("resolution", response.data)

    def test_feat_sync_005_gap_validation_notes_max_1000(self):
        """GAP VALIDATION_RULES 9.2: notes above 1000 chars should be rejected."""
        conflict = self._create_conflict()
        payload = {
            "conflict_id": str(conflict.id),
            "resolution": "KEEP_SERVER",
            "notes": "x" * 1001,
        }

        response = self._resolve(payload, user=self.office_pic)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)


class TestFEAT_HIST_001_002_SyncHistoryAuditBoundary(BaseSyncAPITestCase):
    """
    FEAT-HIST-001/002: Sync boundary checks for activity history and audit logs.

    PRD Reference: Docs/PRD.md FEAT-HIST-001, FEAT-HIST-002
    API Reference: Docs/BACKEND_STRUCTURE.md Section 10.9 (sync pull contract)
    """

    def test_feat_hist_001_happy_path_sync_pull_includes_activity_history_events(self):
        """PRD FEAT-HIST-001: activity history must sync to vessel for offline visibility."""
        inspection = self.create_inspection(sync_version=2)
        ActivityHistory.objects.create(
            entity_type="INSPECTION",
            entity_id=inspection.id,
            vessel_id=self.vessel_id,
            event_type="INSPECTION_SUBMITTED",
            event_description="Inspection submitted for history sync coverage",
            performed_by=self.vessel_master.employee_id,
            performed_by_name=self.vessel_master.display_name,
        )

        view = SyncPullView.as_view()
        payload = {
            "vessel_id": str(self.vessel_id),
            "last_sync_token": str(uuid.uuid4()),
            "last_server_version": 0,
        }
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("activity_history", response.data["data"])
        self.assertGreaterEqual(len(response.data["data"]["activity_history"]), 1)
        event_types = [item["event_type"] for item in response.data["data"]["activity_history"]]
        self.assertIn("INSPECTION_SUBMITTED", event_types)

    def test_feat_hist_002_happy_path_sync_pull_excludes_audit_logs(self):
        """PRD FEAT-HIST-002: audit logs remain server-only and are not synced to vessel."""
        inspection = self.create_inspection(sync_version=3)
        AuditLog.objects.create(
            entity_type="INSPECTION",
            entity_id=inspection.id,
            action="UPDATE",
            field_name="status",
            old_value="DRAFT",
            new_value="SUBMITTED",
            performed_by=self.office_pic.employee_id,
            performed_by_role=RoleCodes.OFFICE_PIC,
        )

        view = SyncPullView.as_view()
        payload = {
            "vessel_id": str(self.vessel_id),
            "last_sync_token": str(uuid.uuid4()),
            "last_server_version": 0,
        }
        request = self.factory.post("/api/psc/sync/pull/", payload, format="json")
        force_authenticate(request, user=self.vessel_master)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("data", response.data)
        self.assertNotIn("audit_log", response.data["data"])
        self.assertNotIn("audit_logs", response.data["data"])
