from django.http import JsonResponse
from django.urls import path

from apps.certs.jobs.cadence_heartbeat import get_last_cadence_heartbeat, serialize_utc
from apps.certs.views import (
    AuditLogDetailView,
    AuditLogExportView,
    AuditLogListView,
    AuditorAccessDetailView,
    AuditorAccessListCreateView,
    CatalogRowAuditHistoryView,
    CatalogRowBulkSoftDeleteView,
    CatalogRowDeprecateView,
    CatalogRowDetailView,
    CatalogRowListCreateView,
    CatalogSectionListView,
    ClassSnapshotDetailView,
    ClassSnapshotListCreateView,
    ClassSnapshotReparseView,
    AlertConfigView,
    CertNotificationAckView,
    CertNotificationListView,
    CertNotificationMagicAckView,
    FleetDashboardView,
    OnboardingBatchCommitView,
    OnboardingBatchCreateView,
    OnboardingBatchDetailView,
    OnboardingBatchPreviewView,
    OnboardingCoverageOverrideView,
    OnboardingFmSignoffView,
    OnboardingProfileView,
    OnboardingRollbackView,
    OnboardingSessionDetailView,
    OnboardingSessionListCreateView,
    PrintArtifactCreateView,
    PrintArtifactDetailView,
    PrintArtifactListView,
    PrintShareBundleView,
    ReconciliationFlagAddMappingView,
    ReconciliationFlagMarkReviewedView,
    ReconciliationFlagNotifyMasterView,
    ReconciliationRunDetailView,
    ReconciliationRunListView,
    SettingsView,
    TrackedItemApproveView,
    TrackedItemDetailView,
    TrackedItemListCreateView,
    TrackedItemPdfInlineView,
    TrackedItemQuarantineResolveView,
    TrackedItemRemovePdfView,
    TrackedItemRejectView,
    TrackedItemSubmitView,
    TrackedItemUploadPdfView,
    VesselClassChangeView,
    VesselDashboardView,
    VesselDecommissionView,
    VesselFlagChangeView,
    VesselProfileView,
    VesselSaleHandoverView,
)

app_name = "certs"


def health_check(request):
    """Read-only module health endpoint for OBS-CERT-12."""
    return JsonResponse(
        {
            "status": "ok",
            "last_cadence_heartbeat": serialize_utc(get_last_cadence_heartbeat()),
        }
    )


urlpatterns = [
    path("health/", health_check, name="health"),
    path("catalog/sections/", CatalogSectionListView.as_view(), name="catalog-sections"),
    path("catalog/rows/", CatalogRowListCreateView.as_view(), name="catalog-rows"),
    path("catalog/rows/bulk-soft-delete/", CatalogRowBulkSoftDeleteView.as_view(), name="catalog-row-bulk-soft-delete"),
    path("catalog/rows/<str:catalog_id>/audit/", CatalogRowAuditHistoryView.as_view(), name="catalog-row-audit"),
    path("catalog/rows/<str:catalog_id>/deprecate/", CatalogRowDeprecateView.as_view(), name="catalog-row-deprecate"),
    path("catalog/rows/<str:catalog_id>/", CatalogRowDetailView.as_view(), name="catalog-row-detail"),
    path("tracked-items/", TrackedItemListCreateView.as_view(), name="tracked-items"),
    path("tracked-items/<str:tracked_item_id>/submit/", TrackedItemSubmitView.as_view(), name="tracked-item-submit"),
    path("tracked-items/<str:tracked_item_id>/approve/", TrackedItemApproveView.as_view(), name="tracked-item-approve"),
    path("tracked-items/<str:tracked_item_id>/reject/", TrackedItemRejectView.as_view(), name="tracked-item-reject"),
    path("tracked-items/<str:tracked_item_id>/upload-pdf/", TrackedItemUploadPdfView.as_view(), name="tracked-item-upload-pdf"),
    path("tracked-items/<str:tracked_item_id>/remove-pdf/", TrackedItemRemovePdfView.as_view(), name="tracked-item-remove-pdf"),
    path(
        "tracked-items/<str:tracked_item_id>/pdfs/<str:blob_id>/view/",
        TrackedItemPdfInlineView.as_view(),
        name="tracked-item-pdf-view",
    ),
    path(
        "tracked-items/<str:tracked_item_id>/quarantine-resolve/",
        TrackedItemQuarantineResolveView.as_view(),
        name="tracked-item-quarantine-resolve",
    ),
    path("tracked-items/<str:tracked_item_id>/", TrackedItemDetailView.as_view(), name="tracked-item-detail"),
    path("dashboard/fleet/", FleetDashboardView.as_view(), name="fleet-dashboard"),
    path("dashboard/vessel/<str:imo>/", VesselDashboardView.as_view(), name="vessel-dashboard"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("alerts/config/", AlertConfigView.as_view(), name="alerts-config"),
    path("vessel/<str:imo>/profile/", VesselProfileView.as_view(), name="vessel-profile"),
    path("vessel/<str:imo>/flag-change/", VesselFlagChangeView.as_view(), name="vessel-flag-change"),
    path("vessel/<str:imo>/class-change/", VesselClassChangeView.as_view(), name="vessel-class-change"),
    path("vessel/<str:imo>/sale-handover/", VesselSaleHandoverView.as_view(), name="vessel-sale-handover"),
    path("vessel/<str:imo>/decommission/", VesselDecommissionView.as_view(), name="vessel-decommission"),
    path("class-snapshots/", ClassSnapshotListCreateView.as_view(), name="class-snapshots"),
    path("class-snapshots/<uuid:snapshot_id>/reparse/", ClassSnapshotReparseView.as_view(), name="class-snapshot-reparse"),
    path("class-snapshots/<uuid:snapshot_id>/", ClassSnapshotDetailView.as_view(), name="class-snapshot-detail"),
    path("print/", PrintArtifactCreateView.as_view(), name="print-create"),
    path("print/artifacts/", PrintArtifactListView.as_view(), name="print-artifacts"),
    path("print/artifacts/<str:print_id>/", PrintArtifactDetailView.as_view(), name="print-artifact-detail"),
    path("print/share-bundle/", PrintShareBundleView.as_view(), name="print-share-bundle"),
    path("notifications/", CertNotificationListView.as_view(), name="notifications"),
    path("notifications/ack/<path:token>/", CertNotificationMagicAckView.as_view(), name="notification-magic-ack"),
    path("notifications/<uuid:notification_id>/ack/", CertNotificationAckView.as_view(), name="notification-ack"),
    path("audit-log/", AuditLogListView.as_view(), name="audit-log"),
    path("audit-log/export/", AuditLogExportView.as_view(), name="audit-log-export"),
    path("audit-log/<uuid:audit_id>/", AuditLogDetailView.as_view(), name="audit-log-detail"),
    path("auditor-access/", AuditorAccessListCreateView.as_view(), name="auditor-access"),
    path("auditor-access/<uuid:grant_id>/", AuditorAccessDetailView.as_view(), name="auditor-access-detail"),
    path("reconciliation/runs/", ReconciliationRunListView.as_view(), name="reconciliation-runs"),
    path("reconciliation/runs/<str:run_id>/", ReconciliationRunDetailView.as_view(), name="reconciliation-run-detail"),
    path(
        "reconciliation/flags/<str:flag_id>/notify-master/",
        ReconciliationFlagNotifyMasterView.as_view(),
        name="reconciliation-flag-notify-master",
    ),
    path(
        "reconciliation/flags/<str:flag_id>/mark-reviewed/",
        ReconciliationFlagMarkReviewedView.as_view(),
        name="reconciliation-flag-mark-reviewed",
    ),
    path(
        "reconciliation/flags/<str:flag_id>/add-mapping/",
        ReconciliationFlagAddMappingView.as_view(),
        name="reconciliation-flag-add-mapping",
    ),
    path("onboarding/", OnboardingSessionListCreateView.as_view(), name="onboarding-sessions"),
    path("onboarding/batch/<uuid:batch_id>/", OnboardingBatchDetailView.as_view(), name="onboarding-batch-detail"),
    path("onboarding/batch/<uuid:batch_id>/preview/", OnboardingBatchPreviewView.as_view(), name="onboarding-batch-preview"),
    path("onboarding/batch/<uuid:batch_id>/commit/", OnboardingBatchCommitView.as_view(), name="onboarding-batch-commit"),
    path("onboarding/<str:vessel_id>/profile/", OnboardingProfileView.as_view(), name="onboarding-profile"),
    path("onboarding/<str:vessel_id>/batch/", OnboardingBatchCreateView.as_view(), name="onboarding-batch-create"),
    path(
        "onboarding/<str:vessel_id>/coverage-override/",
        OnboardingCoverageOverrideView.as_view(),
        name="onboarding-coverage-override",
    ),
    path("onboarding/<str:vessel_id>/fm-signoff/", OnboardingFmSignoffView.as_view(), name="onboarding-fm-signoff"),
    path("onboarding/<str:vessel_id>/rollback/", OnboardingRollbackView.as_view(), name="onboarding-rollback"),
    path("onboarding/<str:vessel_id>/", OnboardingSessionDetailView.as_view(), name="onboarding-session-detail"),
]
