# Generated by Django 5.2.10 on 2026-02-04 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'department',
                'ordering': ['department_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalCrewList',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(max_length=50)),
                ('Crew_ref_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'final_crew_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MappingRoleUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('role_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapping_role_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterRole',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MscReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_not_id', models.UUIDField()),
                ('sent_to', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'msc_reminder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_role', models.CharField(max_length=45)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=45)),
                ('manager_employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_username', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=45, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('upload_photo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_sign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
