# Generated by Django 5.2.11 on 2026-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circular_office', '0002_delete_finalcrewlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCrewList',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('CrewID', models.CharField(max_length=50)),
                ('Crew_ref_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'final_crew_list',
                'managed': False,
            },
        ),
    ]
