/**
 * Tests for CAR Validation Schemas
 *
 * PRD Reference: PRD.md FEAT-CAR-002, FEAT-CAR-004, FEAT-CAR-011
 * Validation Reference: VALIDATION_RULES.md Sections 4 & 5
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import {
  updateCarSchema,
  addActionSchema,
  validateCarSubmission,
} from './car';
import type { CorrectiveAction, Evidence } from '@/types';

// ============================================================================
// HELPERS
// ============================================================================

function makeAction(overrides: Partial<CorrectiveAction> = {}): CorrectiveAction {
  return {
    id: 1,
    car_id: 1,
    action_type: 'IMMEDIATE',
    action_type_display: 'Immediate',
    description: 'Fix the issue with a detailed procedural action plan that exceeds fifty chars.',
    owner_crew_id: null,
    owner_user_id: null,
    owner_name: null,
    due_date: null,
    is_completed: false,
    completed_at: null,
    completion_remarks: null,
    sequence_no: 1,
    created_by: 'user1',
    created_date: '2026-01-01',
    ...overrides,
  };
}

function makeEvidence(overrides: Partial<Evidence> = {}): Evidence {
  return {
    id: 1,
    car_id: 1,
    evidence_type: 'BEFORE',
    evidence_type_display: 'Before',
    file_name: 'photo.jpg',
    file_path: '/uploads/photo.jpg',
    file_size: 1024,
    mime_type: 'image/jpeg',
    description: 'Before photo',
    uploaded_by: 'user1',
    uploaded_at: '2026-01-01',
    ...overrides,
  };
}

function futureDate() {
  const d = new Date();
  d.setDate(d.getDate() + 7);
  return d.toISOString().split('T')[0];
}

function yesterday() {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().split('T')[0];
}

// ============================================================================
// updateCarSchema — HAPPY PATH
// ============================================================================

describe('updateCarSchema — happy path', () => {
  it('test_feat_car_002_happy_path_empty_draft_passes', () => {
    const result = updateCarSchema.safeParse({});
    expect(result.success).toBe(true);
  });

  it('test_feat_car_002_happy_path_full_draft_passes', () => {
    const result = updateCarSchema.safeParse({
      root_cause_summary: 'A'.repeat(50),
      target_date: futureDate(),
      clc_item_ids: ['CLC-001', 'CLC-002'],
      custom_cause_text: 'Custom cause',
    });
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// updateCarSchema — VALIDATION
// ============================================================================

describe('updateCarSchema — root_cause_summary validation', () => {
  it('test_feat_car_002_validation_root_cause_below_min_fails', () => {
    const result = updateCarSchema.safeParse({ root_cause_summary: 'Too short' });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_002_validation_root_cause_at_min_passes', () => {
    const result = updateCarSchema.safeParse({ root_cause_summary: 'A'.repeat(50) });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_002_validation_root_cause_empty_string_passes', () => {
    // Empty string is treated as "not provided" for draft save
    const result = updateCarSchema.safeParse({ root_cause_summary: '' });
    expect(result.success).toBe(true);
  });
});

describe('updateCarSchema — target_date validation', () => {
  it('test_feat_car_002_validation_past_target_date_fails', () => {
    const result = updateCarSchema.safeParse({ target_date: yesterday() });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_002_validation_today_target_date_passes', () => {
    const today = new Date().toISOString().split('T')[0];
    const result = updateCarSchema.safeParse({ target_date: today });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_002_validation_future_target_date_passes', () => {
    const result = updateCarSchema.safeParse({ target_date: futureDate() });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_002_validation_null_target_date_passes', () => {
    const result = updateCarSchema.safeParse({ target_date: null });
    expect(result.success).toBe(true);
  });
});

describe('updateCarSchema — custom_cause_text validation', () => {
  it('test_feat_car_002_validation_custom_cause_over_max_fails', () => {
    const result = updateCarSchema.safeParse({ custom_cause_text: 'A'.repeat(501) });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_002_validation_custom_cause_at_max_passes', () => {
    const result = updateCarSchema.safeParse({ custom_cause_text: 'A'.repeat(500) });
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// addActionSchema — HAPPY PATH
// ============================================================================

describe('addActionSchema — happy path', () => {
  it('test_feat_car_011_happy_path_immediate_action_passes', () => {
    const result = addActionSchema.safeParse({
      action_type: 'IMMEDIATE',
      description: 'A'.repeat(10),
    });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_011_happy_path_long_term_action_passes', () => {
    const result = addActionSchema.safeParse({
      action_type: 'LONG_TERM',
      description: 'A'.repeat(10),
      owner_crew_id: 'crew-1',
      due_date: futureDate(),
    });
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// addActionSchema — VALIDATION
// ============================================================================

describe('addActionSchema — validation', () => {
  it('test_feat_car_011_validation_missing_action_type_fails', () => {
    const result = addActionSchema.safeParse({ description: 'A'.repeat(10) });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_011_validation_invalid_action_type_fails', () => {
    const result = addActionSchema.safeParse({ action_type: 'WRONG', description: 'A'.repeat(10) });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_011_validation_description_below_min_fails', () => {
    const result = addActionSchema.safeParse({ action_type: 'IMMEDIATE', description: 'Short' });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_011_validation_description_at_min_passes', () => {
    const result = addActionSchema.safeParse({ action_type: 'IMMEDIATE', description: 'A'.repeat(10) });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_011_validation_description_over_max_fails', () => {
    const result = addActionSchema.safeParse({ action_type: 'IMMEDIATE', description: 'A'.repeat(4001) });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_011_validation_past_due_date_fails', () => {
    const result = addActionSchema.safeParse({
      action_type: 'IMMEDIATE',
      description: 'A'.repeat(10),
      due_date: yesterday(),
    });
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// validateCarSubmission — HAPPY PATH
// ============================================================================

describe('validateCarSubmission — happy path', () => {
  it('test_feat_car_004_happy_path_valid_submission_passes', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      ['CLC-001'],
      null,
      [
        makeAction({ action_type: 'IMMEDIATE' }),
        makeAction({ action_type: 'LONG_TERM', id: 2 }),
      ],
      [
        makeEvidence({ evidence_type: 'BEFORE' }),
        makeEvidence({ evidence_type: 'AFTER', id: 2 }),
      ]
    );
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it('test_feat_car_004_happy_path_custom_cause_instead_of_clc_passes', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      [],
      'Custom root cause text',
      [
        makeAction({ action_type: 'IMMEDIATE' }),
        makeAction({ action_type: 'LONG_TERM', id: 2 }),
      ],
      [
        makeEvidence({ evidence_type: 'BEFORE' }),
        makeEvidence({ evidence_type: 'AFTER', id: 2 }),
      ]
    );
    expect(result.valid).toBe(true);
  });
});

// ============================================================================
// validateCarSubmission — VALIDATION FAILURES
// ============================================================================

describe('validateCarSubmission — validation', () => {
  it('test_feat_car_004_validation_short_root_cause_fails', () => {
    const result = validateCarSubmission(
      'Too short',
      ['CLC-001'],
      null,
      [makeAction({ action_type: 'IMMEDIATE' }), makeAction({ action_type: 'LONG_TERM', id: 2 })],
      [makeEvidence({ evidence_type: 'BEFORE' }), makeEvidence({ evidence_type: 'AFTER', id: 2 })]
    );
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('Root cause summary'))).toBe(true);
  });

  it('test_feat_car_004_validation_null_root_cause_fails', () => {
    const result = validateCarSubmission(
      null,
      ['CLC-001'],
      null,
      [makeAction({ action_type: 'IMMEDIATE' }), makeAction({ action_type: 'LONG_TERM', id: 2 })],
      [makeEvidence({ evidence_type: 'BEFORE' }), makeEvidence({ evidence_type: 'AFTER', id: 2 })]
    );
    expect(result.valid).toBe(false);
  });

  it('test_feat_car_004_validation_no_cause_at_all_fails', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      [],
      null,
      [makeAction({ action_type: 'IMMEDIATE' }), makeAction({ action_type: 'LONG_TERM', id: 2 })],
      [makeEvidence({ evidence_type: 'BEFORE' }), makeEvidence({ evidence_type: 'AFTER', id: 2 })]
    );
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('root cause'))).toBe(true);
  });

  it('test_feat_car_004_validation_whitespace_only_custom_cause_fails', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      [],
      '   ',
      [makeAction({ action_type: 'IMMEDIATE' }), makeAction({ action_type: 'LONG_TERM', id: 2 })],
      [makeEvidence({ evidence_type: 'BEFORE' }), makeEvidence({ evidence_type: 'AFTER', id: 2 })]
    );
    expect(result.valid).toBe(false);
  });

  it('test_feat_car_004_validation_no_immediate_action_fails', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      ['CLC-001'],
      null,
      [makeAction({ action_type: 'LONG_TERM' })],
      [makeEvidence({ evidence_type: 'BEFORE' }), makeEvidence({ evidence_type: 'AFTER', id: 2 })]
    );
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('immediate'))).toBe(true);
  });

  it('test_feat_car_004_validation_no_long_term_action_fails', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      ['CLC-001'],
      null,
      [makeAction({ action_type: 'IMMEDIATE' })],
      [makeEvidence({ evidence_type: 'BEFORE' }), makeEvidence({ evidence_type: 'AFTER', id: 2 })]
    );
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('long-term'))).toBe(true);
  });

  it('test_feat_car_004_validation_no_before_evidence_fails', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      ['CLC-001'],
      null,
      [makeAction({ action_type: 'IMMEDIATE' }), makeAction({ action_type: 'LONG_TERM', id: 2 })],
      [makeEvidence({ evidence_type: 'AFTER' })]
    );
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('BEFORE'))).toBe(true);
  });

  it('test_feat_car_004_validation_no_after_evidence_fails', () => {
    const result = validateCarSubmission(
      'A'.repeat(50),
      ['CLC-001'],
      null,
      [makeAction({ action_type: 'IMMEDIATE' }), makeAction({ action_type: 'LONG_TERM', id: 2 })],
      [makeEvidence({ evidence_type: 'BEFORE' })]
    );
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.includes('AFTER'))).toBe(true);
  });

  it('test_feat_car_004_validation_all_missing_returns_all_errors', () => {
    const result = validateCarSubmission(null, [], null, [], []);
    expect(result.valid).toBe(false);
    // root cause summary, no cause, no immediate, no long term, no before, no after
    expect(result.errors.length).toBeGreaterThanOrEqual(5);
  });
});
