/**
 * Tests for Deficiency Validation Schemas
 *
 * PRD Reference: PRD.md FEAT-INS-003 Add Deficiency
 * Validation Reference: VALIDATION_RULES.md Section 3
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import { addDeficiencySchema } from './deficiency';

// ============================================================================
// HELPERS
// ============================================================================

function validDeficiency() {
  return {
    def_code: '01101',
    def_text: 'Fire doors not closing properly, requiring immediate repair.',
    action_code: '17',
    target_date: null,
  };
}

function futureDate() {
  const d = new Date();
  d.setDate(d.getDate() + 7);
  return d.toISOString().split('T')[0];
}

function yesterday() {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().split('T')[0];
}

// ============================================================================
// HAPPY PATH TESTS
// ============================================================================

describe('addDeficiencySchema — happy path', () => {
  it('test_feat_ins_003_happy_path_valid_deficiency_passes', () => {
    const result = addDeficiencySchema.safeParse(validDeficiency());
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_003_happy_path_with_action_code_passes', () => {
    const data = { ...validDeficiency(), action_code: '10' };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_003_happy_path_with_future_target_date_passes', () => {
    const data = { ...validDeficiency(), target_date: futureDate() };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_003_happy_path_with_today_target_date_passes', () => {
    const today = new Date().toISOString().split('T')[0];
    const data = { ...validDeficiency(), target_date: today };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// VALIDATION TESTS — def_code
// ============================================================================

describe('addDeficiencySchema — def_code validation', () => {
  it('test_feat_ins_003_validation_missing_def_code_fails', () => {
    const data = { ...validDeficiency(), def_code: undefined };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_003_validation_empty_def_code_fails', () => {
    const data = { ...validDeficiency(), def_code: '' };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// VALIDATION TESTS — def_text
// ============================================================================

describe('addDeficiencySchema — def_text validation', () => {
  it('test_feat_ins_003_validation_missing_description_fails', () => {
    const data = { ...validDeficiency(), def_text: undefined };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_003_validation_description_below_min_fails', () => {
    const data = { ...validDeficiency(), def_text: 'Too short' };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_003_validation_description_at_min_passes', () => {
    const data = { ...validDeficiency(), def_text: 'A'.repeat(10) };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_003_validation_description_over_max_fails', () => {
    const data = { ...validDeficiency(), def_text: 'A'.repeat(4001) };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_003_validation_description_at_max_passes', () => {
    const data = { ...validDeficiency(), def_text: 'A'.repeat(4000) };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// VALIDATION TESTS — target_date
// ============================================================================

describe('addDeficiencySchema — target_date validation', () => {
  it('test_feat_ins_003_validation_past_target_date_fails', () => {
    const data = { ...validDeficiency(), target_date: yesterday() };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_003_validation_null_target_date_passes', () => {
    const data = { ...validDeficiency(), target_date: null };
    const result = addDeficiencySchema.safeParse(data);
    expect(result.success).toBe(true);
  });
});
