/**
 * Tests for Evidence Validation Schemas
 *
 * PRD Reference: PRD.md FEAT-CAR-003 Upload CAR Evidence
 * Validation Reference: VALIDATION_RULES.md Section 6
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import { evidenceSchema, validateEvidenceFile } from './evidence';

// ============================================================================
// HAPPY PATH TESTS
// ============================================================================

describe('evidenceSchema — happy path', () => {
  it('test_feat_car_003_happy_path_valid_before_evidence_passes', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'BEFORE',
      description: 'Photo of damaged fire door before repair',
    });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_003_happy_path_valid_after_evidence_passes', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'AFTER',
      description: 'Photo after repair completed',
    });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_003_happy_path_all_evidence_types_pass', () => {
    for (const etype of ['BEFORE', 'AFTER', 'EVIDENCE', 'OTHER'] as const) {
      const result = evidenceSchema.safeParse({
        evidence_type: etype,
        description: 'Valid description text',
      });
      expect(result.success, `type ${etype} should pass`).toBe(true);
    }
  });
});

// ============================================================================
// VALIDATION TESTS — evidence_type
// ============================================================================

describe('evidenceSchema — evidence_type validation', () => {
  it('test_feat_car_003_validation_missing_evidence_type_fails', () => {
    const result = evidenceSchema.safeParse({ description: 'Valid description text' });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_003_validation_invalid_evidence_type_fails', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'WRONG',
      description: 'Valid description text',
    });
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// VALIDATION TESTS — description
// ============================================================================

describe('evidenceSchema — description validation', () => {
  it('test_feat_car_003_validation_missing_description_fails', () => {
    const result = evidenceSchema.safeParse({ evidence_type: 'BEFORE' });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_003_validation_description_below_min_fails', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'BEFORE',
      description: 'Shor',
    });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_003_validation_description_at_min_passes', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'BEFORE',
      description: 'A'.repeat(5),
    });
    expect(result.success).toBe(true);
  });

  it('test_feat_car_003_validation_description_over_max_fails', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'BEFORE',
      description: 'A'.repeat(501),
    });
    expect(result.success).toBe(false);
  });

  it('test_feat_car_003_validation_description_at_max_passes', () => {
    const result = evidenceSchema.safeParse({
      evidence_type: 'BEFORE',
      description: 'A'.repeat(500),
    });
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// FILE VALIDATION TESTS
// ============================================================================

describe('validateEvidenceFile', () => {
  it('test_feat_car_003_happy_path_valid_pdf_returns_null', () => {
    const file = new File(['content'], 'doc.pdf', { type: 'application/pdf' });
    expect(validateEvidenceFile(file)).toBeNull();
  });

  it('test_feat_car_003_happy_path_valid_jpeg_returns_null', () => {
    const file = new File(['content'], 'photo.jpg', { type: 'image/jpeg' });
    expect(validateEvidenceFile(file)).toBeNull();
  });

  it('test_feat_car_003_validation_png_file_rejected', () => {
    const file = new File(['content'], 'photo.png', { type: 'image/png' });
    const error = validateEvidenceFile(file);
    expect(error).not.toBeNull();
    expect(error).toContain('PDF');
  });

  it('test_feat_car_003_validation_docx_file_rejected', () => {
    const file = new File(['content'], 'doc.docx', {
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    });
    expect(validateEvidenceFile(file)).not.toBeNull();
  });

  it('test_feat_car_003_validation_over_3mb_rejected', () => {
    const bigContent = new Uint8Array(3 * 1024 * 1024 + 1);
    const file = new File([bigContent], 'big.pdf', { type: 'application/pdf' });
    const error = validateEvidenceFile(file);
    expect(error).not.toBeNull();
    expect(error).toContain('3MB');
  });

  it('test_feat_car_003_validation_exactly_3mb_passes', () => {
    const content = new Uint8Array(3 * 1024 * 1024);
    const file = new File([content], 'exact.pdf', { type: 'application/pdf' });
    expect(validateEvidenceFile(file)).toBeNull();
  });
});
