/**
 * Tests for Inspection Validation Schemas
 *
 * PRD Reference: PRD.md FEAT-INS-001 Create Inspection
 * Validation Reference: VALIDATION_RULES.md Section 2
 *
 * Generated by: Frontend Test Backfill
 * Date: 2026-02-08
 */

import { describe, it, expect } from 'vitest';
import {
  createInspectionSchema,
  validateInspectionReportFile,
  canSubmitInspection,
} from './inspection';

// ============================================================================
// HELPERS
// ============================================================================

function validPSCData() {
  return {
    inspection_type: 'PSC' as const,
    psc_subtype: 'INITIAL' as const,
    inspection_date: '2026-01-15',
    port: 'Singapore',
    port_state: 'SG',
    mou_code: 'TOKYO',
    authority: '',
    inspector_name: null,
    report_reference: '',
    is_detention: false,
    def_reported: 'NO' as const,
    detention_reason: null,
  };
}

function validRSData() {
  return {
    inspection_type: 'RS' as const,
    psc_subtype: null,
    inspection_date: '2026-01-15',
    port: 'Rotterdam',
    port_state: 'NL',
    mou_code: null,
    authority: '',
    inspector_name: null,
    report_reference: '',
    is_detention: false,
    def_reported: 'NO' as const,
    detention_reason: null,
  };
}

function tomorrow() {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().split('T')[0];
}

// ============================================================================
// HAPPY PATH TESTS
// ============================================================================

describe('createInspectionSchema — happy path', () => {
  it('test_feat_ins_001_happy_path_valid_psc_inspection_passes', () => {
    const result = createInspectionSchema.safeParse(validPSCData());
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_happy_path_valid_rs_inspection_passes', () => {
    const result = createInspectionSchema.safeParse(validRSData());
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_happy_path_valid_audit_inspection_passes', () => {
    const data = { ...validRSData(), inspection_type: 'AUDIT' as const };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_happy_path_today_date_passes', () => {
    const today = new Date().toISOString().split('T')[0];
    const data = { ...validRSData(), inspection_date: today };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_happy_path_all_psc_subtypes_pass', () => {
    const subtypes = ['INITIAL', 'EXPANDED', 'CIC', 'FOLLOW_UP'] as const;
    for (const subtype of subtypes) {
      const data = { ...validPSCData(), psc_subtype: subtype };
      const result = createInspectionSchema.safeParse(data);
      expect(result.success, `subtype ${subtype} should pass`).toBe(true);
    }
  });
});

// ============================================================================
// VALIDATION TESTS — inspection_type
// ============================================================================

describe('createInspectionSchema — inspection_type validation', () => {
  it('test_feat_ins_001_validation_missing_inspection_type_fails', () => {
    const data = { ...validRSData(), inspection_type: undefined };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_invalid_inspection_type_fails', () => {
    const data = { ...validRSData(), inspection_type: 'INVALID' };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// VALIDATION TESTS — psc_subtype conditional
// ============================================================================

describe('createInspectionSchema — PSC subtype conditional validation', () => {
  it('test_feat_ins_001_validation_psc_without_subtype_fails', () => {
    const data = { ...validPSCData(), psc_subtype: null };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
    if (!result.success) {
      const paths = result.error.issues.map((i) => i.path.join('.'));
      expect(paths).toContain('psc_subtype');
    }
  });

  it('test_feat_ins_001_validation_rs_without_subtype_passes', () => {
    const data = { ...validRSData(), psc_subtype: null };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_validation_psc_with_invalid_subtype_fails', () => {
    const data = { ...validPSCData(), psc_subtype: 'WRONG' };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// VALIDATION TESTS — mou_code conditional
// ============================================================================

describe('createInspectionSchema — MOU conditional validation', () => {
  it('test_feat_ins_001_validation_psc_without_mou_fails', () => {
    const data = { ...validPSCData(), mou_code: null };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
    if (!result.success) {
      const paths = result.error.issues.map((i) => i.path.join('.'));
      expect(paths).toContain('mou_code');
    }
  });

  it('test_feat_ins_001_validation_rs_without_mou_passes', () => {
    const data = { ...validRSData(), mou_code: null };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(true);
  });
});

// ============================================================================
// VALIDATION TESTS — inspection_date
// ============================================================================

describe('createInspectionSchema — inspection_date validation', () => {
  it('test_feat_ins_001_validation_future_date_fails', () => {
    const data = { ...validRSData(), inspection_date: tomorrow() };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_missing_date_fails', () => {
    const data = { ...validRSData(), inspection_date: undefined };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_empty_date_fails', () => {
    const data = { ...validRSData(), inspection_date: '' };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// VALIDATION TESTS — port
// ============================================================================

describe('createInspectionSchema — port validation', () => {
  it('test_feat_ins_001_validation_missing_port_fails', () => {
    const data = { ...validRSData(), port: undefined };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_port_too_short_fails', () => {
    const data = { ...validRSData(), port: 'A' };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_port_at_min_length_passes', () => {
    const data = { ...validRSData(), port: 'AB' };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_validation_port_at_max_length_passes', () => {
    const data = { ...validRSData(), port: 'A'.repeat(200) };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(true);
  });

  it('test_feat_ins_001_validation_port_over_max_length_fails', () => {
    const data = { ...validRSData(), port: 'A'.repeat(201) };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// VALIDATION TESTS — optional fields boundary
// ============================================================================

describe('createInspectionSchema — optional fields boundary', () => {
  it('test_feat_ins_001_validation_country_over_max_length_fails', () => {
    const data = { ...validRSData(), port_state: 'A'.repeat(101) };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_authority_over_max_length_fails', () => {
    const data = { ...validRSData(), authority: 'A'.repeat(201) };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_inspector_name_over_max_length_fails', () => {
    const data = { ...validRSData(), inspector_name: 'A'.repeat(201) };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });

  it('test_feat_ins_001_validation_report_reference_over_max_length_fails', () => {
    const data = { ...validRSData(), report_reference: 'A'.repeat(101) };
    const result = createInspectionSchema.safeParse(data);
    expect(result.success).toBe(false);
  });
});

// ============================================================================
// FILE VALIDATION TESTS
// ============================================================================

describe('validateInspectionReportFile', () => {
  it('test_feat_ins_002_happy_path_valid_pdf_passes', () => {
    const file = new File(['content'], 'report.pdf', { type: 'application/pdf' });
    expect(validateInspectionReportFile(file)).toEqual({ valid: true });
  });

  it('test_feat_ins_002_happy_path_valid_jpeg_passes', () => {
    const file = new File(['content'], 'photo.jpg', { type: 'image/jpeg' });
    expect(validateInspectionReportFile(file)).toEqual({ valid: true });
  });

  it('test_feat_ins_002_validation_invalid_file_type_fails', () => {
    const file = new File(['content'], 'doc.docx', { type: 'application/msword' });
    const result = validateInspectionReportFile(file);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('PDF');
  });

  it('test_feat_ins_002_validation_file_over_3mb_fails', () => {
    const bigContent = new Uint8Array(3 * 1024 * 1024 + 1);
    const file = new File([bigContent], 'big.pdf', { type: 'application/pdf' });
    expect(validateInspectionReportFile(file).valid).toBe(false);
  });

  it('test_feat_ins_002_validation_file_exactly_3mb_passes', () => {
    const content = new Uint8Array(3 * 1024 * 1024);
    const file = new File([content], 'exact.pdf', { type: 'application/pdf' });
    expect(validateInspectionReportFile(file).valid).toBe(true);
  });
});

// ============================================================================
// SUBMIT VALIDATION TESTS
// ============================================================================

describe('canSubmitInspection', () => {
  it('test_feat_ins_004_happy_path_valid_submission_passes', () => {
    const result = canSubmitInspection({ hasReport: true, allDeficienciesValid: true });
    expect(result.canSubmit).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it('test_feat_ins_004_validation_no_report_blocks_submit', () => {
    const result = canSubmitInspection({ hasReport: false, allDeficienciesValid: true });
    expect(result.canSubmit).toBe(false);
    expect(result.errors).toContain('Inspection report must be attached before submission');
  });

  it('test_feat_ins_004_validation_invalid_deficiencies_blocks_submit', () => {
    const result = canSubmitInspection({ hasReport: true, allDeficienciesValid: false });
    expect(result.canSubmit).toBe(false);
    expect(result.errors).toContain('All deficiencies must have a deficiency code');
  });

  it('test_feat_ins_004_validation_both_missing_returns_two_errors', () => {
    const result = canSubmitInspection({ hasReport: false, allDeficienciesValid: false });
    expect(result.canSubmit).toBe(false);
    expect(result.errors).toHaveLength(2);
  });
});
