"""
Tests for authentication and RBAC feature backfill.

PRD Reference: Docs/PRD.md Section 2.5 (FEAT-AUTH-001, FEAT-AUTH-002)
Validation Reference: Docs/VALIDATION_RULES.md Section 9.2 (403/401 behavior patterns)
API/RBAC Reference: Docs/BACKEND_STRUCTURE.md Sections 10.1, 10.3, 10.9, 11.1, 11.2

Generated by: Test Backfill Agent
Date: 2026-02-07
"""

import uuid
from datetime import date
from unittest.mock import patch

from django.db.models import Value
from django.test import TestCase
from rest_framework import status
from rest_framework.test import APIRequestFactory, force_authenticate

from apps.accounts.backends import AuthenticatedUser, PSCJWTAuthentication
from apps.accounts.models import RoleCodes
from apps.accounts.serializers import generate_tokens_for_user
from apps.accounts.utils import resolve_current_office_permission_snapshot
from apps.accounts.views import CurrentUserView, LoginView, LogoutView, TokenRefreshView
from apps.inspection.models import Inspection, InspectionStatus
from apps.inspection.views import InspectionCreateView, InspectionDetailView, InspectionPICReviewView
from apps.sync.views import SyncResolveConflictView


def make_user(
    *,
    role: str,
    user_type: str,
    user_id: str,
    full_name: str,
    vessel_id: str | None = None,
    employee_id: str | None = None,
    crew_id: str | None = None,
):
    """Create an AuthenticatedUser test double with JWT-compatible fields."""
    return AuthenticatedUser(
        user_id=user_id,
        user_type=user_type,
        full_name=full_name,
        role=role,
        vessel_id=vessel_id,
        vessel_code="MVX" if vessel_id else None,
        employee_id=employee_id,
        crew_id=crew_id,
    )


class BaseAuthAPITestCase(TestCase):
    """Shared fixtures/helpers for authentication and RBAC tests."""

    def setUp(self):
        self.factory = APIRequestFactory()
        self.vessel_id = uuid.uuid4()
        self.other_vessel_id = uuid.uuid4()

        self.vessel_master = make_user(
            role=RoleCodes.VESSEL_MASTER,
            user_type="VESSEL",
            user_id="vm-user-1",
            full_name="Vessel Master",
            vessel_id=str(self.vessel_id),
            crew_id="KSM0001",
        )
        self.vessel_crew = make_user(
            role=RoleCodes.VESSEL_CREW,
            user_type="VESSEL",
            user_id="crew-user-1",
            full_name="Vessel Crew",
            vessel_id=str(self.vessel_id),
            crew_id="KSM0002",
        )
        self.office_pic = make_user(
            role=RoleCodes.OFFICE_PIC,
            user_type="OFFICE",
            user_id="office-user-1",
            full_name="Office PIC",
            employee_id="PIC001",
        )
        self.dpa = make_user(
            role=RoleCodes.DPA,
            user_type="OFFICE",
            user_id="dpa-user-1",
            full_name="DPA User",
            employee_id="DPA001",
        )

    def create_inspection(self, **overrides):
        payload = {
            "vessel_id": self.vessel_id,
            "inspection_type": "PSC",
            "psc_subtype": "INITIAL",
            "inspection_date": date.today(),
            "port_place": "Singapore",
            "status": InspectionStatus.SUBMITTED,
            "created_by": self.vessel_master.id,
        }
        payload.update(overrides)
        return Inspection.objects.create(**payload)


class TestFEAT_AUTH_001_UserAuthentication(BaseAuthAPITestCase):
    """FEAT-AUTH-001: User Authentication."""

    def test_feat_auth_001_happy_path_login_returns_access_refresh_and_user_payload(self):
        """PRD FEAT-AUTH-001: login returns JWT access+refresh and user identity payload."""
        view = LoginView.as_view()
        request = self.factory.post(
            "/api/psc/auth/login/",
            {"username": "vmaster", "password": "secret"},
            format="json",
        )

        with patch("apps.accounts.views.PSCAuthenticationBackend.authenticate", return_value=self.vessel_master):
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("data", response.data)
        self.assertIn("access", response.data["data"])
        self.assertIn("refresh", response.data["data"])
        self.assertEqual(response.data["data"]["user"]["role"], RoleCodes.VESSEL_MASTER)
        self.assertEqual(response.data["data"]["user"]["vessel_id"], str(self.vessel_id))

    def test_feat_auth_001_validation_missing_credentials_returns_400(self):
        """BACKEND_STRUCTURE 10.1: login request validation rejects missing fields."""
        view = LoginView.as_view()
        request = self.factory.post("/api/psc/auth/login/", {"username": "vmaster"}, format="json")
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["error"], "VALIDATION_ERROR")
        self.assertIn("password", response.data["details"])

    def test_feat_auth_001_error_invalid_credentials_returns_401(self):
        """PRD FEAT-AUTH-001: invalid username/password must be rejected."""
        view = LoginView.as_view()
        request = self.factory.post(
            "/api/psc/auth/login/",
            {"username": "invalid", "password": "wrong"},
            format="json",
        )

        with patch("apps.accounts.views.PSCAuthenticationBackend.authenticate", return_value=None):
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
        self.assertEqual(response.data["error"], "AUTHENTICATION_FAILED")

    def test_feat_auth_001_happy_path_refresh_returns_new_access_token(self):
        """PRD FEAT-AUTH-001: refresh token endpoint issues a new access token without re-login."""
        tokens = generate_tokens_for_user(self.vessel_master)
        view = TokenRefreshView.as_view()
        request = self.factory.post(
            "/api/psc/auth/refresh/",
            {"refresh": tokens["refresh"]},
            format="json",
        )
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("access", response.data["data"])
        self.assertTrue(response.data["data"]["access"])

    def test_feat_auth_001_validation_invalid_refresh_token_returns_401(self):
        """BACKEND_STRUCTURE 10.1: refresh endpoint rejects invalid/expired refresh tokens."""
        view = TokenRefreshView.as_view()
        request = self.factory.post(
            "/api/psc/auth/refresh/",
            {"refresh": "not-a-valid-token"},
            format="json",
        )
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
        self.assertEqual(response.data["error"], "INVALID_TOKEN")

    def test_feat_auth_001_happy_path_current_user_reads_claims_from_access_token(self):
        """PRD FEAT-AUTH-001: protected `me` endpoint returns identity derived from JWT claims."""
        view = CurrentUserView.as_view()
        token_claims = {
            "user_id": self.vessel_master.id,
            "user_type": self.vessel_master.user_type,
            "full_name": self.vessel_master.full_name,
            "role": self.vessel_master.role,
            "vessel_id": self.vessel_master.vessel_id,
            "vessel_code": self.vessel_master.vessel_code,
            "crew_id": self.vessel_master.crew_id,
        }
        request = self.factory.get("/api/psc/auth/me/")
        force_authenticate(request, user=self.vessel_master, token=token_claims)
        response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["id"], self.vessel_master.id)
        self.assertEqual(response.data["data"]["role"], RoleCodes.VESSEL_MASTER)

    def test_feat_auth_001_current_user_refreshes_vessel_permissions_from_profile_mapping(self):
        """`me` should prefer current vessel profile permissions over stale token claims."""
        view = CurrentUserView.as_view()
        token_claims = {
            "user_id": self.vessel_master.id,
            "user_type": self.vessel_master.user_type,
            "full_name": self.vessel_master.full_name,
            "role": self.vessel_master.role,
            "rank": "MASTER",
            "form_ids": [],
            "process_ids": [],
        }
        request = self.factory.get("/api/psc/auth/me/")
        force_authenticate(request, user=self.vessel_master, token=token_claims)

        with patch(
            "apps.accounts.views._get_current_vessel_permission_snapshot",
            return_value={
                "rank": "MASTER",
                "role_name": "MASTER",
                "safety_role_name": "MASTER",
                "form_ids": ["SAF_F_003"],
                "process_ids": ["SAF_P_004"],
                "department": None,
                "full_name": self.vessel_master.full_name,
            },
        ):
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["role_name"], "MASTER")
        self.assertEqual(response.data["data"]["safety_role_name"], "MASTER")
        self.assertEqual(response.data["data"]["form_ids"], ["SAF_F_003"])
        self.assertEqual(response.data["data"]["process_ids"], ["SAF_P_004"])

    def test_feat_auth_001_current_user_refreshes_office_permissions_from_mapping(self):
        """`me` should surface fresh office permissions even when token claims are stale."""
        view = CurrentUserView.as_view()
        token_claims = {
            "user_id": self.office_pic.id,
            "login_id": "pic001",
            "user_type": self.office_pic.user_type,
            "full_name": self.office_pic.full_name,
            "role": self.office_pic.role,
            "employee_id": self.office_pic.employee_id,
            "form_ids": [],
            "process_ids": [],
        }
        request = self.factory.get("/api/psc/auth/me/")
        force_authenticate(request, user=self.office_pic, token=token_claims)

        with patch(
            "apps.accounts.views._get_current_office_permission_snapshot",
            return_value={
                "role": RoleCodes.OFFICE_PIC,
                "role_name": "SEQ MANAGER",
                "safety_role_name": "DPA",
                "form_ids": ["SAF_F_015"],
                "process_ids": ["SAF_P_023"],
                "has_global_vessel_access": False,
                "employee_id": self.office_pic.employee_id,
                "email": None,
                "department": None,
                "full_name": self.office_pic.full_name,
            },
        ):
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["data"]["role_name"], "SEQ MANAGER")
        self.assertEqual(response.data["data"]["safety_role_name"], "DPA")
        self.assertEqual(response.data["data"]["form_ids"], ["SAF_F_015"])
        self.assertEqual(response.data["data"]["process_ids"], ["SAF_P_023"])

    def test_feat_auth_001_fleet_manager_office_snapshot_is_global(self):
        """Fleet Manager Safety role needs fleet-wide Safety tabs even without assigned vessel rows."""
        with (
            patch(
                "apps.accounts.utils.get_office_profile_bundle_by_mapping",
                return_value=("FLEET MANAGER", ["SAF_F_001", "SAF_F_002"], ["SAF_P_005"]),
            ),
            patch("apps.accounts.utils.get_office_global_reviewer_role", return_value=None),
        ):
            snapshot = resolve_current_office_permission_snapshot(
                user_type="OFFICE",
                login_id="fm001",
                employee_id="FM001",
                role=RoleCodes.OFFICE_PIC,
                has_global_vessel_access=None,
                full_name="Fleet Manager",
            )

        self.assertEqual(snapshot["safety_role_name"], "FM")
        self.assertTrue(snapshot["has_global_vessel_access"])

    def test_feat_auth_001_psc_jwt_authentication_refreshes_vessel_permissions_from_profile_mapping(self):
        """Authenticated Safety requests should not rely on stale vessel permission claims."""
        validated_token = {
            "user_id": self.vessel_master.id,
            "user_type": self.vessel_master.user_type,
            "full_name": self.vessel_master.full_name,
            "role": self.vessel_master.role,
            "rank": "MASTER",
            "department": "DECK",
            "form_ids": [],
            "process_ids": [],
        }

        with patch(
            "apps.accounts.backends.resolve_current_vessel_permission_snapshot",
            return_value={
                "rank": "MASTER",
                "role_name": "MASTER",
                "safety_role_name": "MASTER",
                "form_ids": ["SAF_F_015"],
                "process_ids": ["SAF_P_023"],
                "department": "DECK",
                "full_name": self.vessel_master.full_name,
            },
        ):
            user = PSCJWTAuthentication().get_user(validated_token)

        self.assertEqual(user.role_name, "MASTER")
        self.assertEqual(user.safety_role_name, "MASTER")
        self.assertEqual(user.form_ids, ["SAF_F_015"])
        self.assertEqual(user.process_ids, ["SAF_P_023"])

    def test_feat_auth_001_psc_jwt_authentication_refreshes_office_permissions_from_mapping(self):
        """Authenticated Safety requests should use refreshed office permissions."""
        validated_token = {
            "user_id": self.office_pic.id,
            "login_id": "pic001",
            "user_type": self.office_pic.user_type,
            "full_name": self.office_pic.full_name,
            "role": self.office_pic.role,
            "employee_id": self.office_pic.employee_id,
            "form_ids": [],
            "process_ids": [],
        }

        with patch(
            "apps.accounts.backends.resolve_current_office_permission_snapshot",
            return_value={
                "role": RoleCodes.OFFICE_PIC,
                "role_name": "SEQ MANAGER",
                "safety_role_name": "DPA",
                "form_ids": ["SAF_F_015"],
                "process_ids": ["SAF_P_023"],
                "has_global_vessel_access": False,
                "employee_id": self.office_pic.employee_id,
                "email": None,
                "department": None,
                "full_name": self.office_pic.full_name,
            },
        ):
            user = PSCJWTAuthentication().get_user(validated_token)

        self.assertEqual(user.role_name, "SEQ MANAGER")
        self.assertEqual(user.safety_role_name, "DPA")
        self.assertEqual(user.form_ids, ["SAF_F_015"])
        self.assertEqual(user.process_ids, ["SAF_P_023"])

    def test_feat_auth_001_happy_path_logout_blacklists_refresh_token(self):
        """PRD FEAT-AUTH-001: logout should invalidate refresh token via blacklist flow."""
        tokens = generate_tokens_for_user(self.vessel_master)
        view = LogoutView.as_view()
        request = self.factory.post(
            "/api/psc/auth/logout/",
            {"refresh": tokens["refresh"]},
            format="json",
        )
        force_authenticate(request, user=self.vessel_master)

        with patch("apps.accounts.views.RefreshToken.blacklist") as mock_blacklist:
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["message"], "Logout successful")
        mock_blacklist.assert_called_once()

    # ---- Gap-closing tests (Session 50) ----

    def test_feat_auth_001_gap_login_response_contains_full_user_payload(self):
        """PRD FEAT-AUTH-001: login response must include role, user_type, vessel_id, full_name."""
        view = LoginView.as_view()
        request = self.factory.post(
            "/api/psc/auth/login/",
            {"username": "vmaster", "password": "secret"},
            format="json",
        )
        with patch("apps.accounts.views.PSCAuthenticationBackend.authenticate", return_value=self.vessel_master):
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        user_data = response.data["data"]["user"]
        self.assertEqual(user_data["user_type"], "VESSEL")
        self.assertEqual(user_data["full_name"], "Vessel Master")
        self.assertIn("role", user_data)
        self.assertIn("vessel_id", user_data)

    def test_feat_auth_001_gap_office_user_login_returns_employee_id(self):
        """PRD FEAT-AUTH-001: office user login response includes employee_id."""
        view = LoginView.as_view()
        request = self.factory.post(
            "/api/psc/auth/login/",
            {"username": "pic001", "password": "secret"},
            format="json",
        )
        with patch("apps.accounts.views.PSCAuthenticationBackend.authenticate", return_value=self.office_pic):
            response = view(request)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        user_data = response.data["data"]["user"]
        self.assertEqual(user_data["user_type"], "OFFICE")
        self.assertEqual(user_data["role"], RoleCodes.OFFICE_PIC)


class TestFEAT_AUTH_002_RoleBasedAccessControl(BaseAuthAPITestCase):
    """FEAT-AUTH-002: Role-Based Access Control."""

    def setUp(self):
        super().setUp()
        self.own_inspection = self.create_inspection(vessel_id=self.vessel_id)
        self.other_vessel_inspection = self.create_inspection(
            vessel_id=self.other_vessel_id,
            port_place="Other Vessel Port",
        )

    def _inspection_detail(self, user=None, inspection_id=None):
        view = InspectionDetailView.as_view()
        target_id = inspection_id or self.own_inspection.id
        request = self.factory.get(f"/api/psc/inspections/{target_id}/")
        if user:
            force_authenticate(request, user=user)

        with patch("apps.inspection.views.vessel_name_annotation", return_value=Value("MV Example")), patch(
            "apps.inspection.views.vessel_code_annotation",
            return_value=Value("EXM"),
        ), patch("apps.inspection.views.imo_number_annotation", return_value=Value("1234567")):
            return view(request, id=target_id)

    def test_feat_auth_002_rbac_protected_endpoint_rejects_unauthenticated(self):
        """PRD FEAT-AUTH-002: protected endpoints must reject unauthenticated requests."""
        view = CurrentUserView.as_view()
        request = self.factory.get("/api/psc/auth/me/")
        response = view(request)
        self.assertIn(response.status_code, (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN))

    def test_feat_auth_002_rbac_vessel_role_sees_only_own_vessel_data(self):
        """PRD FEAT-AUTH-002: vessel users can only access own-vessel records."""
        own_response = self._inspection_detail(
            user=self.vessel_master,
            inspection_id=self.own_inspection.id,
        )
        other_response = self._inspection_detail(
            user=self.vessel_master,
            inspection_id=self.other_vessel_inspection.id,
        )

        self.assertEqual(own_response.status_code, status.HTTP_200_OK)
        self.assertEqual(other_response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_auth_002_rbac_dpa_can_access_all_vessels(self):
        """PRD FEAT-AUTH-002: DPA role can access all vessel data."""
        response = self._inspection_detail(
            user=self.dpa,
            inspection_id=self.other_vessel_inspection.id,
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_feat_auth_002_rbac_unauthorized_action_returns_403_with_message(self):
        """PRD FEAT-AUTH-002: unauthorized role actions return 403 with a clear denial message."""
        review_view = InspectionPICReviewView.as_view()
        request = self.factory.post(
            f"/api/psc/inspections/{self.own_inspection.id}/pic-review/",
            {"comment": "PIC review comment text"},
            format="json",
        )
        force_authenticate(request, user=self.vessel_master)
        response = review_view(request, id=self.own_inspection.id)

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
        self.assertIn("detail", response.data)

    def test_feat_auth_002_rbac_office_roles_can_access_conflict_resolution(self):
        """BACKEND_STRUCTURE 11.1: only Office/DPA roles pass resolve-conflict permission gate."""
        view = SyncResolveConflictView.as_view()
        payload = {"conflict_id": str(uuid.uuid4()), "resolution": "KEEP_SERVER"}

        office_request = self.factory.post("/api/psc/sync/resolve-conflict/", payload, format="json")
        force_authenticate(office_request, user=self.office_pic)
        office_response = view(office_request)

        crew_request = self.factory.post("/api/psc/sync/resolve-conflict/", payload, format="json")
        force_authenticate(crew_request, user=self.vessel_crew)
        crew_response = view(crew_request)

        self.assertNotEqual(office_response.status_code, status.HTTP_403_FORBIDDEN)
        self.assertEqual(crew_response.status_code, status.HTTP_403_FORBIDDEN)

    # ---- Gap-closing tests (Session 50) ----

    def test_feat_auth_002_gap_vessel_crew_blocked_from_create_inspection(self):
        """RBAC matrix: VESSEL_CREW cannot create inspections (403)."""
        view = InspectionCreateView.as_view()
        request = self.factory.post(
            "/api/psc/inspections/create/",
            {
                "vessel_id": str(self.vessel_id),
                "inspection_type": "RS",
                "inspection_date": "2026-01-15",
                "port_place": "Singapore Port",
            },
            format="json",
        )
        force_authenticate(request, user=self.vessel_crew)
        response = view(request)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_auth_002_office_cannot_create_psc_inspection(self):
        """PSC inspection creation is vessel-master only."""
        view = InspectionCreateView.as_view()
        request = self.factory.post(
            "/api/psc/inspections/create/",
            {
                "vessel_id": str(self.vessel_id),
                "inspection_type": "PSC",
                "psc_subtype": "INITIAL",
                "inspection_date": "2026-01-15",
                "port_place": "Singapore Port",
                "mou_id": "TOKYO",
            },
            format="json",
        )
        force_authenticate(request, user=self.office_pic)
        response = view(request)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_auth_002_office_cannot_create_rightship_inspection(self):
        """RightShip inspection creation is vessel-master only."""
        view = InspectionCreateView.as_view()
        request = self.factory.post(
            "/api/psc/inspections/create/",
            {
                "vessel_id": str(self.vessel_id),
                "inspection_type": "RS",
                "inspection_date": "2026-01-15",
                "port_place": "Singapore Port",
            },
            format="json",
        )
        force_authenticate(request, user=self.office_pic)
        response = view(request)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_feat_auth_002_office_can_create_audit_inspection(self):
        """Office users can still create AUDIT inspections."""
        view = InspectionCreateView.as_view()
        request = self.factory.post(
            "/api/psc/inspections/create/",
            {
                "vessel_id": str(self.vessel_id),
                "inspection_type": "AUDIT",
                "inspection_date": "2026-01-15",
                "port_place": "Singapore Port",
                "def_reported": "NO",
            },
            format="json",
        )
        force_authenticate(request, user=self.office_pic)
        with patch("apps.inspection.utils.generate_report_reference", return_value="AUD-2026-001"):
            response = view(request)
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)

    def test_feat_auth_002_gap_office_ssqe_can_view_inspection_detail(self):
        """RBAC matrix: OFFICE_SSQE can view inspection details."""
        ssqe = make_user(
            role=RoleCodes.OFFICE_SSQE,
            user_type="OFFICE",
            user_id="ssqe-user-1",
            full_name="SSQE User",
            employee_id="SSQE001",
        )
        response = self._inspection_detail(user=ssqe, inspection_id=self.own_inspection.id)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
