"""URL namespace for /api/audit/* endpoints."""

from django.urls import path

from apps.inspection.audit.views import (
    AuditAcknowledgeView,
    AuditAttachmentValidateView,
    AuditChecklistMasterView,
    AuditClauseMasterView,
    AuditDetailView,
    AuditExternalCertLinkView,
    AuditExternalCloseoutView,
    AuditFindingCarWorkflowView,
    AuditFindingCreateView,
    AuditFindingIssueCircularView,
    AuditFindingNcClosureView,
    AuditFindingNcDraftView,
    AuditFindingNcPartView,
    AuditFindingNcPdfView,
    AuditFindingObsClosureView,
    AuditFindingObsPartView,
    AuditFindingObsPdfView,
    AuditFailedNotificationListView,
    AuditNotificationOfflineResolveView,
    AuditNotificationRetryView,
    AuditPlanAdditionalView,
    AuditPlanCancelView,
    AuditPlanDetailView,
    AuditPlanExtensionDecideView,
    AuditPlanExtensionRequestView,
    AuditPlanFlagNotifyView,
    AuditPlanListCreateView,
    AuditPlanPdfView,
    AuditRegistrationView,
    AuditReportPdfView,
    AuditRcaTemplateMasterView,
    AuditScorecardView,
    AuditScanValidationQueueView,
    AuditSubmitView,
    AuditVesselOptionListView,
    ExternalAuditOrgDetailView,
    ExternalAuditOrgListCreateView,
    QualifiedAuditorDetailView,
    QualifiedAuditorListCreateView,
    VesselRoDelegationDetailView,
    VesselRoDelegationListCreateView,
)

app_name = "audit"
urlpatterns = [
    path(
        "vessels/",
        AuditVesselOptionListView.as_view(),
        name="audit-vessel-options",
    ),
    path(
        "dpa/notifications/failed/",
        AuditFailedNotificationListView.as_view(),
        name="audit-failed-notification-list",
    ),
    path(
        "dpa/scan-validation-queue/",
        AuditScanValidationQueueView.as_view(),
        name="audit-scan-validation-queue",
    ),
    path(
        "notifications/<uuid:id>/retry/",
        AuditNotificationRetryView.as_view(),
        name="audit-notification-retry",
    ),
    path(
        "notifications/<uuid:id>/offline/",
        AuditNotificationOfflineResolveView.as_view(),
        name="audit-notification-offline",
    ),
    path(
        "attachments/<uuid:id>/validate/",
        AuditAttachmentValidateView.as_view(),
        name="audit-attachment-validate",
    ),
    path(
        "plans/",
        AuditPlanListCreateView.as_view(),
        name="audit-plan-list-create",
    ),
    path(
        "plans/<uuid:id>/",
        AuditPlanDetailView.as_view(),
        name="audit-plan-detail",
    ),
    path(
        "plans/additional/",
        AuditPlanAdditionalView.as_view(),
        name="audit-plan-additional",
    ),
    path(
        "plans/<uuid:id>/extension/",
        AuditPlanExtensionRequestView.as_view(),
        name="audit-plan-extension-request",
    ),
    path(
        "plans/<uuid:id>/extension/decide/",
        AuditPlanExtensionDecideView.as_view(),
        name="audit-plan-extension-decide",
    ),
    path(
        "plans/<uuid:id>/flag-notify/",
        AuditPlanFlagNotifyView.as_view(),
        name="audit-plan-flag-notify",
    ),
    path(
        "plans/<uuid:id>/cancel/",
        AuditPlanCancelView.as_view(),
        name="audit-plan-cancel",
    ),
    path(
        "audits/",
        AuditRegistrationView.as_view(),
        name="audit-registration",
    ),
    path(
        "audits/<uuid:id>/",
        AuditDetailView.as_view(),
        name="audit-detail",
    ),
    path(
        "audits/<uuid:id>/scorecard/",
        AuditScorecardView.as_view(),
        name="audit-scorecard",
    ),
    path(
        "audits/<uuid:id>/submit/",
        AuditSubmitView.as_view(),
        name="audit-submit",
    ),
    path(
        "audits/<uuid:id>/acknowledge/",
        AuditAcknowledgeView.as_view(),
        name="audit-acknowledge",
    ),
    path(
        "audits/<uuid:id>/external/close/",
        AuditExternalCloseoutView.as_view(),
        name="audit-external-closeout",
    ),
    path(
        "audits/<uuid:id>/certs/link/",
        AuditExternalCertLinkView.as_view(),
        name="audit-external-cert-link",
    ),
    path(
        "audits/<uuid:id>/pdf/f601/",
        AuditPlanPdfView.as_view(),
        name="audit-plan-pdf",
    ),
    path(
        "audits/<uuid:id>/pdf/f602/",
        AuditReportPdfView.as_view(),
        name="audit-report-pdf",
    ),
    path(
        "audits/<uuid:id>/findings/",
        AuditFindingCreateView.as_view(),
        name="audit-finding-create",
    ),
    path(
        "masters/checklists/",
        AuditChecklistMasterView.as_view(),
        name="audit-master-checklists",
    ),
    path(
        "masters/clauses/<str:book>/",
        AuditClauseMasterView.as_view(),
        name="audit-master-clauses",
    ),
    path(
        "masters/rca-templates/",
        AuditRcaTemplateMasterView.as_view(),
        name="audit-master-rca-templates",
    ),
    path(
        "masters/qualified-auditors/",
        QualifiedAuditorListCreateView.as_view(),
        name="audit-master-qualified-auditors",
    ),
    path(
        "masters/qualified-auditors/<uuid:id>/",
        QualifiedAuditorDetailView.as_view(),
        name="audit-master-qualified-auditor-detail",
    ),
    path(
        "masters/external-audit-orgs/",
        ExternalAuditOrgListCreateView.as_view(),
        name="audit-master-external-audit-orgs",
    ),
    path(
        "masters/external-audit-orgs/<uuid:id>/",
        ExternalAuditOrgDetailView.as_view(),
        name="audit-master-external-audit-org-detail",
    ),
    path(
        "masters/ro-delegations/",
        VesselRoDelegationListCreateView.as_view(),
        name="audit-master-ro-delegations",
    ),
    path(
        "masters/ro-delegations/<uuid:id>/",
        VesselRoDelegationDetailView.as_view(),
        name="audit-master-ro-delegation-detail",
    ),
    path(
        "findings/<uuid:id>/car/workflow/",
        AuditFindingCarWorkflowView.as_view(),
        name="finding-car-workflow",
    ),
    path(
        "findings/<uuid:id>/nc/",
        AuditFindingNcClosureView.as_view(),
        name="finding-nc-closure",
    ),
    path(
        "findings/<uuid:id>/nc/draft/",
        AuditFindingNcDraftView.as_view(),
        name="finding-nc-draft",
    ),
    path(
        "findings/<uuid:id>/nc/part-b/",
        AuditFindingNcPartView.as_view(part_name="part-b"),
        name="finding-nc-part-b",
    ),
    path(
        "findings/<uuid:id>/nc/part-c/",
        AuditFindingNcPartView.as_view(part_name="part-c"),
        name="finding-nc-part-c",
    ),
    path(
        "findings/<uuid:id>/nc/part-d/",
        AuditFindingNcPartView.as_view(part_name="part-d"),
        name="finding-nc-part-d",
    ),
    path(
        "findings/<uuid:id>/nc/part-e/",
        AuditFindingNcPartView.as_view(part_name="part-e"),
        name="finding-nc-part-e",
    ),
    path(
        "findings/<uuid:id>/nc/part-f/",
        AuditFindingNcPartView.as_view(part_name="part-f"),
        name="finding-nc-part-f",
    ),
    path(
        "findings/<uuid:id>/nc/part-g/",
        AuditFindingNcPartView.as_view(part_name="part-g"),
        name="finding-nc-part-g",
    ),
    path(
        "findings/<uuid:id>/pdf/nc/",
        AuditFindingNcPdfView.as_view(),
        name="finding-nc-pdf",
    ),
    path(
        "findings/<uuid:id>/obs/",
        AuditFindingObsClosureView.as_view(),
        name="finding-obs-closure",
    ),
    path(
        "findings/<uuid:id>/pdf/obs/",
        AuditFindingObsPdfView.as_view(),
        name="finding-obs-pdf",
    ),
    path(
        "findings/<uuid:id>/obs/part-b/",
        AuditFindingObsPartView.as_view(part_name="part-b"),
        name="finding-obs-part-b",
    ),
    path(
        "findings/<uuid:id>/obs/part-c/",
        AuditFindingObsPartView.as_view(part_name="part-c"),
        name="finding-obs-part-c",
    ),
    path(
        "findings/<uuid:id>/obs/part-d/",
        AuditFindingObsPartView.as_view(part_name="part-d"),
        name="finding-obs-part-d",
    ),
    path(
        "findings/<uuid:id>/issue-circular/",
        AuditFindingIssueCircularView.as_view(),
        name="finding-issue-circular",
    ),
]
