# Generated by Django 5.2.10 on 2026-02-06 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField()),
                ('server_data', models.TextField()),
                ('vessel_data', models.TextField()),
                ('conflicting_fields', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('KEEP_SERVER', 'Keep Server'), ('KEEP_VESSEL', 'Keep Vessel'), ('REOPEN_FOR_MERGE', 'Reopen for Merge')], max_length=30, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'psc_sync_conflict',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['vessel_id'], name='psc_sync_co_vessel__10b569_idx'), models.Index(fields=['status'], name='psc_sync_co_status_003cf9_idx'), models.Index(fields=['entity_type', 'entity_id'], name='psc_sync_co_entity__c91d54_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_id', models.UUIDField(db_index=True)),
                ('sync_id', models.UUIDField(unique=True)),
                ('sync_type', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull')], max_length=20)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('records_sent', models.IntegerField(blank=True, null=True)),
                ('records_received', models.IntegerField(blank=True, null=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'psc_sync_log',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['vessel_id'], name='psc_sync_lo_vessel__fa9a19_idx'), models.Index(fields=['sync_id'], name='psc_sync_lo_sync_id_710f2a_idx'), models.Index(fields=['-created_date'], name='psc_sync_lo_created_b4c4d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel_id', models.UUIDField(unique=True)),
                ('last_sync_at', models.DateTimeField()),
                ('last_sync_id', models.UUIDField(blank=True, null=True)),
                ('last_server_version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'psc_sync_token',
                'indexes': [models.Index(fields=['vessel_id'], name='psc_sync_to_vessel__76b7de_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField()),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('sync_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('server_version', models.IntegerField(blank=True, null=True)),
                ('client_version', models.IntegerField(blank=True, null=True)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sync.synclog')),
            ],
            options={
                'db_table': 'psc_sync_log_detail',
                'indexes': [models.Index(fields=['sync_log'], name='psc_sync_lo_sync_lo_24ae8e_idx'), models.Index(fields=['entity_type', 'entity_id'], name='psc_sync_lo_entity__f5172c_idx')],
            },
        ),
    ]
